### ISSUE TITLE
Online demo url specified in readme file throws an error

### ISSUE THREAD

**Issue by Pramod2392** [simplcommerce/SimplCommerce#1015]
The online demo(store front) url mentioned in the README.md throws an error.

URL : http://demo.simplcommerce.com/ 

Screen shot of the error message is attached.
<img width="960" alt="Error" src="https://user-images.githubusercontent.com/34315343/140790121-3da009d3-0f19-4159-813f-84e7c9da0c13.png">

**Comment by thiennn** [comment]
It looks fine on my side. @Pramod2392  Could you please help me check it again
