### ISSUE TITLE
'Update-Database' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by shaikmdrafi24** [simplcommerce/SimplCommerce#104]
I am getting Error  "The term 'Update-Database' is not recognized as the name of a cmdlet, function, script file, or operable program" while executing command "Update-Database" in Package Manager Console Window after building whole solution twice.

![error1](https://cloud.githubusercontent.com/assets/25167783/22009494/9ccd7502-dca9-11e6-9f6f-88ef08a50acd.png)

Please help me resolve this issue.
Thanks in advance.

**Comment by thiennn** [comment]
@shaikmdrafi24

Please choose the SimplCommerce.WebHost as the Default project, Update-Database only available in the context of that project

**Comment by shaikmdrafi24** [comment]
Thanks for replay.

Getting same error even thought I choose SimplCommerce.WebHost as the Default project

![error2](https://cloud.githubusercontent.com/assets/25167783/22015308/81e77788-dcc7-11e6-831a-dc13bd4a7040.png)

Help me please.

**Comment by thiennn** [comment]
@shaikmdrafi24 Did the dotnet restore and build successfully?

**Comment by shaikmdrafi24** [comment]
Yes , Both were done successfully.

**Comment by MaherJendoubi** [comment]
@shaikmdrafi24 Which version of nuget do you have?

**Comment by shaikmdrafi24** [comment]
Nuget version : **3.5.0.1484**

**Comment by MaherJendoubi** [comment]
@shaikmdrafi24  the same version that  I have. Have you tested Update-Database with capital letters for U and D?

**Comment by thiennn** [comment]
Open  command prompt to go \src\SimplCommerce.WebHost and type "dotnet ef database update" Enter

**Comment by shaikmdrafi24** [comment]
@MaherJendoubi  It works with Capital letters (Update-Database).

Thank you @MaherJendoubi , @thiennn

**Comment by MaherJendoubi** [comment]
@shaikmdrafi24 You are welcome. It's good to know that Update-Database is case-sensitve.

**Comment by thiennn** [comment]
Actually, It's not case sensitive. However, the .net core and ef core tooling is not stable. Sometime all you need is close and re-open Visual Studio again.
