### ISSUE TITLE
Permission is needed to access the page for ADMIN

### ISSUE THREAD

**Issue by shaikmdrafi24** [simplcommerce/SimplCommerce#105]
I am logging with admin user and getting Error while Redirecting to Admin Dashboard.
"**We are sorry!
Permission is needed to access the page.**"   

![error3](https://cloud.githubusercontent.com/assets/25167783/22020919/a99f5912-dce0-11e6-9d11-88ad9dc5383d.png)

can someone please help me.
Thanks in advance.

**Comment by thiennn** [comment]
I don't know why you get that problem. But you can go to the database. Open the table Core_User, Core_Role and Core_UserRole and make sure that the user have the admin role

**Comment by shaikmdrafi24** [comment]
@thiennn  Thank you , Actually table **Core_UserRole** was empty.

**Comment by thiennn** [comment]
The https://github.com/simplcommerce/SimplCommerce/blob/master/src/Database/StaticData.sql should have inserted into it

**Comment by shaikmdrafi24** [comment]
Yes , I have executed the same SQL script and working fine now.
