### ISSUE TITLE
Update file global.json

### ISSUE THREAD

**Issue by TiennMinhh** [simplcommerce/SimplCommerce#1059]
You might run into an error when try to run update-database or build solution. The solution is update sdk version in file global.json: 
{
   "sdk": {
     "version": "8.0.0",
	 "rollForward": "latestMinor",
	 "allowPrerelease": false
   }
}

**Comment by Abhi441** [comment]
Kindly Update it 

{
"sdk": {
"version": "8.0.0",
"rollForward": "latestMinor",
"allowPrerelease": false
}
}
