### ISSUE TITLE
Add to Cart is not working on the home page

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#115]
![image](https://cloud.githubusercontent.com/assets/1798510/22856820/d5562a14-f099-11e6-961a-681d818cf259.png)

**Comment by thiennn** [comment]
@MaherJendoubi , It redirect to project detail page?

**Comment by MaherJendoubi** [comment]
@thiennn Yes for the three first products in the last products section.

**Comment by thiennn** [comment]
Because the there products have options (colors). Users have to choose a specific option. It's is complex to do that on the product thumbnail view, so I redirect to the detail view.
I am thinking about changing the text of the button to "See options" for this case.

**Comment by MaherJendoubi** [comment]
I see. "See options" makes sense but customers prefer  to see details before buying each product. Have a look here : http://www.cdiscount.com/ or here : https://www.aliexpress.com/

**Comment by thiennn** [comment]
In some cases, when we know clearly about the product, we can add to cart without go to the product details

**Comment by MaherJendoubi** [comment]
Even if we know the product, we should make sure to read the details. No one garantee that details is not updated.

**Comment by thiennn** [comment]
This just an option, people can go to the detail very easily if they want to :)
Like: https://www.amazon.com/gp/goldbox/
