### ISSUE TITLE
Russian Localization

### ISSUE THREAD

**Issue by marker91** [simplcommerce/SimplCommerce#121]

**Comment by thiennn** [comment]
There have been some Russian translations I think.
Btw, I don't know Russian. It would be great if you can help.

**Comment by marker91** [comment]
I found some Russian translations, but it's not fully and i wanted implement full translation for all View in this project, but i have some questions, how it make right. 
1) I not found default culture and resource, how it work?
2) If i add @Localizer[] for all string at View, it will not cause problems in the future?
3) I wanded add Russia country, stateOrProvinces and Districts in StaticDatabase, but i understand there are some differences, when specifying the address we use the following procedure(from general to specific): country, then region, then city, then street and etc, and in some cases add district at city. We can create some mapping, but whether it's the right?(this project involves support for the international standards? =) )

**Comment by thiennn** [comment]
1. The default culture is en-us.
2. No, no problem in the future
3. The current structure is: Country --> StateOrProvice --> District --> AddressLine1 , AddressLine2.

**Comment by Markeli** [comment]
@marker91,  are you working on this issue?

**Comment by marker91** [comment]
@Markeli in the near future no

**Comment by thiennn** [comment]
Let close this because there is no action for a long time.
