### ISSUE TITLE
Can't start on Win 10 IIS Express

### ISSUE THREAD

**Issue by lzymll** [simplcommerce/SimplCommerce#122]
Environment:  Win10, VS Studio 2017 RC 

When I publish to folder, and add a site on IIS Express, http://127.0.0.1 it can't start

> An error occurred while starting the application.
> .NET Core X86 v4.1.1.0    |   Microsoft.AspNetCore.Hosting version 1.1.0-rtm-22752    |    Microsoft Windows 10.0.14393

**Comment by thiennn** [comment]
@lzymll please post the error in details and make sure that you have followed the instructions

**Comment by lzymll** [comment]
I found the problem. when publish to local folder, the module  bin don't have dll file, like 
C:\publish\sctest\Modules\SimplCommerce.Module.Search\bin , there is no dll file.

**Comment by thiennn** [comment]
@lzymll ,

I think you need to change from "Debug" to "Release" in the src\SimplCommerce.WebHost\gulpfile.js

Build, and Publish again

**Comment by amohsyn** [comment]
Siri am still unable to publish on iis.
