### ISSUE TITLE
Can not see the category image on the menu

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#134]
![image](https://cloud.githubusercontent.com/assets/1798510/24166759/a91ce35e-0e74-11e7-8b8f-41e4be626fd0.png)
![image](https://cloud.githubusercontent.com/assets/1798510/24166780/c37a3260-0e74-11e7-9393-f6acfc790d03.png)

**Comment by thiennn** [comment]
I think we shouldn't show these category images in the menu. This category images are  used for other purposes. For example: a page that list all the product categories, or show in the category details page.
It depends on the layout design of the site. Developers have to customize for their own need.

https://github.com/simplcommerce/SimplCommerce/issues/92. Menu management is the right place we should manage the icon for the menu
