### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#15]

**Comment by villanus** [comment]
URLs should have a language slug such as en-us and head should have href Lang meta tags for translations.   This will allow for seo for localized pages

**Comment by thiennn** [comment]
At this stage we would like to keep thing as simple as possible. Most of the cases, for there is only one language per deployment, but we can choose which language we want during the installation.

**Comment by thiennn** [comment]
Close this item because the localization core feature has been complete. Next step is localize per language
