### ISSUE TITLE
UserRole Migration generated excess foreign keys RoleId1 and UserId1

### ISSUE THREAD

**Issue by chenasdf** [simplcommerce/SimplCommerce#166]
When I dig into the code, I found that because of the design of UserRole class, after migration, some excess foreign keys generated by EF Add-Migration command. Althought I didn't find these foreign keys in the source code,  have you delete the excess foreign keys manually after run the add-migration command? Is there any problems? 

![excess foreigh keys](https://cloud.githubusercontent.com/assets/13676331/25029783/28e156f2-20f3-11e7-89b2-24b8928e3adf.jpg)

**Comment by thiennn** [comment]
Hi @chenasdf 

I am not sure I understand your problem. The image is broken also. Could you please update it?

**Comment by thiennn** [comment]
No, we haven't seen this issue, The UserRole.cs is correct, and we also have the custom mapping here https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Core/Data/CoreCustomModelBuilder.cs

Which RDBMS are use using?

**Comment by chenasdf** [comment]
Thanks thiennn, I have found my issue, because missing the CoreCustomModelBuilder.
