### ISSUE TITLE
As an admin I would like to see order history of users

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#174]

**Comment by olivercross** [comment]
@thiennn Is this still needed/required?

**Comment by thiennn** [comment]
Yes

**Comment by olivercross** [comment]
@thiennn I can take this feature on and create a pull request when finished

**Comment by thiennn** [comment]
Awesome!. Just for a reference https://demo.pixelcave.com/proui/page_ecom_customer_view.php

**Comment by olivercross** [comment]
Great, thanks. I can probably pick up a few more of the issues tagged with help wanted in time

**Comment by jducobu** [comment]
Is this issue already developed ?
Some news from @olivercross ?

**Comment by jducobu** [comment]
The reference imply to create a user readonly view with user info, user order, user address, ...  Is it correct ?

**Comment by alessalessio** [comment]
is this issue still looking for someone who takes care of it ? or is it in progress?

**Comment by thiennn** [comment]
It would be great if you can take care of it.

**Comment by alessalessio** [comment]
@thiennn sure. can we have a quick chat on gitter?

**Comment by thiennn** [comment]
in the order list, the other can be filtered by customer. we might not need an another view
