### ISSUE TITLE
When deploy to hosting server I get this error

### ISSUE THREAD

**Issue by jolub** [simplcommerce/SimplCommerce#178]
When I run in hosting server
I get this error....

2017-04-25 22:55:06.280 -07:00 [Fatal] Application startup exception
Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MvcRouteHandler (ReflectionActivator), Services = [Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ActionInvokerFactory (ReflectionActivator), Services = [Microsoft.AspNetCore.Mvc.Infrastructure.IActionInvokerFactory], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IActionInvokerProvider[] (DelegateActivator), Services = [System.Collections.Generic.IEnumerable`1[[Microsoft.AspNetCore.Mvc.Abstractions.IActionInvokerProvider, Microsoft.AspNetCore.Mvc.Abstractions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerActionInvokerProvider (ReflectionActivator), Services = [Microsoft.AspNetCore.Mvc.Abstractions.IActionInvokerProvider], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = 

....
...
...
...
...

Everything works great on localhost with visual studio 2017

**Comment by thiennn** [comment]
@jolub please make sure that you have the correct .net core installed in the server.
And check the modules folder in the root of the website. Each modules should have .dll in the bin directory.

**Comment by jolub** [comment]
Hi Thien

I test with this hosting Compay
http://www.smarterasp.net/hosting_plans

They have Asp net core 1.0 AND 1.1

I will check the files Inder webfolder

Thanks in Advance



El 26 abr. 2017 1:52 AM, "Thien Nguyen Le Quynh" <notifications@github.com>
escribió:

@jolub <https://github.com/jolub> please make sure that you have the
correct .net core installed in the server.
And check the modules folder in the root of the website. Each modules
should have .dll in the bin directory.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/simplcommerce/SimplCommerce/issues/178#issuecomment-297256942>,
or mute the thread

**Comment by thiennn** [comment]
And also please post the full error message

**Comment by jolub** [comment]
I checked.
not exists any dll file inside bin module folder
I test copy and check again, but have the same error

Seems like publishing from visual studio not copy all required files,
what are wrong?

**Comment by thiennn** [comment]
This is a know issue. The workaround is copy entire the modules folder manually.
Please post the full error message. I think you might also having the data connection problem.

**Comment by jolub** [comment]
Thiennn

I dont know wich files copy to my hosting server, I am confused.

Can you send me a screenshoot or tree structure from your production server
for check how you have dlls configuration, etc. (only for modules?)

**Comment by thiennn** [comment]
![psimplcommerce](https://cloud.githubusercontent.com/assets/289607/25441534/b3196f98-2acc-11e7-813c-11bb96d29bd6.png)

Post the full error message, please.
Btw, I have fixed the publishing issue

**Comment by jolub** [comment]
Please, un your Modules folder, also one Module only for View your files

**Comment by thiennn** [comment]
The modules folder in production is the same as in your local host

**Comment by jolub** [comment]
Thanks a lot,
System is running now!

**Comment by thiennn** [comment]
Cool
