### ISSUE TITLE
Consider using MSBUILD to copy modules to the WebHost

### ISSUE THREAD

**Issue by joshua-mng** [simplcommerce/SimplCommerce#193]
You can consider trying to use MSBUILD to copy module files into the host application.

Defining separate .targets file in the solution with the following content

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<WebHostPath>..\..\SimplCommerce.WebHost</WebHostPath>
	</PropertyGroup>	

	<Target Name="CopyModule" AfterTargets="Build">
		<ItemGroup>			
			<ModuleOutput Include="$(OutputPath)\*.*" />
			<ModuleView Include="Views\*.*" />
			<ModuleAsset Include="wwwroot\*.*" />
			<ModuleMetadata Include="module.json" />
		</ItemGroup>
		
		<Copy SourceFiles="@(ModuleOutput)" DestinationFolder="$(WebHostPath)\Modules\$(MSBuildProjectName)\bin" />		
		<Copy SourceFiles="@(ModuleView)" DestinationFolder="$(WebHostPath)\Modules\$(MSBuildProjectName)\Views\%(ModuleView.RecursiveDir)" />
		<Copy SourceFiles="@(ModuleAsset)" DestinationFolder="$(WebHostPath)\wwwroot\modules\$(MSBuildProjectName.ToLowerInvariant())" />
		<Copy SourceFiles="@(ModuleMetadata)" DestinationFolder="$(WebHostPath)\Modules\$(MSBuildProjectName)" />
	</Target>
</Project>
```

And importing this file in every module project files.

I guess it would make things a little bit faster if number modules increases.

**Comment by thiennn** [comment]
I have tried to write a custom MSBuild Task before. But there was an issue that when we are testing the website in IIS Express with Visual Studio. Dlls in the WebHost are kept by the webserver and we cannot override them.

**Comment by joshua-mng** [comment]
i'm employing shadow copy method in my app, like copying module DLL files to another directory (~/modules/bin/ etc), and then loading from that location instead. That way you will have no problem, but needs to restart the application for the changes to take effect (and that's not problem anyway).

**Comment by thiennn** [comment]
Thank you for your information. 
Currently in the gulpfile, there are is also a task called "copy-static". It only copy static content such as .cshtml, javascript, css, images and it's very helpful if you only change the layout stuff. Run this task and refresh the browser. 
For the future, we are going to implement a modules store (marketplace), and a cli that consists of some commands to pack and publish modules.
The current implement with gulp is fine. However we might revisit this
