### ISSUE TITLE
Changing the name "SimplCommerce"

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#196]
There are some confusion about the name SimplCommerce and it is not a good marketing name also. I am thinking about changing it.

Finding a good name is difficult task as most of them are not available. Luckily, I have bought 2 domains below: 

- eCommerceSharp
- eComSharp

Which one do you prefer? You can suggest a better name, we will consider it. (Just please make sure the name you suggested is available: domain name, and github repository)

Thanks

**Comment by masoud-dehghanpour** [comment]
finding good name is kinda disaster for me.
I prefer eComSharp

**Comment by balasratran** [comment]
eComSharp

**Comment by thiennn** [comment]
After Receiving many feedback and advice. We decided to keep the current name.

Thanks
