### ISSUE TITLE
EF Migration

### ISSUE THREAD

**Issue by masoud-dehghanpour** [simplcommerce/SimplCommerce#197]
Hi

you add models to context with `RegisterEntities ` method.
how do you create migration with dynamically add models from each module?
i tried, bud it's didn't work.

and how about migration it each module, do you have any idea?

thanks

**Comment by thiennn** [comment]
EF Migration will call instantiate Startup class, then call ConfigureService which then scan all the .dlls in modules in WebHost/Modules and load them up. The RegisterEntities method registers entities that in inherit from EntityBase

**Comment by masoud-dehghanpour** [comment]
I think my question was wrong, let me correct it.

when i use `Add-Migration`, the result is migration class with nothing inside `Up` and `Down` method.
when i add `DbSet` of some models in Context, `Add-Migration` works correct but if i use `RegisterEntities` nothing generate.

**Comment by thiennn** [comment]
Does your models class inherit from EntityBase?

**Comment by masoud-dehghanpour** [comment]
I found the problem
I changed the `EntityBase` to generic (for primary key type)
because of that it's didn't work.

sorry for wasting your time
