### ISSUE TITLE
database can't use,only read ,i can't write dowm and modify database.

### ISSUE THREAD

**Issue by stephenzhang88** [simplcommerce/SimplCommerce#202]
when i want to Edit Category
:Could not add category.
Edit Product
when i want to Edit Category
Could not add category.

but i can create new category and anything,just can't modify and delete..
i don't know what happen?

sql server 2012

**Comment by thiennn** [comment]
@stephenzhang88 please tell how where and how you deployed the site and the full error message that you got

**Comment by stephenzhang88** [comment]
i send the email for you.

**Comment by thiennn** [comment]
because of WebDAV, PUT has been disabled on IIS. Enable PUT the system works
