### ISSUE TITLE
Add DisplayOrder to MenuItem

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#203]

**Comment by AdSoares** [comment]
Hi thiennn. Can I try to help with this issue?

**Comment by thiennn** [comment]
@AdSoares sure. Looking forward to seeing your pull request

**Comment by amioneworld** [comment]
Is this still open? or someone working on it?

**Comment by thiennn** [comment]
yes, it's still open. Please give a hand
