### ISSUE TITLE
 Option Values - Color

### ISSUE THREAD

**Issue by marcosph** [simplcommerce/SimplCommerce#204]
When the user adds the name of a color with compound name in the values of options, for example Nany blue. 
![variatins](https://cloud.githubusercontent.com/assets/5003847/26757458/1abe7ad4-4892-11e7-8fac-7e68d3d1b2f4.JPG)

When the customer is going to make a purchase of product with the color Nany blue, he could not, because a product message not avalilable appears. 
![navy](https://cloud.githubusercontent.com/assets/5003847/26757461/305e380c-4892-11e7-868e-0ff875371cfb.JPG)

This error occurs in the following line of code:
path(SimplCommerce-master\src\Modules\SimplCommerce.Module.Catalog\wwwroot\product-detail.js
![code](https://cloud.githubusercontent.com/assets/5003847/26757463/3b9d64fe-4892-11e7-9392-1f80c02896be.JPG)

**Comment by thiennn** [comment]
@marcosph Please check to make sure that the product variation (Nany blue) have "Is Allowed To Order" checked and "Out Of Stock" unchecked

**Comment by marcosph** [comment]
I already checked, two attributes are according to what you requested, however the error is still occurring (not available). This error occurs only with compound word, for example "Nany Blue". When you add a non-compound color (Red), the error does not occur.
1- Color Red
![red](https://cloud.githubusercontent.com/assets/5003847/26785372/62e24be6-49d8-11e7-982a-04fe74ab192c.JPG)

2- Color Navy Blue
![navyblue](https://cloud.githubusercontent.com/assets/5003847/26785398/83ba2faa-49d8-11e7-9d21-349334bb6816.JPG)
