### ISSUE TITLE
Add menu items adds duplicate

### ISSUE THREAD

**Issue by pahlot** [simplcommerce/SimplCommerce#207]
The current behaviour adds multiple instances of the same category if you click "Add" multiple times, a common user behaviour when they might be adding multiple categories but forget to add one so they select another category.

Fix 1 (simple): de-select all checkboxes when "add" is clicked.
Fix 2 (ideal): Do a duplicate check and do not add duplicate categories.

**Comment by thiennn** [comment]
I prefer the fix 1

**Comment by kwinyyyc** [comment]
@thiennn Hi, if this issue is still open, I would like to work on it.

**Comment by thiennn** [comment]
@kwinyyyc great!, looking forward to seeing your pull request
