### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by dongfangshen** [simplcommerce/SimplCommerce#215]
Prerequisites
SQL Server
Visual Studio 2017 Preview 3 with .NET Core Tools 2.0 Preview 1

I can't find Visual Studio 2017 Preview 3 on this website:
https://www.visualstudio.com/zh-hans/thank-you-downloading-visual-studio/?ch=pre&sku=Enterprise&rel=15
and I only find the lastest version:
Microsoft Visual Studio Enterprise 2017 Preview
Version 15.3.0 Preview 2.1
my computer have installed .NET Core 2.0.0 Preview 1,but I use the version--15.3.0 Preview 2.1 to compile this solution,there are some mistakes:
“SimplCommerce.Module.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”assembly“SimplCommerce.Module.Core”used “System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”version is above“System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”assembly“System.Runtime”

How can I do that? thank you

**Comment by MaherJendoubi** [comment]
@dongfangshen There is no Preview 3 yet for VS2017. It is a typo. Sorry about that.

**Comment by thiennn** [comment]
@dongfangshen I use 15.3 Preview. Haven't try the Version 15.3.0 Preview 2 yet. I try it today to see whether I get the error like you

**Comment by dongfangshen** [comment]
@thiennn if you have a conclusion,please let me know,thank you

**Comment by thiennn** [comment]
@dongfangshen tested on Version 15.3.0 Preview 2. Everything ok, Can you share screenshot of the error

**Comment by dongfangshen** [comment]
![pic20170623002232](https://user-images.githubusercontent.com/15624890/27444877-4a13a5d0-57aa-11e7-821b-0ad3cc3724d5.png)

**Comment by thiennn** [comment]
Did you get the latest source code in branch master or from the release?

**Comment by thiennn** [comment]
.NET Core 2.0 Preview 1-005977. I tried, but cannot reproduce the issue. Can you upload the code somewhere so that I can take a look?

**Comment by dongfangshen** [comment]
thank you for your patience.
I am sure that the code is ok,because i deleted the old one,and I retrieved the new code again,but when i built this solution,it it failed.
If I want to build the solution successful,what are prerequisites? because I follow your prerequisites,but it is not successful.

**Comment by CristiCor** [comment]
I have some errors too !
first dotnet --version in 1.0.4 and I can't upgrade 
![error2](https://user-images.githubusercontent.com/26934899/27588571-5201a828-5b51-11e7-8a0e-641b11763ef5.png)
in Package Manager 
![microsoft netcore app](https://user-images.githubusercontent.com/26934899/27588614-6feb4cf4-5b51-11e7-97aa-818943200ae2.png)

and this is Error Compiling list
![error1](https://user-images.githubusercontent.com/26934899/27588633-856340be-5b51-11e7-8247-53552dcd778e.png)

I lost few hours .. and I can't get it works.
Thank you !

**Comment by thiennn** [comment]
Hi @CristiCor ,

You need VS 15.3 preview and dotnet core sdk 2.0 preview installed

**Comment by dongfangshen** [comment]
I tried on another computer,it can build successful.
