### ISSUE TITLE
Error start when update Netcore 2 preview 2 

### ISSUE THREAD

**Issue by balasratran** [simplcommerce/SimplCommerce#218]
![image](https://user-images.githubusercontent.com/26430195/27907288-3eacbd2c-6271-11e7-89ae-24ea25ddf75f.png)

**Comment by thiennn** [comment]
@balasratran please share your appsettings.json

**Comment by balasratran** [comment]
`{
  "Kestrel": {
    "Endpoints": {
      "Localhost": {
        "Address": "127.0.0.1",
        "Port": "51104"
      }
    }
  },
  "ConnectionStrings": {
    "DefaultConnection": "Server=LAPTOP;Database=SimplCommerce;uid=sa;pwd=123;Trusted_Connection=True;MultipleActiveResultSets=true"
  },
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
  }
}
`
Please see help me.

**Comment by thiennn** [comment]
I haven't encounter this issue. Close VS and reopen again, run by command line, checking the environment variable,  hosting.json 

Try to google with the keyword "HTTPS endpoints can only be configured using KestrelServerOptions.Listen()".

**Comment by thiennn** [comment]
@balasratran ,

I found it, in preview 2. dotnet run will try to load the setting from SimplCommerce.WebHost\Properties\launchSettings.json, find https and changed to http to resolve this issue
