### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by jlusarreta** [simplcommerce/SimplCommerce#219]
We are thinking of starting to use this project.

Do you line up to make it multi-linguage?

**Comment by MaherJendoubi** [comment]
@jlusarreta I can do the support for Arabic and French languages. I know a little of Korean but I am not a native speaker.

**Comment by jlusarreta** [comment]
I can do it in spanish.
My question is about multilanguage for products pages or menu.... and make 
multisites web or sites with different languages ( ..../es .../en,.....)

**Comment by MaherJendoubi** [comment]
Multilanguage feature is supported. @thiennn Would you please confirm that?

**Comment by thiennn** [comment]
For dynamic content like products, at the moment we don't support multiple languages. The only option is to deploy multiple instances and use a reverse proxy to make the url look like a single site. But the drawback is the data of each instances is separated
