### ISSUE TITLE
Error deploy server 2012 r2

### ISSUE THREAD

**Issue by balasratran** [simplcommerce/SimplCommerce#224]
Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE' with physical root 'C:\inetpub\wwwroot\' failed to start process with commandline 'dotnet .\SimplCommerce.WebHost.dll', ErrorCode = '0x80004005 : c0000135.

Please see help me

**Comment by thiennn** [comment]
Have you installed .net core and .net core modules in the server?  Or which is the .net core version in the server.

**Comment by balasratran** [comment]
@thiennn  
I successfully deployed on server 2016 but 2012 was bugs and I installed the full core

**Comment by thiennn** [comment]
I haven't encountered this issue, google by the error code. this might be a permission issue

**Comment by thiennn** [comment]
@balasratran  How's it going? Has you resolved this issue?

**Comment by balasratran** [comment]
@thiennn 
Maybe my server has a problem. I was deploy on 1 server and was running. I will check that server later. Thank you
