### ISSUE TITLE
A better way to copy dependency of modules 

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#227]
Currently when a module reference to packages. By default, these packages are not being copied to the build output and cause the module cannot load these dependencies. 

The temporary workaround is set <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>. However this CopyLocalLockFileAssemblies set to true, too many system assemblies are copied to the build output also.

We want to copy only packages that we explicitly referenced, not assemblies are bundled with AspnetCore

**Comment by hishamco** [comment]
This will be tracked in #570

**Comment by thiennn** [comment]
In development, we can set CopyLocalLockFileAssemblies to true OR set isBundledWithHost to true and add project reference in the WebHost. To publishing a module as self contained, use dotnet publish

**Comment by kenc82** [comment]
I got ten of these emails saying the same thing today and i unsubscribed. Next step is this
[cid:A373595C-0AA3-480C-8250-95A4E02CBA4D]


On Oct 1, 2018 at 6:16 PM, <Thien Nguyen Le Quynh<mailto:notifications@github.com>> wrote:


In development, we can set CopyLocalLockFileAssemblies to true OR set isBundledWithHost to true and add project reference in the WebHost. To publishing a module as self contained, use dotnet publish

**Comment by thiennn** [comment]
@kenc82 Please unwatch this project and stop posting similar comments. You should learn how to use GitHub first 

![unwatch](https://user-images.githubusercontent.com/289607/46376150-83f93280-c6bf-11e8-9077-d943d0aff8bd.png)
