### ISSUE TITLE
Allow users to update Seo title (Slug) 

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#229]
The system automatically generates them but then allow user to update. For all entity types:

- Category
- Brand
- Product
- Page
- Vendor
- NewsCategory
- NewsItem

**Comment by odemeulder** [comment]
Hi, I would love to help with this. Do you intend to SEO title to be the text inside the html title tag? Or the part of the URL? Or both?

**Comment by thiennn** [comment]
I think just the part of the URL is ok. Thanks

**Comment by odemeulder** [comment]
Are you sure? Having run an eCommerce site myself, the ability to change the title is a big asset. 
On the other hand, the url is not that important.

**Comment by thiennn** [comment]
I am not a SEO expert. Please correct me if I am wrong. I think the content in the html title tag should be the name of the content, for example product name, category name.

**Comment by odemeulder** [comment]
That is the most obvious way, but an experienced SEO practitioner may want to do some more fine tuning of the title tag. The title tag is one of many factors that determine the ranking of the page, but it is a very important one. But it's your project, so I'll leave the final decision up to you.

**Comment by thiennn** [comment]
If it is import than, I am fine.  Actually I think I have added some properties for SEO: MetaTitle, MetaKeywords and MetaDescription. Your support is appreciated

**Comment by thiennn** [comment]
Hi @odemeulder, any update on this?
