### ISSUE TITLE
ArgumentOutOfRangeException: The UTC time represented when the offset is applied must be between year 0 and 10,000.

### ISSUE THREAD

**Issue by diggerton** [simplcommerce/SimplCommerce#23]
First run exception located in: 

`SimplCommerce.Web.Extensions.WorkContext.SetUserGuidCookies(Guid userGuid) in WorkContext.cs`

The code that appears to be triggering this exception is:

    private void SetUserGuidCookies(Guid userGuid)
    {
        _httpContext.Response.Cookies.Append(UserGuidCookiesName, _currentUser.UserGuid.ToString(), new CookieOptions
        {
                Expires = DateTime.MaxValue
                //Expires = DateTime.UtcNow.AddDays(30)
            });
        }
    }`

To remedy this issue, I used the commented line instead of the default.

**Comment by thiennn** [comment]
Thank you
