### ISSUE TITLE
AuthorizeAsync asp.net core 2.0

### ISSUE THREAD

**Issue by balasratran** [simplcommerce/SimplCommerce#233]
Asp.net Core 1:
```c#
Task<bool> AuthorizeAsync(ClaimsPrincipal user, object resource, IEnumerable<IAuthorizationRequirement> requirements);
```

Asp.net Core 2:
```c#
Task<AuthorizationResult> AuthorizeAsync(this IAuthorizationService service, ClaimsPrincipal user, object resource, IAuthorizationRequirement requirement);
```

In asp.net core 1 returns true when there is permissions, while asp.net 2 returns AuthorizationResult. How come in asp.net core 2 returns the bool value? Please guide me.

**Comment by thiennn** [comment]
@balasratran 

```cs
var authorizationResult = await AuthorizeAsync(this IAuthorizationService service, ClaimsPrincipal user, object resource, IAuthorizationRequirement requirement);

bool success = authorizationResult.Succeed 
```
I might not remember exactly the property name, but you can find it using intellisense

**Comment by balasratran** [comment]
Hi @thiennn 
I tried it but the application always returns flase. You see 2 help below picture.

![2-1486357521628](https://user-images.githubusercontent.com/26430195/28569180-006b91ae-7163-11e7-9fb2-37274a980168.jpeg)
List of permissions on Claims
![error1](https://user-images.githubusercontent.com/26430195/28569181-020d9d0e-7163-11e7-876b-11907a2208d7.jpeg)

**Comment by thiennn** [comment]
Then you should check the result.Failure property

**Comment by balasratran** [comment]
@thiennn 
![anh-gai-xinh-16](https://user-images.githubusercontent.com/26430195/28573676-9599face-7175-11e7-9705-06248c6d31e4.jpg)
Did you see any wrong place?

**Comment by thiennn** [comment]
It's very hard to determine without source code, may be the permission or claim required is missing

**Comment by balasratran** [comment]
I fixed this by adding `AddAuthentication()` to Startup. I accidentally deleted it when updating dotnet 2.0.
