### ISSUE TITLE
Customer (user) groups

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#236]
CRUD customer groups
Add/Remove users from group

**Comment by KartikkShetty** [comment]
Can i take this up?

**Comment by thiennn** [comment]
In the module Core/Modules, create a class CustomerGroup.cs which inherit EntityBase and has some basic properties like Name and Description. Another class is UserCustomerGroup to link User and CustomerGroup. Similar to User and Role

- A screen to list, create, edit and delete customer group
- On the screen user create/edit user, show the list of CustomerGroup and allow selected non or many
