### ISSUE TITLE
 Error running product detail link

### ISSUE THREAD

**Issue by balasratran** [simplcommerce/SimplCommerce#237]
I open the browser and delete the cache, then run the product details link as domain.com/iphone-6s-16gb, the application fails.
```c#
An unhandled exception occurred while processing the request.
InvalidOperationException: A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.
```

![2-1486357521628](https://user-images.githubusercontent.com/26430195/28755496-8ee14056-7586-11e7-9bbd-df573dabde51.jpeg)

Please guide me how to fix it. Thank you

**Comment by thiennn** [comment]
The reason I am thinking about is that MediatR handles notification in parallel. https://github.com/jbogard/MediatR/blob/master/src/MediatR/Mediator.cs. To fix this issue, we have to create a class extend Mediator and override the PublishCore method to be something like

```cs
protected virtual Task PublishCore(IEnumerable<Task> allHandlers)
        {
            foreach(var handler in allHandlers) {
                    await handler;
            }
        }
```
