### ISSUE TITLE
 Call and use Culture.cs in the Core module?

### ISSUE THREAD

**Issue by balasratran** [simplcommerce/SimplCommerce#243]
Hi @thiennn 
Can I ask how can Core module call and use Model Culture.cs in Localization module? Please give me solution.

**Comment by thiennn** [comment]
Why do you need Culture class in Core?

**Comment by balasratran** [comment]
I need to get the Culture data in the Core to be multilingual for the content. What solution do you have for obtaining the Culture data in Core? Please guide yourself.

**Comment by thiennn** [comment]
You might need to duplicate them or move them to Core :)

**Comment by balasratran** [comment]
Yes, I switched to core module. Thanks
