### ISSUE TITLE
Register button generates IndexOutOfRangeException

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#246]
An unhandled exception occurred while processing the request.

IndexOutOfRangeException: Index was outside the bounds of the array.
System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)

Exception: is not a valid value for Int32.
System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)

InvalidOperationException: Failed to convert '' to type 'System.Int32'.
Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, string value)

DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Configuration.IConfiguration)' on type 'EmailSender'. ---> Failed to convert '' to type 'System.Int32'. (See inner exception for details.)
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = EmailSender (ReflectionActivator), Services = [SimplCommerce.Module.Core.Services.IEmailSender], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Configuration.IConfiguration)' on type 'EmailSender'. ---> Failed to convert '' to type 'System.Int32'. (See inner exception for details.) (See inner exception for details.)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)

Stack Query Cookies Headers
IndexOutOfRangeException: Index was outside the bounds of the array.
System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)

Show raw exception details
Exception: is not a valid value for Int32.
System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
System.ComponentModel.TypeConverter.ConvertFromInvariantString(string text)
Microsoft.Extensions.Configuration.ConfigurationBinder.TryConvertValue(Type type, string value, out object result, out Exception error)

Show raw exception details
InvalidOperationException: Failed to convert '' to type 'System.Int32'.
Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, string value)
Microsoft.Extensions.Configuration.ConfigurationBinder.GetValue<T>(IConfiguration configuration, string key, T defaultValue)
Microsoft.Extensions.Configuration.ConfigurationBinder.GetValue<T>(IConfiguration configuration, string key)
SimplCommerce.Module.EmailSenderSmtp.EmailSender..ctor(IConfiguration config) in EmailSender.cs
+
            _emailConfig.SmtpPort = config.GetValue<int>("SmtpPort");
lambda_method(Closure , Object[] )
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

Show raw exception details
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Configuration.IConfiguration)' on type 'EmailSender'. ---> Failed to convert '' to type 'System.Int32'. (See inner exception for details.)
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)

Show raw exception details
DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = EmailSender (ReflectionActivator), Services = [SimplCommerce.Module.Core.Services.IEmailSender], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Microsoft.Extensions.Configuration.IConfiguration)' on type 'EmailSender'. ---> Failed to convert '' to type 'System.Int32'. (See inner exception for details.) (See inner exception for details.)
Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.InstanceLookup.Execute()
Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable<Parameter> parameters)
Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable<Parameter> parameters, out object instance)
Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable<Parameter> parameters)
Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
lambda_method(Closure , IServiceProvider , Object[] )
Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider+<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider+<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController0(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware+<Invoke>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by MaherJendoubi** [comment]
InvalidOperationException: Failed to convert '' to type 'System.Int32'.
Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, string value)
Microsoft.Extensions.Configuration.ConfigurationBinder.GetValue<T>(IConfiguration configuration, string key, T defaultValue)
Microsoft.Extensions.Configuration.ConfigurationBinder.GetValue<T>(IConfiguration configuration, string key)
SimplCommerce.Module.EmailSenderSmtp.EmailSender..ctor(IConfiguration config) in EmailSender.cs
+ Line 19            _emailConfig.SmtpPort = config.GetValue<int>("SmtpPort");
lambda_method(Closure , Object[] )
Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

**Comment by thiennn** [comment]
You should configure Smtp server or disable sending email

**Comment by MaherJendoubi** [comment]
Thank you @thiennn
