### ISSUE TITLE
Switch from MVC to .NET Core 2.0 Razor Pages

### ISSUE THREAD

**Issue by Xeevis** [simplcommerce/SimplCommerce#247]
I am wondering whether it would be feasible for SimplCommerce to make a switch to .NET Core 2.0 Razor pages?

https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/

**Comment by MaherJendoubi** [comment]
@Xeevis I like your idea

**Comment by thiennn** [comment]
I don't see any reason to switch to Razor pages. We have a lot of important feature need to implement. And of course, from now on we might use razor pages for simple pages.

**Comment by YuriiPovkh** [comment]
No. Please.
