### ISSUE TITLE
"Execute src/Database/StaticData_Postgres.sql on the created database to insert seed data"

### ISSUE THREAD

**Issue by aaaaeinai** [simplcommerce/SimplCommerce#248]
I don't understand this.
I'm new to postgress and .NET core.

**Comment by thiennn** [comment]
For PostgreSQL you can use a Management Tool like pgAdmin to execute sql scripts

**Comment by aaaaeinai** [comment]
What I did: (Manual)

> Create a database in PostgreSQL

```bash
$ psql -d postgres
```

> Update the connection string in appsettings.json in SimplCommerce.WebHost

```json
...
 "ConnectionStrings": {
    "DefaultConnection": "Username=mac_user; password=123; host=localhost; port=5432; database=postgres"
  },
...
```

> Run file "sudo ./simpl-build.sh"

```bash
SimplCommerce$ sudo ./simpl-build.sh
```

> Execute src/Database/StaticData_Postgres.sql on the created database to insert seed data

```bash
$ psql -U mac_user -h localhost -d postgres -f "src/Database/StaticData_Postgres.sql"
```

> In the terminal, navigate to the "src/SimplCommerce.WebHost" type "dotnet run" and hit "Enter"

```bash
SimplCommerce$ cd src/SimplCommerce.WebHost && dotnet run
```

The rest aren't terminal.

**Comment by thiennn** [comment]
@aaaaeinai What you got after run "dotnet run"? and what you mean by "The rest aren't terminal."
