### ISSUE TITLE
Migrate database issue

### ISSUE THREAD

**Issue by sonmt23** [simplcommerce/SimplCommerce#253]
Hi A.Thiện,
Khi em gõ Update-Database để migrate model với database của mình thì báo lỗi, em đã cấu hình đúng connection string, đã tạo database trên MSSQL. anh xem giúp em, thanks anh.
Dưới đây là stacktrace
> PM> Update-Database
> System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'User.UserAddresses' of type 'IList<UserAddress>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
>    at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.Validate()
>    at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Validate()
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
>    at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>    at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
>    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
>    at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
>    at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
>    at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
>    at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
>    at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
> Unable to determine the relationship represented by navigation property 'User.UserAddresses' of type 'IList<UserAddress>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.
> PM>

**Comment by thiennn** [comment]
It's seem that modules are not being copied to the WebHost, Please re-build the solution again, or run "copy-modules" group task. See https://github.com/simplcommerce/SimplCommerce/wiki/Development-tips for more details

**Comment by sonmt23** [comment]
Oh, maybe because the solution on my side now cannot restore Bower and npn packages, it's throwing:
> PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
> "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\Bower.cmd" install --force-latest
> 
> bower                            retry Request to https://bower.herokuapp.com/packages/angular failed with ETIMEDOUT, retrying in 1.4s ....

Therefore, the gulpfile.js cannot be loaded to run copy-modules.

Cảm ơn anh thiện, để em xem thêm lỗi này.

**Comment by sonmt23** [comment]
Hi A.Thiện, Your SimplCommerce solution already works very well. I created new one similar SimplCommerce.
I have an issue with custom route in my project
> public static IApplicationBuilder UseCustomizedMvc(this IApplicationBuilder app)
>         {
>             app.UseMvc(routes =>
>             {
>                 routes.Routes.Add(new UrlSlugRoute(routes.DefaultHandler));
> 
>                 routes.MapRoute(
>                     "default",
>                     "{controller=Home}/{action=Index}/{id?}");
>             });
>             return app;
>         }
The custom route have added on above with controller/action handle of SimplCommerce.Module.Core module in UrlSlugRoute,
but when the Project startup, it throws exception:

> InvalidOperationException: The view 'Index' was not found. The following locations were searched:
>  /Views/Home/Index.en-US.cshtml
>  /Views/Home/Index.en.cshtml
>  /Views/Home/Index.cshtml
>  /Views/Shared/Index.en-US.cshtml
>  /Views/Shared/Index.en.cshtml
>  /Views/Shared/Index.cshtml
> Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable<string> originalLocations)
> Microsoft.AspNetCore.Mvc.ViewResult+<ExecuteResultAsync>d__26.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeResultAsync>d__19.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResultFilterAsync>d__24.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
> 

Could you take a look about this? Thank you so much!

**Comment by thiennn** [comment]
You will need a custom view expander. For example https://github.com/simplcommerce/SimplCommerce/blob/master/src/SimplCommerce.Infrastructure/Web/ModuleViewLocationExpander.cs

**Comment by sonmt23** [comment]
That's sweet!
