### ISSUE TITLE
Authentication not working?

### ISSUE THREAD

**Issue by sweeperq** [simplcommerce/SimplCommerce#263]
Just cloned from the master repo and followed the instructions for getting it set up in Visual Studio. When I attempt to go to the Admin dashboard it kicks me to the login screen, as expected. However, upon logging in it kicks me to the home page and never sets the user in the web context.

I went into the debugger and set a breakpoint in the Login action. _signInManager.PasswordSignInAsync is returning **Successful**, but unfortunately the user is not being set. Thoughts?

**Comment by thiennn** [comment]
Please check whether the cookies .AspNetCore.Identity.Application has been written in the browser

**Comment by sweeperq** [comment]
I restarted VS2017 and cleared my cookies then it worked.
