### ISSUE TITLE
PostgreSQL and MySQL CustomerGroup Unique Constraint Violation Exception Handling

### ISSUE THREAD

**Issue by wwrighter** [simplcommerce/SimplCommerce#265]
Current implementation of the unique constraint violation exception handling contained in the CustomerGroupApi does not account for PostgreSQL nor MySQL exceptions.  

https://www.postgresql.org/docs/9.4/static/errcodes-appendix.html
https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html

**Comment by thiennn** [comment]
I don't think it's a good approach. We should check it in the code. Shouldn't depend to much on the database

**Comment by thiennn** [comment]
#345 we prefer to keep thing simple.
