### ISSUE TITLE
Angular 4 table choices

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#271]
We are considering migrate to Angular 4 for back-office. There are some choices for data table
1. https://github.com/valor-software/ng2-table. The UI look good but seem not up to date
2. https://github.com/swimlane/ngx-datatable. The most popular but, haven't figure out how to filter by multiple columns
3. https://github.com/akveo/ng2-smart-table. Not official smart table for angular 2
4. https://github.com/andyperlitch/ngx-super-table. Look promising

**Comment by sau-lanvy** [comment]
How about the data-table from Angular Material as https://material.angular.io/components/table/overview?

**Comment by thiennn** [comment]
looking nice. Thank @sau-lanvy
