### ISSUE TITLE
names of Brands and Categories do not allow foreign characters

### ISSUE THREAD

**Issue by ChrisSun1212** [simplcommerce/SimplCommerce#275]
For example, if we name a brand with only Chinese characters, then the SeoTitle of the brand would be an empty string.  This would cause a problem on routing, and the home page is set to the search result of this brand unintentionally.  I guess the right way to do is to name everything in English and have the localizer translate everything into a different language. However, what if the brand name doesn't have an English translation? My suggestion is to allow the user to specify the SeoTitle themselves instead of forcing them to use the default setting. Just my two cents.

**Comment by Joy2BeWith** [comment]
Any eta on gateway/credit card setup?

**Comment by thiennn** [comment]
This is the aware issue #229 and here #155

**Comment by thiennn** [comment]
@Joy2BeWith, I am sorry, there is not eta. Day by day, I have to work for living :)

**Comment by Joy2BeWith** [comment]
No worries - the work u done so far is fricken awesome!!!

**Comment by thiennn** [comment]
#278
