### ISSUE TITLE
GetCurrentUser in Workcontext class

### ISSUE THREAD

**Issue by dovandap** [simplcommerce/SimplCommerce#276]
Hi Thiennn,

I have problem about the WorkContext.
Step 1: I login with account(test1@gmail.com) on site --> success: 
Step 2: Logout --> success
Step 3: Login again with other account(test2@gmail.com) --> success --> but GetCurrentUser in Workcontext class alway is test1@gmail.com.

Pls help me. 

Thanks,

Dap.DV

**Comment by thiennn** [comment]
The current code on master works fine. You are in another branch or it's your own code?

**Comment by dovandap** [comment]
:(. I get code on master branch. And using original code. 
- I create own module and implement IWorkcontex class. 
- Call function GetCurrentUser then show current prev.

**Comment by thiennn** [comment]
Just curious, why you need to implement IWorkContext? instead of using the existing one

**Comment by dovandap** [comment]
:). I create module payment to show all wallet's. each other user have purses. 
- user 1: 3 purses
- user 2:  5 purses
--> So when i login other user, then currently User in(WorkContext ) not update.

**Comment by thiennn** [comment]
Could you share the source code so that I can take look and investigate

**Comment by dovandap** [comment]
I using : 
private readonly IWorkContext _workContext;
public AccountController(
            UserManager<User> userManager,
            SignInManager<User> signInManager,
            IEmailSender emailSender,
            ISmsSender smsSender,
            ILoggerFactory loggerFactory, IWorkContext workContext, IClientService clientService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSender = emailSender;
            _smsSender = smsSender;
            _workContext = workContext;
            _clientService = clientService;
            _logger = loggerFactory.CreateLogger<AccountController>();
        }
public async Task<IActionResult> ExternalInfo()
        {
            var u = await _workContext.GetCurrentUser(); --> u alway the user prev login.
            //var u = await _userManager.GetUserAsync(User);
            if (u == null)
            {
                return RedirectToAction(nameof(AccountController.Login), "Account");
            }
            var p = await _clientService.GetPurseList(u.Id);
            var i = new ExternalViewModel.AccInfo();
            i.User = u;
            i.Purses = p;

            return View(i);
        }

**Comment by thiennn** [comment]
Below are a couple things you can do
1. Please make sure that you didn't register the WorkingContext as Singleton
2. Debug through the code to see how it run

**Comment by dovandap** [comment]
Yes, i working with register iworkcontext AddTransient.

Thanks for help,
