### ISSUE TITLE
Problem with migration

### ISSUE THREAD

**Issue by yessow** [simplcommerce/SimplCommerce#279]
Hello 

I have been using Simplcommerce over Core 1.1 locally with PostgreSQL and visual studio 2017. Everything is working fine. 
But once I have migrated to new project with Core 2.0 I am not able to create all the tables on the new database. I have changed UseSqlServer to UseNpgsql in both files program.cs and ServiceCollectionExtensions.cs. I also added Npgsql.EntityFrameworkCore.PostgreSQL in SimplCommerce.WebHost.csproj and I have cleared the folder Migrations.
Therefore The only tables I have been able to create with dotnet ef migrations initial are The Core Tables and Localization (see file below)
[initial.txt](https://github.com/simplcommerce/SimplCommerce/files/1360897/initial.txt)

Is there a workaround to fix this.

Thank you

**Comment by thiennn** [comment]
There must be some thing wrong with loading module. Please checkout the doc here https://github.com/simplcommerce/SimplCommerce/wiki/Development-tips and then checking the code about module loader. There are some minor changes between 1.1 and 2.0
