### ISSUE TITLE
What design pattern you are following

### ISSUE THREAD

**Issue by amitsaini12345** [simplcommerce/SimplCommerce#282]
It is very nice and good project. 

Sir I want to contribute in this project. Please help me about these questions for better implementations.

1. What design patterns are you following. How dependency injection is implemented in this project.
2. **I don't understand there are two folders SimplCommerce.WebHost and SimplCommerce.Infrastructure** Why? Why there are sperate folders of bin each in modules folders.
3. **Why you are not using WebApi to perform backend operations like insert product, display product and implement security in web service and perform  etc.** so that we can consume web api methods on andriod apps ,ios apps etc. later on

 I think using webApi is better for good eneterprise app.

**Comment by thiennn** [comment]
1. We use Autofac, auto register by scanning assemblies
2. As their names. WebHost is the hosting project. You can think the  Infrastructure contains utilities, helpers that not related to the business domain. Separating bin folder for each module so that we can add/remove modules easier.
3. The backend is actually the SPA, AngularJS + WebAPI

**Comment by Joy2BeWith** [comment]
Do we when shopping cart is ready for prime time 😇

**Comment by amitsaini12345** [comment]
Love this project and contribute in developing this project.   Assign we task if you require 
Please add step  by step youtube tutorials about this project to learn

**Comment by amitsaini12345** [comment]
It will be great products  like cms Magento.. Build in php. 

I believe that it will fail Magento in terms of performance.  
Please always be sure about performance while developing this product. 

One more thing great i salute you sir that you made it open source.  

Please let me know if any kind of task contributions. Always ready to be for task contributions
