### ISSUE TITLE
StaticData defaults to Vietnam and Vietnamese?? How to change?

### ISSUE THREAD

**Issue by drewid** [simplcommerce/SimplCommerce#284]
Great platform!

The StaticData,sql seems defaults to Vietnam and Vietnamese?? How to change?  Would like English and US data.  Does that exist somewhere?  There is no US state data in Core_StateOrProvince table and don't want to reinvent the wheel if not necessary.

Thanks!

**Comment by thiennn** [comment]
Thanks, currently we don't have the English and US data. It would be great if you can help on this

**Comment by thiennn** [comment]
Added by https://github.com/simplcommerce/SimplCommerce/pull/310/commits/38b461bcaeb97eb9c089549036630190a13d8778
