### ISSUE TITLE
Add new module - Azure blob media storage 

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#289]

**Comment by ricardodemauro** [comment]
Hello,

Can you give more details?

Want to store the media (images and videos) in Azure blob storage?

What about reading? Should be a controller to encapsulate the communication or a direct link it's enought?

I'll try to implement this if no one object.

**Comment by thiennn** [comment]
Hi,

You only need to implement IMediaService interface. You can take a  look at the AmazonS3 as a reference https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.StorageAmazonS3/S3MediaService.cs.

Thanks

**Comment by ricardodemauro** [comment]
I just submit a pull request.

Hope you find useful.
