### ISSUE TITLE
Question about address structures?

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#308]
In Vietnam, our address structure is: Country --> Province or City --> District. How about your country and others?

**Comment by MaherJendoubi** [comment]
A French address is structured as follows:

Madame Marie Delaroche
RESIDENCE DES FLEURS
8 ALLEE DES LILAS
75014 PARIS    

- 5 digit post code. The first two digits stand for the district (departement) and the following three for the postage delivery point. 

- Excluding the name, the address should be written in capital letters.  

-  Additional information (residence, storey, building, etc.) are often used.    

- A maximum of 38 characters or spaces per line.   

-  Capital letters are recommended for the last three lines of the address (four with the country name).
