### ISSUE TITLE
[info] not an issue!

### ISSUE THREAD

**Issue by iyilm4z** [simplcommerce/SimplCommerce#315]
hi all, as i understood, in gulpfile.js file we do "select(grab) or delete(remove)" actions
with the help of some libraries.
-clean:js task uses 'rimraf' to delete
-clean:lib task uses 'del' to delete
-clean-module task uses 'gulp-clean' to delete
-loadModules function uses 'glob' to select
-copy-modules task uses 'gulp.src' to select
i do want to know why we didn't use only one library to do our select or delete actions.
gulp's src is not enought for loadModules function? or rimraf is not enought for clean:lib, clean-module tasks?

**Comment by thiennn** [comment]
Thanks, I didn't notice that. Actually this the current gulpfile.js is merged from 2 separated file and which were written by 2 different people. 

It would be great if you can help simplify it.

**Comment by iyilm4z** [comment]
thanks for answering! i will try to give a hand!

**Comment by Joy2BeWith** [comment]
When will this project be ready for commercial use???

**Comment by thiennn** [comment]
@Joy2BeWith The first public release 1.0 is scheduled to Q1, 2018.
