### ISSUE TITLE
Master branch has critical issues

### ISSUE THREAD

**Issue by IevgenZub** [simplcommerce/SimplCommerce#321]
Hi! I've noted that master branch has critical bugs related to recent changes e.g. incorrect link to add-to-cart.js and it's impossible to proceed with order. At the same time demo version is working and it's not deployed from master. 

Just wanetd to clarify which branch is stable and can be safely merged into my fork repo?

**Comment by thiennn** [comment]
We are in development mode. Master is the most stable branch. Please include the error message in details. Thanks

**Comment by thiennn** [comment]
You can now check out with COD
