### ISSUE TITLE
Can't add product variations

### ISSUE THREAD

**Issue by zhukovskyy** [simplcommerce/SimplCommerce#328]
When I try to add some product variations - new product item creates without thumbnail - should I add them manually for each new item created? 
And why my new item with options does not have this "Has Option" flag?
How can I reproduce your example with color options for IPhone item? Or I should fix this issue in code?

**Comment by thiennn** [comment]
Hi,

I will take a look into that. But normally, Product variations don't need a thumbnail. Only the main products are visible to customers. 

Only the main products have "Has Option" value

**Comment by zhukovskyy** [comment]
Product variations need thumbnails because in the cart (when user make an order) user don't see the image.

**Comment by thiennn** [comment]
fixed
