### ISSUE TITLE
remodeling product variation

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#33]
I see there 2 ways to model the products with options like a T-Shirt with many colors and sizes:

1. Product and product variation, 1 product can have 0 or n variations. Most of the properties will be on Product, there are just some on variation: like sku, price, picture, maybe stock. Shoptify seems model this way, and as we currently do.

2. Flatten, everything is product like Magento

I'm struggling which one is the best

**Comment by thiennn** [comment]
We go with option 2, everything is product

**Comment by sunnygb** [comment]
Can i ask u why u choose the second option and migrated from the first one?
I know its been an old thread.. but since im new to ecommerce development.. so bear with me please...

**Comment by thiennn** [comment]
With the first option, it is more complicated for modules that depend on the product, like shopping cart, order, inventory, etc. Because a product can be is product (no variation) or a variation.

With the flatten approach, every thing is products, it's simpler. The downside is that it is required a little more storage as the product information is duplicated into every variations.

**Comment by sunnygb** [comment]
Thanks.. its now making sense
