### ISSUE TITLE
Updated several parts of the program

### ISSUE THREAD

**Issue by jamalkaksouri** [simplcommerce/SimplCommerce#335]
1- CRUD for Countries and  State or Province.
2- Add new culture in manage translation.
3- Change status of the reviews and can be removed.
4- In the SpaceBar Widget can be choose icon from computer and upload.
5- In the Shipping - Table Rate Configuration when click Save button recieve error (Could not html widget)
6- Payment providers not showing!
7- Can replay comment's of customer by admin

**Comment by thiennn** [comment]
Thank @jamalkaksouri 
For the item number 5: Could you please capture the error message return by the server in Chrome Developer Tool, Network tab.
About the item number 6: Are you in the latest code of master branch. And please check whether they are showed in the Admin --> System--> Payment Providers.

**Comment by jamalkaksouri** [comment]
For the item number 5: show error : http://localhost:49209/api/shippings/tablerate/setting 404 (Not Found)
item number 6 : Not Showing!!
and in the latest code of master branch how to set user pass or port to gmail account?

**Comment by thiennn** [comment]
I cannot reproduce the issue 5, 6 on my local, it also works fine on the http://demo.simplcommerce.com  I think you might need to re-create your database.

About the email setting. Sorry about that. The current workaround is that you can set them directly in the database, table Core_AppSetting

**Comment by thiennn** [comment]
#475
