### ISSUE TITLE
Add Setup module

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#337]
- A middleware to check whether the database has been installed
- A screen for user to input some info such as database connection string 
- Execute the sql script to create database and table
- Execute the sql script to insert seed data

**Comment by etam168** [comment]
How would you like to help? I can generate the scripts for SQL Server for you in the next few days if you still need help. Can do the same for PostgreSQL also.

**Comment by thiennn** [comment]
Hi @etam168 , Generating sql script is very simple, just run one command "Script-Migration". It would be best if you can create entire the module as described above. Thanks

**Comment by etam168** [comment]
Sorry, I was busy last few days. How about using a Powershell script with UI to automate those tasks?

**Comment by thiennn** [comment]
For this ticket we assume the sql scripts are ready

**Comment by hishamco** [comment]
@thiennn are you working on this? or you need some help

**Comment by thiennn** [comment]
I am thinking about not implement this feature. SimplCommerce supports many databases MS SQL, PostgreSQL, MySQL, SQLite. However, to change database, we have to add the corresponding nuget package, Update the code, UseSqlServer or UseMySql,...

On each release we will include 2 versions of self contained app: 1 for mac, 1 for windows and using SQLite, for users to try out easier. All they need to do is just extract the zip file and run the app.

**Comment by hishamco** [comment]
In `OrchardCode` I see all of the providers are supported out-the-box, so the user is enable to the user can pick the one he prefers without add a nuget packages

**Comment by hishamco** [comment]
Yep it uses `YesSQL` which I contribute to it too 😄, but If you look into the database access all the providers have been registered

**Comment by thiennn** [comment]
I quite sure that in order to use other entity framework core providers than MS SQL Server, we have to pull additional nuget package

**Comment by hishamco** [comment]
Exactlly

**Comment by thiennn** [comment]
We are not going to implement this feature as https://github.com/simplcommerce/SimplCommerce/issues/337#issuecomment-420170064
