### ISSUE TITLE
Invoices

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#339]

**Comment by jducobu** [comment]
http://fizzylogic.nl/2017/08/03/how-to-generate-pdf-documents-in-asp-net-core/

**Comment by thiennn** [comment]
Pdf generating need a wkhtmltopdf to work. Download the suitable according to your OS 
at https://github.com/rdvojmoc/DinkToPdf/tree/master/v0.12.4

In development: put it in to the src\SimplCommerce.WebHost. In servers put in the root folder

Note: It not working with IIS Express, still don't know why. So don't run under IIS Express

**Comment by horseyhorsey** [comment]
I have this running in IIS Express. I think until `.net core 3.0` you need a `CurrentDirectoryHelper`.

I combined this with https://github.com/rdvojmoc/DinkToPdf/issues/5#issuecomment-321183899

`SimplCommerce.Module.DinkToPdf.ModuleInit`

        // TODO: Remove this when/if move to dotnet 3.0
        currentdirectoryhelpers.setcurrentdirectory();
        var context = new CustomAssemblyLoadContext();
        context.loadunmanagedlibrary(path.combine(directory.getcurrentdirectory(), "libwkhtmltox.dll"));
