### ISSUE TITLE
One payment gateway in Vietnam

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#341]

**Comment by richardrcruzc** [comment]
I think I can help with this new module, do you have any particular payment gateway in mind ?

**Comment by thiennn** [comment]
@richardrcruzc you can choose any gateway you like. Sorry for the lateness btw.

**Comment by hishamco** [comment]
After reading my comment [here](https://github.com/simplcommerce/SimplCommerce/issues/403#issuecomment-421574977) we can enable / disable the modules that act as transient by its nature

**Comment by thiennn** [comment]
Added momo payment #723
