### ISSUE TITLE
 [Edit Product] ->StockQuantity 

### ISSUE THREAD

**Issue by PeterJD** [simplcommerce/SimplCommerce#342]
Only had a quick look in demo Admin
[Edit Product], unable to find where I can increase stockQuantity level

**Comment by thiennn** [comment]
It should be in another screen stock management.  But we haven't implemented yet

**Comment by Joy2BeWith** [comment]
Are we close to being ready to fully use?

**Comment by thiennn** [comment]
The beta release is scheduled to 28-Feb-2018

**Comment by thiennn** [comment]
Added stock management https://github.com/simplcommerce/SimplCommerce/commit/bb7af295c7ce1bb007a300880f606c85c58d51b9
