### ISSUE TITLE
CRUD for warehouse

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#359]
It's on Inventory module

**Comment by tdavisjr** [comment]
I see that warehouse has a reference to the Address entity. Should CRUD operations affect address is some way? If you could also help clarify why this relationship exist, that would be helpful.

**Comment by thiennn** [comment]
In the warehouse form, we also display fields of address. A warehouse always has one address and that address is only referenced by this warehouse. On create: add Address then add the Warehouse. On delete similar to district and country, if the warehouse record hasn't referenced, then delete the warehouse then delete the address,  if it has show the error message.
