### ISSUE TITLE
Split EF migrations to modules

### ISSUE THREAD

**Issue by MaklaCof** [simplcommerce/SimplCommerce#362]
Right now all migrations live in one project. (WebHost)
Is it possible to split migrations to modules? That means that if module is not included, tables would not be created.

**Comment by thiennn** [comment]
It's possible, but will be a bit more complicated and you can not deploy directly from Visual Studio to Azure. 
I don't really get your point about benefits of this splitting. Please describe more

**Comment by thiennn** [comment]
In version 2.0, The host only contains core modules. Other modules will be in the marketplace, each of these module will contain the migration for itself.

For now, you can just delete the existing migration then re-create with modules that you want to include.
