### ISSUE TITLE
Update-Database fails for AddedStockHistory migration

### ISSUE THREAD

**Issue by tdavisjr** [simplcommerce/SimplCommerce#363]
**Error:** 
```
ALTER TABLE [Catalog_Product] ALTER COLUMN [StockQuantity] int NOT NULL;
System.Data.SqlClient.SqlException (0x80131904): Cannot insert the value NULL into column 'StockQuantity', table 'SimplCommerce.dbo.Catalog_Product'; column does not allow nulls. UPDATE fails.
The statement has been terminated.
```

This issue originates from commit bb7af295 where StockQuantity type was changed from int? to int. Since the table was already populated will null data, the migration failed when it altered the column to make it not nullable.

I have resolved this by updating the AddedStockHistory migration to drop the column and add it back. I'll submit a PR for review.

**Comment by thiennn** [comment]
The workaround is to update the StockQuantity column in Catalog_Product table to 0 or some value then run Update-Database again.
It's not a problem for new created database
