### ISSUE TITLE
Use Angular 5 and typescript

### ISSUE THREAD

**Issue by jducobu** [simplcommerce/SimplCommerce#366]

**Comment by AdnanCukur** [comment]
Much rather prefer Vue, since it takes a day to learn and doesnt force us to use a full SPA backend, but every module can have its own page and its own Vue instance without any hassle.

If people wanna use plain JS to build their modules thats fine, and if they wanna use typescript that works too.

**Comment by thiennn** [comment]
not in the next 2 - 3 years, after that we might re-implement the back-office
