### ISSUE TITLE
Add Sku to product form

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#367]

**Comment by jducobu** [comment]
Multi SKU for one product ?

**Comment by jducobu** [comment]
SKU = EAN ? Because same product must have different EAN.

**Comment by thiennn** [comment]
SKU = Stock Keeping Unit. What does EAM mean?

**Comment by jducobu** [comment]
EAN = European Article Numbering.
The SKU is attributed by the shop as product reference ?

**Comment by thiennn** [comment]
SKU for internal shop owner use. Maybe we should add both

**Comment by jducobu** [comment]
Sku is already present in table data model of product table

**Comment by thiennn** [comment]
Yes, but it haven't showed in product form yet
