### ISSUE TITLE
Set default DeleteBehavior for all relationship to Restrict

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#370]
EF Core 2.0 default behavior is CASCADE. That mean all the child will be deleted when the parent is deleted. See here for more details https://docs.microsoft.com/en-us/ef/core/saving/cascade-delete

In SimplCommerce, we prefer to set this default behavior to Restrict to prevent data loss. Scenarios required Cascade need to explicitly override.

**Comment by Joy2BeWith** [comment]
U close to prime time? :-)

**Comment by jducobu** [comment]
https://stackoverflow.com/a/34777839

**Comment by thiennn** [comment]
It's done already
