### ISSUE TITLE
Reset StockQuantity for all products on demo site

### ISSUE THREAD

**Issue by tdavisjr** [simplcommerce/SimplCommerce#372]
No product is able to be added to the shopping cart perhaps due to having 0 set for it's StockQuantity. There is also no way to edit in the Admin screen.

**Comment by thiennn** [comment]
Please go to admin --> sales --> stocks. Add All Product to Warehouse (the button on the right). Then you will be able to update stock

**Comment by tdavisjr** [comment]
Ok. That works. Thank you.

Is there a better way to ask such a question? Gitter? I didn't know if this was an issue or not; but it was the only way to communicate.

**Comment by thiennn** [comment]
Either submit the issue here or gitter are fine. Btw, I going to add default stock quantity for the sample data.
