### ISSUE TITLE
Create history of discount price

### ISSUE THREAD

**Issue by jducobu** [simplcommerce/SimplCommerce#380]
Denormalize discount data in a table with 1:n relationship between product and discount

**Comment by alessalessio** [comment]
Are you talking about dbo.Catalog_Product ? Do you want to move the SpecialPrice columns into a separate table and add a foreign key to the active discount ?

**Comment by jducobu** [comment]
Exactely! Add also datefrom and dateto to the table perhaps

**Comment by thiennn** [comment]
So it duplicate of #286
