### ISSUE TITLE
Can't Get The Sign In To Work

### ISSUE THREAD

**Issue by HarleyBartles** [simplcommerce/SimplCommerce#397]
Hello.

I've forked the repo and done the DB setup and I'm completely unable to properly sign in using either the in built admin account or a newly registered account.

This returns success in AccountController.Login post method
`var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);`

This returns false immediately on next render of the Login Partial
`@if (SignInManager.IsSignedIn(User))`

Any help in what I'm missing? I'm sure it'll be something obvious I'll kick myself about once it's pointed out.

Thanks

**Comment by thiennn** [comment]
We haven't encountered this error.  If the sign in return success but out in the next request. I think there may be something wrong in the authentication cookie

**Comment by HarleyBartles** [comment]
Nevermind! Turns out clearing my cookies was all that was required. Schoolboy! Thanks for the pointer.

Thanks so much for your quick reply and help!
