### ISSUE TITLE
Dependencies' versions conflict 

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#402]
When testing the new module StorageAzureBlob we encounter the exception "FileNotFoundException: Could not load file or assembly 'Microsoft.WindowsAzure.Storage, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified." After some investigation we discovered that the Microsoft.WindowsAzure.Storage, Version=9.0.0.0 cannot be load because the Microsoft.WindowsAzure.Storage, Version=8.1.4 had been loaded already. 

It had been loaded because the "Microsoft.AspNetCore.All/2.0.3" --> Microsoft.AspNetCore.DataProtection.AzureStorage/2.0.1 --> Microsoft.WindowsAzure.Storage/8.1.4

Manually copy the file 'Microsoft.WindowsAzure.Storage, Version=9.0.0.0 to the WebHost/bin folder. It works. However we don't want the host know about dependencies of modules because we want to build plug/play at runtime (the marketplace of modules) in the next phase.

**Comment by thiennn** [comment]
@tdavisjr This is the issue you encountered

**Comment by tdavisjr** [comment]
Wow. I would have never discovered this. Good find. ASP.Net team made a mistake with including all of these dependencies in the .All meta-package. That said, t[hey are fixing it in v2.1](https://github.com/aspnet/Announcements/issues/287). 

Would it be wise to remove that meta-package now and just reference the packages required for the app to run?

**Comment by thiennn** [comment]
It now has a clear error message if there is a version conflicts
