### ISSUE TITLE
Services might be registered twice

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#403]
Currently, to be convention all the services (class end with 'Service') are automatically registered as Transient . But sometimes, in modules there are the need to register some services with other lifetime such as Singleton for example AzureBlobStorageService, S3StorageService.

**Comment by tdavisjr** [comment]
I've been wondering. When multiple modules have classes that implement the same interface, like in this case, and registered in the DI container, how will the application know what implementation to use?

**Comment by thiennn** [comment]
@tdavisjr normally, There is only 1 implementation is included. For example IStorageService, there are 3 implementations: LocalStorageService, AzureBlobStorageService, S3StorageService, but we only use one per site deployment. 

If you include more than one, the system will pick one and we might not control the order. In the case you would like to have more than one implementation co-running then in the constructor add (IList<IStorageService> storageServices) then you can loop through it

**Comment by hishamco** [comment]
IMHO we dive the services into two categories:
1- Singleton
Database provider, storage services .. etc we should provide one implementation bundled with the host, if there 's a change, restart is required in this case
2- Transient
Payment gateways for instance it can be many implementation as the same time

FYI I didn't have an entire look to the project, but this what it should be done as developer point of you

**Comment by hishamco** [comment]
This is for repositories what about the others, hope you check my previous [comment](https://github.com/simplcommerce/SimplCommerce/issues/403#issuecomment-421574977)
