### ISSUE TITLE
English (UK) Language option

### ISSUE THREAD

**Issue by bassios** [simplcommerce/SimplCommerce#404]
I cannot figure out how to add a language to the system. I've added the translations to the database and added a culture option, and added an option to the select language dropdown. The doc page for adding a language is absolutely no help as it only links off to other pages with no instructions or hints on how to use the resources from the other pages.

I'm trying to add English UK so I can have the store display prices in £, instead of $. Literally all I need is to change that.

**Comment by thiennn** [comment]
For your case. I  think you should make a small change at https://github.com/simplcommerce/SimplCommerce/blob/bb5ef8da992fb678f8593a254d1f0f96421f7bf6/src/SimplCommerce.WebHost/Extensions/ApplicationBuilderExtensions.cs#L70

Add 'en-UK' for supportedCultures and set 'en-UK' as DefaultRequestCulture. You can also remove the rest.

Please let me know whether it works for you

**Comment by bassios** [comment]
Brilliant! Thanks so much, I'd totally missed that.
