### ISSUE TITLE
Diffrence between Source and demo

### ISSUE THREAD

**Issue by reader-man** [simplcommerce/SimplCommerce#41]
Hi,
Thanks on the nice project, its niceness comes from the use of .Net core.

but i downloaded the source, and run it, and here is a the result:

![source run](https://cloud.githubusercontent.com/assets/12806275/16656156/47a0c614-4466-11e6-9b34-e64401c767c7.jpg)

but the demo looks like this:
![demo](https://cloud.githubusercontent.com/assets/12806275/16656155/479bc3e4-4466-11e6-9e74-02f2baeedbed.jpg)

too much difference?

Regards.

**Comment by thiennn** [comment]
Hi @reader-man 

I think the css files haven't been loaded for some reasons. which environment has you run: development or production or testing ?

Btw, on the demo, there are sample data. You can click on the button  "Do it" on the "Sample data" block, it will create some sample product for you.
