### ISSUE TITLE
licence question

### ISSUE THREAD

**Issue by diggschauhan** [simplcommerce/SimplCommerce#412]
Hey this may sound like totally stupid question. i read about apache 2.0 but still needed to clarify. what are the terms of using this for commercial purpose? anything credits or anything we have to maintain when producing this as commercial website?

**Comment by thiennn** [comment]
You can use SimplCommerce for commercial purpose. The condition is keep the file https://github.com/simplcommerce/SimplCommerce/blob/master/License.txt in your distributed software

**Comment by Joy2BeWith** [comment]
Is it ready to use now? I notice when you set the category display positions it doesn’t stick and there’s no way to enter quantities 

But overall GREAT JOB!!! You’re a fricken rock star developer Thien!!!!!

**Comment by diggschauhan** [comment]
@thiennn  thanks a lot buddy for replying. if i am just publishing this as website, do i need to give the link to this licence somewhere on the website itself? or just including this in the page source? never used open source software hence not sure :)

**Comment by thiennn** [comment]
@diggschauhan you don't need to give a link to the licence on your website. Just don't manually delete the licence file is all we need.

**Comment by thiennn** [comment]
@Joy2BeWith the stock quantity are manage in Sales --> Stock menu

**Comment by diggschauhan** [comment]
@thiennn  thanks buddy and one final thing. if i would like to customise it just for myself do i have to publish the modified version anywhere i mean the source code?

**Comment by thiennn** [comment]
@diggschauhan no you don't need if you don't want to

**Comment by diggschauhan** [comment]
ok thanks a lot for your time :)
