### ISSUE TITLE
Payment gateway with extra fees

### ISSUE THREAD

**Issue by madking2010** [simplcommerce/SimplCommerce#413]
it would be very nice if payment module comes with payment fees.

**Comment by thiennn** [comment]
How do you think if we note the fee like the image below
![payment with fee](https://user-images.githubusercontent.com/289607/36708141-31e6b39e-1ba4-11e8-94ba-b942f85772a5.png)

In the Payment table,  we will add another columns to store this fee.
On the payment provider configuration, add a field for admin to enter the fee

**Comment by madking2010** [comment]
yes look nice . where you will calculate % in papal component before sending request ?

**Comment by Joy2BeWith** [comment]
I’m up and running, thank you Thien! I guess were waiting to be able to delete product options, etc!

Great job
