### ISSUE TITLE
Support Razor UI in class libraries

### ISSUE THREAD

**Issue by tdavisjr** [simplcommerce/SimplCommerce#422]
This is coming in the [ASP.Net Core 2.1 update](https://blogs.msdn.microsoft.com/webdev/2018/03/01/asp-net-core-2-1-razor-ui-in-class-libraries/). This feature seems to lend itself well for building modules so I'm hoping this can be added in V2.

**Comment by thiennn** [comment]
Sure. I have upgrade to 2.1-preview1 on another branch. There a some small issues. I think I can go with preview2

**Comment by afernandes** [comment]
What are the problems?
What's the branch?
Can we even try to migrate?

**Comment by thiennn** [comment]
I last time I try (2 - 3 months ago), it's didn't work. I don't remember exactly the issue. I think we should make another try

**Comment by thiennn** [comment]
There is an issue with dynamic loading when using Razor Class Library see https://github.com/thiennn/dynamicLoadingRazorLib/

**Comment by thiennn** [comment]
Please take a look at the prototype at https://github.com/thiennn/dynamicLoadingRazorLib/ if there are no concern. We will apply for SimplCommerce soon

**Comment by thiennn** [comment]
#610
