### ISSUE TITLE
Is it difficult to change it and use it for a pizza store? 

### ISSUE THREAD

**Issue by TonyWoo** [simplcommerce/SimplCommerce#425]
Hi, is it difficult to change it and use it for a pizza store? the store have multiple store. Thanks.

**Comment by thiennn** [comment]
I think it's for Pizza store. You can route orders to warehouse (store) nearest to the delivery address

**Comment by thiennn** [comment]
You can also leverage multiple vendors feature also

**Comment by TonyWoo** [comment]
Thank you @thiennn 

btw, it looks you placed all of the script for the admin in this file https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Core/Views/HomeAdmin/Index.cshtml

maybe you can use the OrchardCore resource module to do this easier.
please see below:
https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore.Modules/OrchardCore.Resources
https://channel9.msdn.com/Shows/On-NET/Sbastien-Ros-Modular-ASPNET-apps

you may can also use or borrow Orchard module concept:)
https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore/OrchardCore.Modules


Anyway, thank you for developing so good project and opend source it.

**Comment by TonyWoo** [comment]
the other feature I'd like to have is allow user to create the roles, so we need to do the authorization by the permission not the role.  For example, user can create a role and then assign some permissions to this role.
