### ISSUE TITLE
Apply theme

### ISSUE THREAD

**Issue by dovandap** [simplcommerce/SimplCommerce#429]
Dear Mr Thien,
I try custom the theme. I have issue.

How to set default custom theme. When I press refresh or open another brower, the theme rollback default site. 
- I updated item from Db: General --> Custom theme
- Created folder custom theme with structor SampleTheme.

Thanks
DapDV

**Comment by thiennn** [comment]
Hi @dovandap you don't need to update in the database. Please follow the instructions here http://docs.simplcommerce.com/en/latest/theme-development/

Please let me know whether you can resolve the issue

**Comment by dovandap** [comment]
Hi @thiennn, I created other theme same the SampleTheme folder, but running the project default SampleTheme not Mytheme. 

The first time default theme is sampletheme and then i change current theme inside the admin and theme changed to mytheme. 

But the more time and press button fresh then theme rollbank to default theme. 

pls help me. 

thanks

Dap.DV

**Comment by thiennn** [comment]
The cookies only used for preview. If the cookies not set, then system will load the theme setting in database

**Comment by dovandap** [comment]
Thanks your supported, I have changed to my theme.

Dap.DV
