### ISSUE TITLE
DELETE http://localhost:49210/api/products/2 500 (Internal Server Error)

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#43]
![image](https://cloud.githubusercontent.com/assets/1798510/17839952/2be1fba8-67f9-11e6-9434-f5891f8b3248.png)

**Comment by MaherJendoubi** [comment]
Hello,

Each time I try to delete the old products from back office I get that error.

Thanks.

**Comment by MaherJendoubi** [comment]
@thiennn I tested it and it works as a charm. Great job! Thanks a lot. You could close the issue.

**Comment by thiennn** [comment]
Thanks
