### ISSUE TITLE
Credit Card Payment 

### ISSUE THREAD

**Issue by muayyat** [simplcommerce/SimplCommerce#435]
What about a payment module for collecting credit card details on orders and displaying it to admin on dashboard.

**Comment by PeterJD** [comment]
Thats illegal

**Comment by muayyat** [comment]
What its illegality? And if it's illegal why are other open source eCommerce platforms supporting the feature. Like Nopcommerce.

**Comment by thiennn** [comment]
Directly storing the credit card information in the database is not a good idea. We are not recommended, but you can write your own module if you want to
