### ISSUE TITLE
Can't see any option to remove item from cart

### ISSUE THREAD

**Issue by itsriteshbhatt** [simplcommerce/SimplCommerce#438]
Can't see any option to remove item/s from cart

![remove item missing](https://user-images.githubusercontent.com/33856248/38022748-f86067b2-329d-11e8-9535-da90e66f006e.PNG)

**Comment by muayyat** [comment]
I've had same issue in the past and even on their demo site there's same problem. Create a custom remove from cart button and rebuild the solution.

**Comment by itsriteshbhatt** [comment]
Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
