### ISSUE TITLE
Ionic shop

### ISSUE THREAD

**Issue by jducobu** [simplcommerce/SimplCommerce#440]

**Comment by madking2010** [comment]
you can look at hear https://market.ionicframework.com/themes/ionic-2-ecommerce-ui

**Comment by jducobu** [comment]
@madking2010, To do an e-commerce via mobile, the front end must be share via rest and it's not the case today !

**Comment by madking2010** [comment]
@jducobu yes i agree must be share with everybody.the user authentication will be with firebase or identity server 4.

**Comment by thiennn** [comment]
We will support OAuth2 #444 for rest APIs. But adding Ionic app is much beyond my time and effort. 

Responsive web for mobile is what we are try to do

**Comment by jducobu** [comment]
Just expose data (category, product, price, ...) via api
