### ISSUE TITLE
Add id-ID Culture

### ISSUE THREAD

**Issue by tru3d3v** [simplcommerce/SimplCommerce#442]
Hi Guys,

I trying to add Indonesian Culture "id-ID" in _SelectLanguage.cshtml and i add new record  for tables ; Localization_Resource and Culture. But the translating is always back to default Culture en-US. 

CurrentCulture is not affected to set id-ID. 

Advice me please.

Thank You.

**Comment by thiennn** [comment]
Hi @tru3d3v ,

You also need to add to the supportedCultures in https://github.com/simplcommerce/SimplCommerce/blob/14a76a16c0f112abcc4bc17ca2a434d21e9c01c9/src/SimplCommerce.WebHost/Extensions/ApplicationBuilderExtensions.cs#L72

**Comment by tru3d3v** [comment]
Hi @thiennn 

Cool !, its work. Thank you :)
