### ISSUE TITLE
Static data is not identical between dbs

### ISSUE THREAD

**Issue by lekhasy** [simplcommerce/SimplCommerce#449]
Currently, there are a lot of diff between MSSQL and Postgres db static data file. With postgres file, i can't event run it. I haven't check for another one yet.
So, does anyone have idea to make all static data identical without having to check for every single line?

**Comment by thiennn** [comment]
I'm sorry I haven't had enough time to do this. Just ignore the Localization_Culture and Localization_Resource, there are not much line remaining.

**Comment by lekhasy** [comment]
Actually i have problem with tables that have FK is Country table.
The id of countries is not the same between static files.
Anyway, i will find a way to fix it.
