### ISSUE TITLE
Keeping a Clean Startup.cs in Asp.Net Core

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#45]
Hi @thiennn,

I find this blog post http://odetocode.com/blogs/scott/archive/2016/08/30/keeping-a-clean-startup-cs-in-asp-net-core.aspx useful to clean Startup.cs 

I tried to do the cleanup
https://gist.github.com/MaherJendoubi/70e60b900b86f90f55420e0530da4ed3
https://gist.github.com/MaherJendoubi/984c683b4c77ff8a56c26e549b9fd81b
https://gist.github.com/MaherJendoubi/8a093012a14c29ce898f18c675108b6c

but I get this issue : 
![image](https://cloud.githubusercontent.com/assets/1798510/18144508/3dcbd408-6fc7-11e6-95d2-0c1bb64f8ac3.png)

Best,
Maher

**Comment by thiennn** [comment]
Maybe the Modules collection in ServiceCollectionExtensions is not populated by LoadInstalledModules method?

**Comment by sau-lanvy** [comment]
@MaherJendoubi You can add the modules as a new parameter in your AddCustomizedMvc method instead:

`AddCustomizedMvc(this IServiceCollection services, IList<ModuleInfo> modules)`

Then use it in the Startup.cs file as follow:
`services.AddCustomizedMvc(GlobalConfiguration.Modules);`

**Comment by MaherJendoubi** [comment]
@thiennn :+1:  @sau-lanvy :+1:  thanks for the help, the problem was that the object Configuration null.

@thiennn I will refactor the code and do some tests then I will do a PR :)

**Comment by MaherJendoubi** [comment]
@thiennn https://github.com/simplcommerce/SimplCommerce/pull/46

**Comment by thiennn** [comment]
nice, thank you
