### ISSUE TITLE
implement IScheduledTask or implement BackgroundService?

### ISSUE THREAD

**Issue by afernandes** [simplcommerce/SimplCommerce#450]
#353 Would you have any examples of using the AddScheduler method?
What's the best alternative, implement IScheduledTask or implement BackgroundService?

**Comment by thiennn** [comment]
You should implement IScheduledTask if you want to have the ability to config the schedule for the task to run, for example 1 a days, every hours, etc. using cron expression.

Implement BackgroundService if you want to have a task always run continuously.

I don't have the sample of using  IScheduledTask at the moment. Basically, after you have an implement of IScheduledTask and set the Schedule (cron expression), then register it with service collection.

Then call AddScheduler() in ConfigureService to register SchedulerBackgroundService. Then it should work

**Comment by afernandes** [comment]
I got it, thanks!
How about using the [hangfire](https://www.hangfire.io/) for background processes?
