### ISSUE TITLE
View stock history

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#458]
In the Stock Management page, Add a new column call "Stock History" value View history" when click on this link will show a stock history page, that contains a table of the stock history of that product in the selected warehouse

Product Name | CreatedOn | CreatedBy | AdjustedQuantity | Note

**Comment by justindongqiang** [comment]
@thiennn I ma testing the changes now and just wondering how do you created records in StockHistory table. Click "Add All Products" does not seem to add an stock history

![image](https://user-images.githubusercontent.com/18490641/47319454-56473f80-d614-11e8-98be-d10919681b3e.png)

**Comment by thiennn** [comment]
@justindongqiang stock histories are added when you (+/-) Adjusted Quantity then Save

**Comment by justindongqiang** [comment]
@thiennn I submitted the PR.

**Comment by justindongqiang** [comment]
View history is not relevant to how the history is generated,
@thiennn but I still need to see it...
"when you (+/-) Adjusted Quantity then Save", do you mean click "Add all products" on the top right?
where is the save button when changing the quantity?

**Comment by thiennn** [comment]
the save button at the bottom
