### ISSUE TITLE
Is it possible to run IIS without Docker?

### ISSUE THREAD

**Issue by afernandes** [simplcommerce/SimplCommerce#460]
Is it possible to run IIS without Docker?

**Comment by thiennn** [comment]
Absolutely yes

**Comment by thiennn** [comment]
https://docs.simplcommerce.com/en/latest/development-tips. Just make sure the gulp-copy is run correctly.
To deploy to IIS, all you need is publish the WebHost using either Visual Studio or dotnet cli, the output folder then ready to deploy to IIS

**Comment by afernandes** [comment]
IIS in-process hosting moved out of ASP.NET Core 2.1
[https://github.com/aspnet/Announcements/issues/302](https://github.com/aspnet/Announcements/issues/302)

**Comment by ViacheslavMelnichenko** [comment]
@thiennn could you please provide simple instruction how to run with IIS.
I receive an error when try to run published site.

**Comment by thiennn** [comment]
@ViacheslavMelnichenko Please share the details error mesage

**Comment by ViacheslavMelnichenko** [comment]
My steps are next:
1) Clone the repository;
2) Check gulp is available - tasks run with no error;
3) Switch to release and build, here is the log:
[https://gist.github.com/ViacheslavMelnichenko/162459721470c83b8a0259357e0e4bc8](url)
4) Publish to local file as release:
[https://gist.github.com/ViacheslavMelnichenko/4cf4cd36786c35988ac81e7d5ac48850](url)
As you mentioned in other topics I should have .dll file in service directories such as SimpleComAuto\Modules\SimplCommerce.Module.ActivityLog, but only module.json file are there.
And all the dll files are in root SimpleComAuto though.

5) When I start it via IIS I receive next error *HTTP** Error 502.5 - Process Failure*.
In my opinion there are something wrong with my publishing? Thank you.

**Comment by thiennn** [comment]
4. That fine.
5. In the root of the site. Find Web.config. Set log to true. Create the logs folder. Run the site again and view the log

**Comment by ViacheslavMelnichenko** [comment]
ok, I have add next one to webconfig:
  <system.web>
    <customErrors mode="Off"/>
</system.web>
  <system.webServer>
  	<httpErrors errorMode="Detailed" />

ErrorLog here:
[https://gist.github.com/ViacheslavMelnichenko/49735ca993e36f210db4af251edbbe79](url)

Should I add **IIS APPPOOL\SImpleComAuto** user to DB?

**Comment by ViacheslavMelnichenko** [comment]
so, I have switch Identity to LocalSystem in App Pools. And now it is seems working fine. Thank you!
