### ISSUE TITLE
Seperate Admin and Store

### ISSUE THREAD

**Issue by EmreKarahan** [simplcommerce/SimplCommerce#466]
Can we make the store and Admin seperate applications?

Because this situtation will cause scalability and performance problems in the future.

**Comment by thiennn** [comment]
For simplify, we have chosen not separate and store-front and the admin. But if you want, you can do it with a little modification. 
- Make use of external storage: Azure Blob or AWS S3.
- Deploy 2 applications and if you like you can prevent access or redirect  to admin or store-front

**Comment by sunnykachwala** [comment]
@EmreKarahan are you able to resolve the stuff?
