### ISSUE TITLE
Add Comments modules

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#476]
Add new comment modules.

- Comment 1
    - Comment reply
    - Comment reply
    - Comment reply
- Comment 2
    - Comment reply

1 level of reply, pagination on comment only

**Comment by teeshter** [comment]
I can help with this module. How is this different than the review module?

**Comment by thiennn** [comment]
The difference is with comment, we don't need the rating and the title.

**Comment by thiennn** [comment]
It should be display at the bottom of the product details page. Maybe we should required the users to login before adding comments. I have sample screenshot, but it's in Vietnamese, not sure that can help

**Comment by thiennn** [comment]
Hi @teeshter, How are you doing? Any update on this?

**Comment by justindongqiang** [comment]
Not sure how this goes? I am new here and I am interested in contributing. Can you let me know best way to get it started? or if there is any similar checkin I can refer to it?

Thanks,
Justtin

**Comment by justindongqiang** [comment]
@thiennn do you have an email or skype we could communicate?

**Comment by thiennn** [comment]
@justindongqiang  nlqthien@gmail.com or skype:nlqthien. You can look at the Review module

**Comment by justindongqiang** [comment]
Thanks you @thiennn. I will look at the review module first.

**Comment by teeshter** [comment]
@thiennn  I haven't started on this one yet. I've been working on the replies for the review module first. That one is done. Is justindongqiang working on this one now?

**Comment by justindongqiang** [comment]
@teeshter If you haven't started yet, I can work on it, no worries. Just I am new here and may take a bit more time to get up to speed.

**Comment by teeshter** [comment]
@justindongqiang Why don't you go ahead and work on it? Since you are new and this is very similar to the Review module from what I understand, it'll be a good first issue for you to work on.

**Comment by justindongqiang** [comment]
@teeshter thanks and I will work on it...

**Comment by justindongqiang** [comment]
@teeshter I have project loaded it up on my laptop and starting looking into it... as I am new here and also I the last time I used angularjs was a couple years ago. Please allow me to take some time to get my memory back. Meantime, if you know any good dev document to get started with the project, please let me know. Appreciate it:)

**Comment by justindongqiang** [comment]
@thiennn where do we want to place the comment in the page of product details?

![image](https://user-images.githubusercontent.com/18490641/42720567-b6a9d538-86ee-11e8-9641-94933e1672be.png)

**Comment by thiennn** [comment]
@justindongqiang Please place it below the review. We will revise the layout of the product details page after you finish.

**Comment by justindongqiang** [comment]
@thiennn Did you receive the email I sent? Just want to make sure I was using the correct email address.

**Comment by thiennn** [comment]
@justindongqiang Yes, I have receive your email, a lot of emails :D Actually, I think we both discuss here, or https://gitter.im/simplcommerce/SimplCommerce. Thanks

**Comment by justindongqiang** [comment]
@thiennn don't worry about it for now, I am putting all the pieces together and then we can review them.

**Comment by thiennn** [comment]
@justindongqiang I don't think we need EntityType and EntityId for Comment. The UserId should be nullable  long? because we may allow users comments before login. We should have ParentId to support nested comments

**Comment by justindongqiang** [comment]
@thiennn I saw the review module that the entity id and entity type id represent a specific product. 
A comment also belongs to a product, is that right? If no  EntityType and EntityId for Comment, how do we link comment to product?

**Comment by justindongqiang** [comment]
@thiennn the new entity "Comment" is not being picked up by database migration, when I run database-update. Any ideas?

**Comment by thiennn** [comment]
@justindongqiang You are right, we need the EntityType and EntityId for Comment. You should name the Migration AddCommentModule
