### ISSUE TITLE
How to quick edit and Debug?

### ISSUE THREAD

**Issue by mrsherlock88** [simplcommerce/SimplCommerce#478]
In my case, I have another library CIS.Client, only SimplCommerce.Order use this lib.
Each time I edit code inside CIS.Client, I always rebuild CIS.Client, then SimplCommerce.Order, then WebHost to make it possible to Debug. If not, it show ```Breakpoint will not currently be hit. No symbols loaded for this document.```

With simple project, I just stop debug, edit the code then Hit F5 to run again. With SimplCommerce, there'are too many projects, they take too much time and step to debug a single line.

Am I missing something?

**Comment by thiennn** [comment]
@mrsherlock88 the easiest way is right click on the solution and choose build (not rebuild), unchanged projects will be skipped.

Btw, are you using the latest code of SimplCommerce?

**Comment by mrsherlock88** [comment]
Thanks for advise, any other solution to just edit and hit F5?

Anw, I cloned the repo about a month ago, and change both in core (Add, Remove columns, Remove Modules .....) so I can not get latest.

**Comment by thiennn** [comment]
With the latest code I think you can just edit and hit F5

**Comment by mrsherlock88** [comment]
Yep, I will try and merge our code into the latest source.

Many thanks,
