### ISSUE TITLE
Add token-based or basic authentication method

### ISSUE THREAD

**Issue by spielinger** [simplcommerce/SimplCommerce#487]
In order to make calls to the ApiControllers from external clients it would be good, to have an authentication method other than cookie authentication in the SimplCommerce.WebHost app.

Or how can I easily extract an web.api project from the SimplCommerce.WebHost that only handles the calls to serveral ApiControllers (ProductApiController, StockApiController, etc.)?

Why should I want to call the ApiControllers from an external app? For example it would be needed for a connector (ERP <-> simplcommerce) that does the product creation and updates or gets the orders. Like the API in Shopify (https://help.shopify.com/api/reference/products/product) that allows to manage the shop from an external app. In real shop scenarios you cannot manage a bigger shop within the simplecommerce admin backend.

**Comment by thiennn** [comment]
I can add a simple token authentication shortly, but it's might not support refresh token yet

**Comment by spielinger** [comment]
This would be fine!

**Comment by thiennn** [comment]
Now you can use it and let me know if it work for you.

To get the token:
POST /api/token/create

{
	"Username" : "admin@simplcommerce.com",
	"Password": "1qazZAQ!"
}

Then add the token return to the Authentication header

Authorization Bearer tokenReturned
