### ISSUE TITLE
Show a tree of categories in product filters

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#491]
Currently it only show the top category
![cattree](https://user-images.githubusercontent.com/289607/42000184-2295011c-7a8a-11e8-85e6-af031218f90c.png)

**Comment by justindongqiang** [comment]
Let me look into this issue.

**Comment by justindongqiang** [comment]
@thanhxuanhd thank you.

**Comment by unencode** [comment]
Is there a way to show this category filter with sub categories on the CategoryDetail page?
