### ISSUE TITLE
Staticdata violates not null constraint, consider default value rule for Culture Entity

### ISSUE THREAD

**Issue by AdnanCukur** [simplcommerce/SimplCommerce#494]
Property IsDefault in Localization_Culture has a not null constraint, but no default value is set through code first. 

StaticData SQL scripts inserts cultures without a IsDefault value, this works with mysql since it ignores constraints and just chooses a default value, but this crashes with postgresql.

`INSERT INTO "Localization_Culture" ("Id", "Name") VALUES (1, 'vi-VN');`

```
ERROR:  null value in column "IsDefault" violates not-null constraint
DETAIL:  Failing row contains (1, vi-VN, null).
```

Consider adding default value rule for Culture entity in code

`modelBuilder.Entity<Culture>().Property(x => x.IsDefault).HasDefaultValue(false);`

**Comment by thiennn** [comment]
Thanks, btw the static data for postgreSQL and MySQL are a bit out of date :)
