### ISSUE TITLE
Clone a product

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#5]

**Comment by justindongqiang** [comment]
Hi @thiennn 
where do you want to place the button of "Clone Product"?

**Comment by thiennn** [comment]
I think top right is the suitable position

**Comment by justindongqiang** [comment]
Do you mean the product page in admin area?

**Comment by justindongqiang** [comment]
Thanks. Will do.

JD.

________________________________

**Comment by justindongqiang** [comment]
@thiennn I noticed there is method called Clone() in Product class. I don't see it is good enough. 
There are many many child items, when "Clone", do we need to keep all of them or just copy over ProductAttributeValue and ProductCategory?

**Comment by thiennn** [comment]
I think this clone feature (button Clone) we should clone everything except the variations

**Comment by justindongqiang** [comment]
PR: https://github.com/simplcommerce/SimplCommerce/pull/658
