### ISSUE TITLE
Problems with documentation hosting

### ISSUE THREAD

**Issue by vctrferreira** [simplcommerce/SimplCommerce#500]
Hello guys,

So I tried open the documentation this morning and I get some errors about the cloudflare.

https://docs.simplcommerce.com/

![captura de tela 2018-07-18 as 14 35 50](https://user-images.githubusercontent.com/9720953/42897923-fc50a772-8a97-11e8-8708-7a2243d346a4.png)

So I'm here to warning you all, this documentation was hosted in another place? If yes, someone can send me the link of them?

**Comment by thiennn** [comment]
@vctrferreira the problem has been fixed. The doc repo is here https://github.com/simplcommerce/docs
