### ISSUE TITLE
Recently viewed product widget

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#501]
Make a recently viewed product widget so that it can be configured to display in many places, for example the homepage

**Comment by tabiodun** [comment]
Looks like the existing recently viewed widget works in other places as-is

**Comment by tabiodun** [comment]
What exactly are you looking to do here. To add an instance of the recently viewed widget to the home page?

**Comment by thiennn** [comment]
Add a new widget called RecentlyViewedProducts. You can look at the docs here http://docs.simplcommerce.com/en/latest/widgets/. You can see the existing widgets by going to the Admin, in the top menu choose Content --> Widgets --> Create Widgets

**Comment by tabiodun** [comment]
Sounds good. I can take this on. Do you have any specifications for the options that should be available for the widget?
