### ISSUE TITLE
How to upload product images in Azure storage 

### ISSUE THREAD

**Issue by Vaidehi17** [simplcommerce/SimplCommerce#511]
Hi,

When i add new product and product images/documents, they are getting uploaded to local storage.

How to upload it on Azure blob storage instead of local storage?

**Comment by thiennn** [comment]
You can follow the doc for AWS S3 here to enable StorageAzureBlob module. They are similar.

The config for Blob

```json
"Azure" : {
    "Blob" : {
        "StorageConnectionString" : "<your connection string>",
        "ContainerName" : "<your container name>",
        "PublicEndpoint" : "<optional, set the value here in case you use your own domain for blob>"
    }
}
```

Please let me know whether it work for you

**Comment by Vaidehi17** [comment]
I did the same thing.

It worked for me when i have run copy_module task in task explorer after adding module.json in  
StorageAzureBlob module.

Thanks!
