### ISSUE TITLE
Long running query

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#513]
Environment: https://demo.simplcommerce.com
Stats: [ActivityLog_Activity], 62424 records
SQL generated by EF:

```sql
SELECT TOP(5) [a].[EntityTypeId], [a].[EntityId], [e].[Name], [e].[Slug], COUNT(*) AS [ViewedCount]
FROM [ActivityLog_Activity] AS [a]
INNER JOIN [Core_Entity] AS [e] ON ([a].[EntityId] = [e].[EntityId]) AND (([a].[EntityTypeId] = [e].[EntityTypeId]) OR ([a].[EntityTypeId] IS NULL AND [e].[EntityTypeId] IS NULL))
WHERE [a].[ActivityTypeId] = CAST(1 AS bigint)
GROUP BY [a].[EntityId], [a].[EntityTypeId], [e].[Name], [e].[Slug]
HAVING [a].[EntityTypeId] = 'Product'
ORDER BY [ViewedCount] DESC
```

It take around 19 seconds to execute. 

Note: before changing EntityTypeId datatype from long to string. It very much faster. I haven't thought that that changing have a big impact on performance. EntityTypeId column has been indexed

**Comment by thiennn** [comment]
Thank @mrsherlock88 , just check the current database on demo
[Core_Entity].[EntityTypeId] nvarchar(450) NULL
[ActivityLog_Activity].[EntityTypeId] nvarchar(MAX) NULL

I think the biggest problem is  nvarchar(MAX) which is not good be indexed. After alter both to nvarchar(100) NOT NULL,  the query run super fast.

**Comment by mrsherlock88** [comment]
Yep, JOIN and INDEX work well without complex condition, NULL value make the condition complex, I am not sure it affects to the way index work or not.
