### ISSUE TITLE
Show product overview in the popup dialog 

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#519]
When user click on the Quick View button on an item in the product list will show a popup contains overview information of the product.

Add an config option in the admin to enable or disable this feature

**Comment by justindongqiang** [comment]
I will be working on this story.

**Comment by justindongqiang** [comment]
@thiennn the page for product details is Modules\SimplCommerce.Module.Catalog\Views\Product\ProductDetail.cshtml, do you think to move it to shared view folder so we can reuse it with model window?

**Comment by justindongqiang** [comment]
Sine this is only going to show product overview, I am assuming it has different content with product detail. I will get modal window works first and then let us review what information would be displayed in overview page.

**Comment by thiennn** [comment]
Yes, it is a simplify version of product details. I think it should contain name, images, variants, short description, prices, add to cart button, add to wishlist, add to compare.

**Comment by justindongqiang** [comment]
Pull request #561 created.

**Comment by thiennn** [comment]
Working on SampleTheme
