### ISSUE TITLE
Consider moving modular functionality to ExtCore framework

### ISSUE THREAD

**Issue by DmitrySikorsky** [simplcommerce/SimplCommerce#52]
We could cut out existing modular functionality from SimplCommerce and replace it with ExtCore framework's one. This approach can have next advantages:

- code is much simpler and cleaner, focused on the main task of the project (e-commerce), not modularity;
- real possibility to reuse extensions (modules) in different projects from different developers;
- bigger community for both projects;

**Existing projects on ExtCore as samples**
- [Platformus CMS](https://github.com/Platformus/Platformus);
- [ThemeManager](https://github.com/artemb89/ExtCore.ThemeManager).

**Possible problems**
ExtCore is not only modularity framework but like architecture pattern too. So it could take some time to build it into the existing project.

Thank you for your reply and your opinion.

**Comment by thiennn** [comment]
Hi Dmitry,

Actually, we have considered ExtCore and some other solutions before starting our own modular approach. I have written an article about this here http://www.codeproject.com/Articles/1109475/Modular-Web-Application-with-ASP-NET-Core.

Our principle is trying to keep thing as simple as possible.

**Comment by DmitrySikorsky** [comment]
Hi Thien! Thanks for the answer!
