### ISSUE TITLE
Warming up Application

### ISSUE THREAD

**Issue by michael-nee** [simplcommerce/SimplCommerce#523]
Does anyone know a way to warm-up the application?  The first load to the page is very long.  Will be using with Docker and Swarm mode so need a way to ensure warm-up is done before some hits the site.

**Comment by thiennn** [comment]
Not sure but can a Healthcheck help?

**Comment by vascofernandes** [comment]
My recommendation is to have your CI/CD pipeline hit the site as part of the deployment process.

You can also consider writing a simple UI test to make sure the application was deployed and started correctly; thus doing 2 things in one shot.

**Comment by thiennn** [comment]
After the switch to Razor Class Lib, now all the default view are complied at build time. The warm up time has been reduce a bit.
