### ISSUE TITLE
Visual Studio 15.8.x breaks task runner - can't load gulpfile.js

### ISSUE THREAD

**Issue by footysteve** [simplcommerce/SimplCommerce#528]
Just fyi, new to GitHub not sure where to put this. Apologies if it's in the wrong place I thought it important to mention as this is part of SimpleCommerce installation process..

Updating to Visual Studio 15.8.x breaks task runner, the file cannot be loaded - described with solution here..

https://developercommunity.visualstudio.com/content/problem/312584/update-158-broke-task-runner-gulpfile.html

**Comment by thiennn** [comment]
@footysteve Creating issue is the correct way to put this, and also bugs, features request or even questions.

The problem you described is the problem of visual studio and itself. So I think I should close this as there is no further action needed.
