### ISSUE TITLE
Error deloy IIS

### ISSUE THREAD

**Issue by balasratran** [simplcommerce/SimplCommerce#533]
> Application startup exception: System.IO.FileNotFoundException: Could not load file or assembly 'SimplCommerce.Module.StorageLocal, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'SimplCommerce.Module.StorageLocal, Culture=neutral, PublicKeyToken=null'

please guide how to fix it for me. Thank you

**Comment by thiennn** [comment]
Build the hold solution in Release mode before publish

**Comment by balasratran** [comment]
Thanks, has been fixed.
