### ISSUE TITLE
#480 The command "npm run gulp-copy-modules -- --configurationName Debug" exited with code 9009

### ISSUE THREAD

**Issue by avenxu** [simplcommerce/SimplCommerce#534]
Hi,
When I try to build the solution from scrach I kept getting this error:
"The command "npm run gulp-copy-modules -- --configurationName Debug" exited with code 9009"
Any idea why?

Thanks

**Comment by thiennn** [comment]
Are you build from command line or in Visual Studio? Normally it is required to have nodejs installed, also check  what is your nodejs version

**Comment by avenxu** [comment]
I did have nodejs installed (8.11) and was building from visual studio 2017.
I cleaned my solution and ran it again as an admin the the issue remains.

**Comment by thiennn** [comment]
Please open the command line windows at the SimplCommerce.WebHost folder and run the command npm run gulp-copy-modules -- --configurationName Debug to see the detail error
