### ISSUE TITLE
Refactor front-end of the reviews, comments using Vue for better user experience

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#536]

**Comment by vascofernandes** [comment]
Since I am working on a proposal for using Typescript with AngularJS in 
https://github.com/simplcommerce/SimplCommerce/issues/526 I would suggest to put this on hold and instead go for Web Components as much as possible.

**Comment by thiennn** [comment]
for the comments, reviews, for example I think it will be better to not reload the page after added new items. I see Vue is tiny and simple enough for mini spa like this.

**Comment by jalvarezca** [comment]
I was thinking the same. It would be nice that the UI doesn't need to refresh the all page on each event, like when changing the filter. Angular provides all the tools to do a good SPA.
