### ISSUE TITLE
Completely delete a product

### ISSUE THREAD

**Issue by selombanybah** [simplcommerce/SimplCommerce#537]
Hi,
I'm still new to the application, please is there a simple way to completely delete a product? I mean hard delete.  If not I will have to write the sql query to delete product and linked data

**Comment by thiennn** [comment]
Why you want to do hard delete the product. It's not easy because there are too many table depend on it

**Comment by selombanybah** [comment]
You are right. Its just in a scenario where I finish testing with products data and want to clean database for production. In that case, I do not want to delete things like product attributes and options but only the products and categories. I can import new products for production in excel files (using https://github.com/SheetJS/js-xlsx)

**Comment by thiennn** [comment]
@selombanybah to clean up the database, you can prefer to the script https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.SampleData/SampleContent/Fashion/ResetToSampleData.sql and modify it according your need
