### ISSUE TITLE
error MSB3073: The command "npm run gulp-copy-modules -- --configurationName Debug" exited with code 134

### ISSUE THREAD

**Issue by MikoSharp** [simplcommerce/SimplCommerce#538]
I'm following the super detailed installation guide:  https://docs.simplcommerce.com/en/latest/getting-started/     to Linux. and my vps is: Ubuntu 16.04 4GB 30GB 

![sin titulasdasd](https://user-images.githubusercontent.com/11472688/45057471-55a21c00-b05b-11e8-9419-25b655abba77.png)

installed 
dotnet --version 2.1.401
node --version v10.9.0
PostgreSQL 9.5.14 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609, 64-bit

**Comment by thiennn** [comment]
@MikoSharp Please run the command "npm run gulp-copy-modules -- --configurationName Debug" in the terminal at SimplCommerce.WebHost so that we can see the detail error

**Comment by MikoSharp** [comment]
![abcbroncol](https://user-images.githubusercontent.com/11472688/45060950-ea127b80-b067-11e8-8d1c-14019b9d59c6.png)
I try 5 hours, I try google and documentation.

**Comment by thiennn** [comment]
Please uninstall node v10.9.0 and install node 8.11.4 (the LTS version)

**Comment by MikoSharp** [comment]
I create new vps, and install node 8.11.4. and is ok result "sudo ./simpl-build.sh"
but in "In the terminal, navigate to the "src/SimplCommerce.WebHost" type "dotnet run" and hit "Enter"."
![newerror](https://user-images.githubusercontent.com/11472688/45067659-b5afb700-b089-11e8-8787-c71a38b9b836.png)

**Comment by thiennn** [comment]
It's seem that the connection string for Postgres isn't correct

**Comment by MikoSharp** [comment]
@thiennn I try with SDK 2.1.401 .NET Core, 
// Is the version necessary? in the Prerequisite to linux, SDK 2.1.1
Thanks thiennn

**Comment by thiennn** [comment]
SDK 2.1.401 is the correct version. 2.1 is just the general team
