### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by fetullahyldz** [simplcommerce/SimplCommerce#540]
hello i am getting error when installing error code as below

System.InvalidOperationException: 'Unable to determine the relationship represented by' User.UserAddresses' of type 'IList <UserAddress>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.

**Comment by thiennn** [comment]
It seems that the modules are not copy to the WebHost correctly. Please describe steps you have been done

**Comment by fetullahyldz** [comment]
Thanks for your answer But I Get Different Error This Time MSB3073 "npm install" command exited with 9009 code.

**Comment by thiennn** [comment]
This seem there is a problem with nodejs on your machine

**Comment by fetullahyldz** [comment]
node.js I've done a lot of updates, but the result might still be the same gulpfile.js error

**Comment by footysteve** [comment]
seen a lot of these types of error, it's why I posted this - probably related - Visual Studio 15.8.x breaks task runner - can't load gulpfile.js #528

**Comment by thiennn** [comment]
try to run "npm install" in the command windows at the folder SimplCommerce.WebHost

**Comment by muratcabuk** [comment]
I have got the same error today. I realized NodeJS is not installed in my system :) I installed NodeJS and "dotnet build" command worked. Also I didn't get gulp error again. Im using VS 2017 v 15.8.2.

**Comment by thiennn** [comment]
Please make sure you have nodejs 8.x or 10.x installed

**Comment by fetullahyldz** [comment]
hello i've tried them all but again the problem continues the same

**Comment by thiennn** [comment]
@fetullahyldz Can you describe step you have done and take some screeshot

**Comment by fetullahyldz** [comment]
I have installed the latest version of nodejs but the problem can still cause this same

![image](https://user-images.githubusercontent.com/6751949/45798339-3984b880-bcb2-11e8-9ee5-7b559a81bcc5.png)

**Comment by thiennn** [comment]
@fetullahyldz . Please add my on skype: nlqthien. So that I can support you better

**Comment by tomanye** [comment]
Still not fixed
