### ISSUE TITLE
Add Brand name to ProductDetail in SimplCommerce.Module.Catalog module

### ISSUE THREAD

**Issue by jducobu** [simplcommerce/SimplCommerce#542]
Add and mange BrandDetail (Name and Slug) to ProductDetail in SimplCommerce.Module.Catalog module

**Comment by jducobu** [comment]
Name and Slug

**Comment by thiennn** [comment]
I don't get your point. Currently you can select brand for products

**Comment by jducobu** [comment]
Allow to show brand name in product detail view
