### ISSUE TITLE
Localization Improvements

### ISSUE THREAD

**Issue by hishamco** [simplcommerce/SimplCommerce#545]
I investigate the localization stuff in SimpleCommerce  the time I'm writing this issue, I find there 're some improvements that we can made:

- No need for `ResourceString` while we already have `Resource` model
- Loading all the resources for all the cultures may not preferable in this, we can use load on demand strategy, so whenever a translation is needed for certain culture we will go to database and cache the resources for future use
- Introduce localization resource caching
- Store the default culture & UI culture in the database by introducing a `EFLocalizationCultureProvider`
- `GlobalConfigurations.Cultures` should be read only

I will keep update this list until ...
/cc @thiennn

**Comment by hishamco** [comment]
I have two questions:
1. `SimpleCulture` needs to be replaced with `Culture` model
2. Why we need `ResourceItemVm`?!!

**Comment by thiennn** [comment]
1. agree
2. ResourceItemVm is used as a view model for the https://demo.simplcommerce.com/admin#!/localization page

**Comment by hishamco** [comment]
If my earlier comments are fine for you, I will push a PR for that

**Comment by thiennn** [comment]
Yes, can't wait to see your PR

**Comment by hishamco** [comment]
I think I will break down the above point into manageable PRs for simplicity
