### ISSUE TITLE
how to add more languages

### ISSUE THREAD

**Issue by osmanrahimi** [simplcommerce/SimplCommerce#555]
1-in the managing Translations page  there are just some languages up to 10 , I wonder to know if I want to add one more language can I do that with admin panel or I have to change the database ?

2- do you have any plan to add `RTL` model   for some languages like `Arabic ` or `Persian`?
thank you

**Comment by hishamco** [comment]
1- Have a look to a `Database` folder there 're database scripts per culture
2- Issue #557

**Comment by hishamco** [comment]
Is this solved you question?

**Comment by hishamco** [comment]
@thiennn while the question is answered and there's no reply from the author, so this should be closed
