### ISSUE TITLE
Dependency problem in EfRequestCultureProvider

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#558]
It's seem that the EfRequestCultureProvider is called too early that the HttpContext.User hasn't been filled. The WorkContext is also not resolved per request as expected. Maybe it being resolved before asp.net core start the dependency Scope.

cc @hishamco

**Comment by hishamco** [comment]
Perhaps the middleware order, but I didn't ran into an issue with this, Do you have a certain scenario where this throws an exception?

**Comment by thiennn** [comment]
Testing on my laptop. The user return by the WorkingContext is differ from the HttpContext.User. Debug through the code, I see the problem.

**Comment by hishamco** [comment]
But this may related to how the user is set in `WorkContext`
