### ISSUE TITLE
Gulpfile

### ISSUE THREAD

**Issue by rafsanulhasan** [simplcommerce/SimplCommerce#560]
the line
https://github.com/simplcommerce/SimplCommerce/blob/2c246554b00f860d215585db7e5e959785e5793a/src/SimplCommerce.WebHost/gulpfile.js#L61

should be changed to `if (module.isBundledWithHost) {`
other wise it does not copy dlls from **Modules** to **WebHost/Modules**

**Comment by thiennn** [comment]
If the module is bundled with host. That module should be added as project reference in the WebHost. Then its dll already in the WebHost, so no copy needed.

**Comment by rafsanulhasan** [comment]
Okay, so only SampleData is being copid to WebHost for the time being. When I run Update-Database from PMC defaulting the WebHost project, it shows up an error and ends up with failing database migration. What could be the workaround to fix this issue?

**Comment by thiennn** [comment]
Can you share your code so that I can look into

**Comment by rafsanulhasan** [comment]
**update-database** failed with following:
`System.InvalidOperationException: Unable to determine the relationship represented by navigation property 'Product.ProductLinks' of type 'IList<ProductLink>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`
`Unable to determine the relationship represented by navigation property 'Product.ProductLinks' of type 'IList<ProductLink>'. Either manually configure the relationship, or ignore this property using the '[NotMapped]' attribute or by using 'EntityTypeBuilder.Ignore' in 'OnModelCreating'.`

**Comment by rafsanulhasan** [comment]
What code you are telling me to share? I ran the same code found in master branch to migrate the DB

**Comment by thiennn** [comment]
All. The code on master work fine for me. I Thought you have changed some thing

**Comment by rafsanulhasan** [comment]
Nope, the master branch is untouched. I have set up a pull bot to automatically pull latest changes from upstream to the master of the forked repo.

**Comment by rafsanulhasan** [comment]
I figured the actual issue out. It was a connection string problem. 
I updated it to use LocalDB in development environment in PR #564.
Thanks for your assistance.
