### ISSUE TITLE
[Question + Enhancement] Angular SPA Template provided by VS

### ISSUE THREAD

**Issue by rafsanulhasan** [simplcommerce/SimplCommerce#562]
Hi @thiennn 
After going through the WebHost project, I found that it is using Angular (downloaded via LibMan) and also using jQuery. My question is:

1. Why the VS SPA template for Angular is not being used to setup the an Angular project (Or why Angular is not being used through NPM)
2. If this is built with Angular, why using jQuery since Angular is one of the powerful SPA framework built on the top of JS (JQuery is not needed) compared to jQuery which is a JS Library (for DOM manipulation). 

Because we can manipulate the DOM in a more smarter but efficient way than that of jQuery, IMHO we should use Angular in the first place.

I'll be happy to come up with PRs if you really think it will be helpful.
Thanks in advance.

**Comment by thiennn** [comment]
I don't think we should do this. I am try to get out of nodejs, webpack,... for this version. We might re-consider at V2, but not a the moment
