### ISSUE TITLE
[Feature] Support Razor Pages for Modules UI

### ISSUE THREAD

**Issue by hishamco** [simplcommerce/SimplCommerce#567]
@thiennn it would be nice if we use Razor Pages for all the modules instead of MVC apps, also it's a preparation for [Support Razor UI in class libraries](https://github.com/simplcommerce/SimplCommerce/issues/422)

**Comment by thiennn** [comment]
I am trying to leverage the Razor Class Library. But I prefer MVC over Pages. MVC is a lot more familiar and I think it's easier to do theming and custom routing.

**Comment by hishamco** [comment]
For modules razor pages are easier, don't forget that many of the modules doesn't require a controls or sort type of things .. think about Analytics module, localization and much more, what you need is simply drop some pages and you are ready go. You 're still do theming, custom routes .. etc

**Comment by thiennn** [comment]
I think we should support both MVC style and Razor Pages.  However there is a problem with applying Razor Class Library. Please see my prototype for more details https://github.com/thiennn/dynamicLoadingRazorLib/

**Comment by hishamco** [comment]
> I think we should support both MVC style and Razor Pages

IMHO we can make the host as MVC app and the modules as razor pages for simple as fast module  development

Regarding your sample I can make a prototype for 1 module and see how's everything will fit

**Comment by hishamco** [comment]
> Theming doesn't work well though because razor pages wont work with View Expanders.

How is told you that?!! I already used theme since year ago, have a look to my repo [Bloggy](https://github.com/hishamco/Bloggy) https://github.com/hishamco/Bloggy/blob/master/src/Bloggy/ThemeViewLocationExpander.cs, perhaps there's an issue or something missing in sample you're working with

**Comment by akluthe** [comment]
> https://github.com/aspnet/Mvc/issues/7332#issuecomment-382154674

This comment seems to indicate it only works for layouts and partials. 

I was working with Thien's repo and I can't overide RCL plugin views with local view files in the ~/Themes/TestTheme folder of the WebHost project.

I'll set a fork up and show you what I mean and maybe we can figure it out.

**Comment by hishamco** [comment]
I see, seems the issue occurs with the localized Razor Pages

**Comment by akluthe** [comment]
Well, that thread is about localization, but the issue from the linked comment is broader.

They were trying to use what we want to do for Themes to implement localization in their project, but found out it won't work because the view expander only works with partials and layouts.

I modified Thien's repo here to show what I mean.

> https://github.com/akluthe/dynamicLoadingRazorLib

I can get the view file circled in blue to work because it is not a custom view location like the theme folder.

The view circled in red I cannot get to work.

![image](https://user-images.githubusercontent.com/2624953/46222024-be0bb280-c314-11e8-9240-4e7e87177807.png)

**Comment by justindongqiang** [comment]
@thiennn  any update on this?

**Comment by thiennn** [comment]
Applied Razor Class Library. You can add Razor Page to modules but it will not have theming support
