### ISSUE TITLE
Discussions about coding styles

### ISSUE THREAD

**Issue by rafsanulhasan** [simplcommerce/SimplCommerce#588]
## I'm submitting a proposal regarding...

```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Question
[x] Refactoring
[x] Coding styles and conventions
```

## Current conventions
I would like to request a change in coding styles and refactorings
* Block body for methods, constructors and properties
   ```
   public class ClassA {
       private int _a;
       public int A 
       {
            get {  return _a;  }
            set {  _a = value; }
       }
       public ClassA(int a) { _a = a; }
       public int square() { return _a*_a; }
   }
   ```

* Explicit usage of variable declaration
   `string a = "";`
* Importing namespaces in a clumsy way
  ```
  using SimplCommerce.Module.Cms.Models;
  using SimplCommerce.Module.Core.Models;
  using SimplCommerce.Infrastructure.Web;
  namepsace SimpleCommerce.Module.Cms
  {
       class x {...}
  }
  ```
* Longer line
  `A.abcde.defg.hi(a.b.c, abc(asd));`

## Expected conventions
* Expression body for methods, constructors and properties
   ```
   public class ClassA {
       private int _a;
       public int A 
       {
            get => _a;
            set =>  _a = value; 
       }
       public ClassA(int a) => _a = a; 
       public int square() => _a*_a; 
   }
   ```

* Implicit usage of variable declaration
   `var a = "";`

* Importing namespaces in a cleaner way
  ```
  namepsace SimpleCommerce.Module.Cms
  {
       using Models;
       using Core.Models;
       using Infrastructure.Web;
       // static classes 
       using static Infrastructure.Web.ViewComponentExtensions;
       //Specific classes
       using User = Core.Models.User;
       class x {...}
  }
  ```
* Break longer lines into shorter ones
   ```
   query
        .Where(a=>
        {
           ...
          return ...;
        })
       . Select(a=> a.i==d);
   
   ```

## Another suggestion
As I have been encountering many issues regarding indentation, an **.editorconfig** file in the solution root should be there to avoid collision between the settings developer PC's IDE and this project's conventions and best practices. @thiennn  If you agree with this, I can  post a PR for it

## Other information
It'd increase code quality, readability as well as understandability.

**Comment by thiennn** [comment]
I suggest that you should structure like this

### Item 1
*Current*:
*Suggestion*:

### Item 2
*Current*:
*Suggestion*:


- I prefer block body for methods, constructors and properties. Setting default value for properties is expression
- I prefer use var
- I prefer the current importing style:

```cs
using System...
using Microsoft ...
using SimplCommerce ...

namespace ....
{

}
```

- long lines. It depends, I not very strictly on this. Sometime long lines are easier to read than a lot of short line.

Btw, I have added the default .editorconfig. Please take a look and comments on this.

Thanks

**Comment by rafsanulhasan** [comment]
@thiennn 
* I don't understand the confusing statement
  > Setting default value for properties is **expression**

  Since you
  > prefer block body for methods, constructors and properties
* Since you prefer `var` would you accept PR's about this
* Simplified namespaces should be preferable as I mentioned because   
  * unnecessary imports might degrade performance
    ```
    using SimplCommerce.Infrastructure.Web;
    ```
    imports all the things included while
    ```
    using static SimplCommerce.Infrastucture.Web.ViewComponentExtensions;
    ```
    would import only the class I need for the current class I'm working on
  * using simplified version should be preferable
     ```
     using System;
     namespace SimplCommerce.Module.Cms.Services
     {
           using Models;
           using Core.Models;
           using ...
     }
     ```
    this code is much more cleaner and more readable
* With due respect, I would say
  * In case of `word wrap` is enabled, long lines become nearly unreadable
  * Research says short lines are more readable to most of the developers. 

I'm talking about these convention changes regardless of personal preference/opinion rather most of the developers around the world prefers these the most and these are introduced in the new version releases of c# on the basis of extensive researches on the developer community conducted by .NET team and some of them are discussed in best-practice docs from Microsoft.

**Comment by thiennn** [comment]
I think we better track one by one and implement one by one. For example create an issue about using var, discuss on it, implement for it. Then another issue for example long lines

**Comment by rafsanulhasan** [comment]
sounds good

**Comment by thiennn** [comment]
As discussed https://github.com/simplcommerce/SimplCommerce/issues/588#issuecomment-424139614, feel free to open other issues (one by one)
