### ISSUE TITLE
Create scope (dependency injection) for hosted services

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#597]
There is no scope is created for a hosted service by default. We need to create scope for them.

Currently there is only one hosted service: OrderCancellationBackgroundService. However, we will add more soon

Related to #596

**Comment by hishamco** [comment]
Fixed in https://github.com/simplcommerce/SimplCommerce/pull/596/commits/0cb83be0192ff080daf208d8721f234b32cf0c8a

**Comment by hishamco** [comment]
This [docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.1) has a rich information to implement such thing
