### ISSUE TITLE
Cosmos DB

### ISSUE THREAD

**Issue by myomyinthan** [simplcommerce/SimplCommerce#603]
Hi , 
Any plan to support Cosmos DB in near future? Now cosmos Db is more and more popular 😁

**Comment by michael-nee** [comment]
That would take a pretty fundamental change from SQL to NoSQL?

I know GrandNode is using MongoDB which can use Cosmos DB.  Certainly massive benefits from a read point of view.

**Comment by thiennn** [comment]
As far as I know, modeling the data model for NoSQL is different from relational database. In relational database, we are usually eliminate the data redundant by normalize, normalize and normalize. But in NoSQL normally the entities are self-contained documents. It is not easy to switch between them without changes

**Comment by akluthe** [comment]
This might be possible once entity framework core releases cosmos db as a provider option? Then I would imagine your models would just "work" without much fiddling.

**Comment by rafsanulhasan** [comment]
@thiennn FYI microsoft has added a support for modelling CosmosDB/DOcumentDB in Azure in the same way as we do for relational DB in Reverse-Engineering Code First approach. Please take this issue into account and look deep into it. Thanks

**Comment by hishamco** [comment]
FYI CosomoDB had been added to EF Core, nothing stop you to used https://github.com/aspnet/EntityFrameworkCore/tree/master/src/EFCore.Cosmos
