### ISSUE TITLE
Feature: Export Functionality

### ISSUE THREAD

**Issue by michael-nee** [simplcommerce/SimplCommerce#604]
A number of previous e-commerce solutions have export functionality for orders to CSV and for users?

**Comment by thiennn** [comment]
We have implemented export to CSV for tax https://demo.simplcommerce.com/admin#!/tax-rates. This should be similar

**Comment by hishamco** [comment]
@michael-nee can you share some of those to see what should be exported

**Comment by justindongqiang** [comment]
Wonder what info we want to be exported?

**Comment by michael-nee** [comment]
Should we export from the API to a CSV or use angularjs module to export using Json that is used to show the orders grid?

**Comment by hishamco** [comment]
You can have a look to the Tax module

**Comment by michael-nee** [comment]
> You can have a look to the Tax module

Yes, using the same code for export.

**Comment by hishamco** [comment]
Exactly, that's what @thiennn pointed to earlier

**Comment by thiennn** [comment]
Implemented export to csv for orders and order lines. We might not need to export users
