### ISSUE TITLE
HOW TO CONFIGURE SYSTEMCTL UBUNTU WITH SIMPLCOMMERCE？

### ISSUE THREAD

**Issue by marcelowu** [simplcommerce/SimplCommerce#614]
To create a new systemd file, just use the:
sudo vi /etc/systemd/system/SIMPLCOMMERCE.service

       Below you will find the content of this file, it’s example, if you need you can modify it. Paste it to the created file:
[Unit]
 Description=SIMPLCOMMERCE
 
  [Service]
  WorkingDirectory=/var/webapps/SIMPLCOMMERCE/src/SimplCommerce.WebHost
  ExecStart=/usr/bin/dotnet /var/webapps/SIMPLCOMMERCE/src/SimplCommerce.WebHost
  Restart=always
  RestartSec=10
  SyslogIdentifier=dotnet-SimplCommerce
  User=www-data
  Environment=ASPNETCORE_ENVIRONMENT=Production
 
  [Install]
  WantedBy=multi-user.target

**Comment by thiennn** [comment]
I think you should publish the SimplCommerce.WebHost to a folder first. For example

```
dotnet publish -c Release -o /var/simplcommerce
```
Then update the service path

```
[Unit]
Description=SIMPLCOMMERCE

[Service]
WorkingDirectory=/var/simplcommerce
ExecStart=/usr/bin/dotnet /var/simplcommerce/SimplCommerce.WebHost.dll
Restart=always
RestartSec=10
SyslogIdentifier=dotnet-SimplCommerce
User=www-data
Environment=ASPNETCORE_ENVIRONMENT=Production

[Install]
WantedBy=multi-user.target
```

**Comment by marcelowu** [comment]
thanks
