### ISSUE TITLE
Unable to determine the relationship represented by navigation property 'User.UserAddresses' of type 'IList<UserAddress>'

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#62]
![image](https://cloud.githubusercontent.com/assets/1798510/18817242/52aaf91e-835c-11e6-8dd9-6d11ae0a0577.png)

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/18819087/8d18fd80-8389-11e6-95d1-33a7e0301ceb.png)

**Comment by thiennn** [comment]
Hi @MaherJendoubi,

Please make sure that you compile all the projects, not just the WebHost as in the instructions
In the Console Windows, type "cd .." then press Enter to change directory to /src
Type "dotnet build **/**/project.json" then press Enter
Type "cd SimplCommerce.WebHost" then press Enter
Type "npm install" then press Enter
Type "gulp copy-modules" then press Enter

**Comment by MaherJendoubi** [comment]
λ dotnet build //project.json
Could not find project file '//project.json'

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/18819309/cb088188-838e-11e6-98c2-5fddd9c57318.png)

**Comment by thiennn** [comment]
Type "dotnet build \*\*/\*\*/project.json" then press Enter

**Comment by thiennn** [comment]
The start is a special character
The full instructions https://github.com/simplcommerce/SimplCommerce/blob/master/README.md

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/18819360/c2a683cc-838f-11e6-8201-7e8d77740dc7.png)

**Comment by MaherJendoubi** [comment]
@thiennn 👍 👍 👍
