### ISSUE TITLE
how-to-add-new-modules： Microsoft.NET.Sdk.Razor and  Microsoft.NET.Sdk.Web

### ISSUE THREAD

**Issue by ghd258** [simplcommerce/SimplCommerce#622]
http://docs.simplcommerce.com/en/latest/how-to-add-new-modules/
![qq 20181012091857](https://user-images.githubusercontent.com/4811375/46842433-1c9a5b80-ce00-11e8-8d00-9bb64f204f7c.jpg)

**Comment by thiennn** [comment]
I sorry the document is out of date. 

```
<Project Sdk="Microsoft.NET.Sdk.Razor">
```

is the correct one

**Comment by ghd258** [comment]
How can the ViewEngine pick up the right location for the Views in modules

**Comment by thiennn** [comment]
As we use Razor Class Library, all the views in the module will be complied into an assembly and at the run time those views are found just like normal MVC Area

**Comment by ghd258** [comment]
route ？

**Comment by thiennn** [comment]
/AreaName/ControllerName/ActionName or you can override it by AttributeRouting
