### ISSUE TITLE
[Admin] Create order

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#628]
For some cases, there is a need for admin to create orders for a customer. An "Create Order" button should be added in the Orders page. 

2 new properties should be added into Order object

```cs
public long CustomerId { get; set; }
public User Customer { get; set; }
```

Update the existing logic related to CreatedBy. If an order created by the customer, then the Customer and CreatedBy are the same. If an order create by the admin then CreatedBy is the current logined user and the Customer is the user who this order is created for.

**Comment by codingdefined** [comment]
@thiennn I would like to work on this, few questions.

1. Is there a Separate Button for Admin to create the Order for the Customer.
2. Can Admin create an order for himself?
3. When creating an Order, should we create a dropdown by which Admin can select the which customer he is creating an order for.

**Comment by codingdefined** [comment]
Thanks @thiennn for the information. One more thing, for every Order Cart, is mandatory, so should the admin add products in his cart and then create the Order for the customer? Also does the Customer be in the dropdown or it should be a search field?

**Comment by thiennn** [comment]
Just do a quick check. In the Order class, there are no information about the Cart, I think we can create a Order without Cart

**Comment by codingdefined** [comment]
But in the CreateOrder function of OrderService, it says if Cart is Null, Result.Fail<Order>($"Cart of user {user.Id} cannot be found");. Am I looking at the wrong code, also to create an Order there should be some products added, right?

**Comment by thiennn** [comment]
We might need to create another CreateOrder

**Comment by codingdefined** [comment]
@thiennn I was working on it, since you have started working on it, then no problem

**Comment by codingdefined** [comment]
Yes, What I have done till now is to have a AutoComplete Customer TextBox, where the user can type two or more letters and get the required customer with name and id.

**Comment by thiennn** [comment]
cool, I will factor the Create method in Order service

**Comment by thiennn** [comment]
After investigation, I see it better to apply 1 ordering process for both customer and admin. So we need to add to cart before create order

**Comment by codingdefined** [comment]
Yeah, its better to have Cart, because then you do not need to add Order Items when creating the Order.
