### ISSUE TITLE
An issue displaying duplicate tree of categories in product filters.

### ISSUE THREAD

**Issue by justindongqiang** [simplcommerce/SimplCommerce#630]
An issue displaying sub-categories in search filters. As you can see in the screenshot below, sub-categories display twice. 

![image](https://user-images.githubusercontent.com/18490641/47245467-04f24280-d3bf-11e8-99b1-fc851c96fb32.png)

**Comment by justindongqiang** [comment]
Please assign to me and I will fix it.

**Comment by justindongqiang** [comment]
@thiennn I checked in the fix 
https://github.com/simplcommerce/SimplCommerce/pull/631

**Comment by thiennn** [comment]
Thank @justindongqiang
