### ISSUE TITLE
Override view

### ISSUE THREAD

**Issue by kostyrin** [simplcommerce/SimplCommerce#633]
I created a theme. Make own layout. In the moment my theme looks fine. But when I override a view like Index in my theme, in the result I render just view without header/body/css/js without layout, When I make wrong? Help me.

**Comment by thiennn** [comment]
Add _ViewStart.cshtml to your View directory. Similar this https://github.com/simplcommerce/SimplCommerce/tree/master/src/SimplCommerce.WebHost/Themes/CozaStore/Areas/Catalog/Views

**Comment by kostyrin** [comment]
Thanks
