### ISSUE TITLE
Cannot pull docker image simplcommerce/nightly-build

### ISSUE THREAD

**Issue by ViacheslavMelnichenko** [simplcommerce/SimplCommerce#637]
Since 26.10 I can't pull simplcommerce/nightly-build image via docker.
STR:
1) run "docker run --name simplsite -d -p 5000:80 --link simpldb:simpldb simplcommerce/nightly-build"

Actual result:
Error received -
"C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: pull access denied for simplcommerce/nightly-build, repository does not exist or may require 'docker login'."

**Comment by ViacheslavMelnichenko** [comment]
So I have tried with **simplcommerce/ci-build** and this works for me.
As I understand you should update documentation.

**Comment by thiennn** [comment]
Updated http://docs.simplcommerce.com/en/latest/getting-started/
@ViacheslavMelnichenko  is that where you saw?
