### ISSUE TITLE
Uncaught Error: [$injector:nomod] Module 'simplAdmin.inventory' is not available!

### ISSUE THREAD

**Issue by muhammetsahin** [simplcommerce/SimplCommerce#640]
Hi,

Im using 1.0.0-RC version

And i setup with postgreSQL everything is okey but i've got an error admin panel 

![image](https://user-images.githubusercontent.com/2045788/47919899-af8b5a80-dec1-11e8-9c0d-40e9f6d30250.png)

Thanks.

**Comment by thiennn** [comment]
You should use the latest code on master, the 1.0.0-RC is out of date

**Comment by muhammetsahin** [comment]
Im tried latest version but still same error.

**Comment by thiennn** [comment]
In the browser, view source the page and search for inventory.module.js to see whether it there.
The source file is src/Modules/SimplCommerce.Module.Core/Areas/Core/Views/HomeAdmin/Index.cshtml

**Comment by muhammetsahin** [comment]
![image](https://user-images.githubusercontent.com/2045788/47921510-ce8beb80-dec5-11e8-8079-39318f714a3b.png)

![image](https://user-images.githubusercontent.com/2045788/47921629-1ad72b80-dec6-11e8-813e-2cf7f55aec0c.png)
