### ISSUE TITLE
Event handles called twice 

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#645]
It seems that with services.AddMediatR(); in Startup.cs, all the event handles have been registered automatically. 
Explicit register as below will result to handles being called twice.
services.AddTransient<INotificationHandler<OrderChanged>, OrderChangedCreateOrderHistoryHandler>();

**Comment by Mirivhbv** [comment]
Asking for just learn, why have you registered OrderChangedCreateOrderHistoryHandler to service as twice in Modules/Orders/ModuleInitializer.cs? I couldn't figure out purpose of it.
