### ISSUE TITLE
Allow customers to change billing address

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#646]
Currently the billing address is cloned from shipping address. We want to offer customers a way to edit billing address during the checkout. On the page filling shipping address add an option for customers to change their billing address

**Comment by daniel-loudon** [comment]
Can I be assigned this for my first contribution

**Comment by thiennn** [comment]
Great!. Currently I cannot assign to you on Github, likely the Github issue, but this item is reserved to you

**Comment by daniel-loudon** [comment]
PR #661 Closes this
