### ISSUE TITLE
PayPal Express 

### ISSUE THREAD

**Issue by ak23young** [simplcommerce/SimplCommerce#647]
Hey guys,

Just wanted to point out that PayPal Express doesn't seem to be working correctly.  After clicking the PayPal payment button on '/checkout/payment', the payment window pops up and begins to load, but eventually errors and closes itself.

These errors appear in the Chrome Developer Console: https://imgur.com/a/wkfTgFK

I've tried testing with real credentials in both sandbox and live mode with no success.  It might be worth noting that Stripe payment is working fine.

I'll probably try to dive deeper into the issue sometime later this week.  Does anyone have any suggestions or ideas on where to start though?

Thanks!

**Comment by thiennn** [comment]
It works fine now on ci build https://ci.simplcommerce.com
