### ISSUE TITLE
X-XSRF-Token is not present

### ISSUE THREAD

**Issue by balasratran** [simplcommerce/SimplCommerce#660]
I'm having problems trying to use the Post method.Thank you very much
`info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {area = "Core", action = "List", controller = "UserApi"}. Executing action SimplCommerce.Module.Core.Areas.Core.Controllers.UserApiController.List (SimplCommerce.Module.Core)
info: SimplCommerce.Infrastructure.Web.CookieOnlyAutoValidateAntiforgeryTokenAuthorizationFilter[1]
      Antiforgery token validation failed. The required antiforgery header value "X-XSRF-Token" is not present.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery header value "X-XSRF-Token" is not present.
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
      Authorization failed for the request at filter 'SimplCommerce.Infrastructure.Web.CookieOnlyAutoValidateAntiforgeryTokenAuthorizationFilter'.
info: Microsoft.AspNetCore.Mvc.StatusCodeResult[1]
      Executing HttpStatusCodeResult, setting HTTP status code 400
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action SimplCommerce.Module.Core.Areas.Core.Controllers.UserApiController.List (SimplCommerce.Module.Core) in 2.5785ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 34.3043ms 400 
info: Microsoft.AspNetCore.Server.Kestrel[32]
      Connection id "0HLIDC08RT039", Request id "0HLIDC08RT039:00000013": the application completed without reading the entire request body.`

**Comment by balasratran** [comment]
I have been restore this.
Accept Use this space to summarize your privacy and cookie use policy.

**Comment by kuan62hu** [comment]
Hi balasratran ,
   Can you explain how to fix it?

br,

**Comment by thiennn** [comment]
#663

**Comment by balasratran** [comment]
> Hi balasratran ,
> Can you explain how to fix it?
> 
> br,

Thank you, I learned and understood how it works.
