### ISSUE TITLE
Angular bad request

### ISSUE THREAD

**Issue by kuan62hu** [simplcommerce/SimplCommerce#663]
Hi~
   Recently, I had downloaded the project from gitHub and after executed it, but I always got the message as below:
* URL = http://localhost:49208/admin#!/users
* Browse Error = Possibly unhandled rejection: {"data":"","status":400,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/users/grid","data":{"sort":{},"search":{},"pagination":{"start":0,"totalItemCount":0,"number":50}},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":"Bad Request"}
	  (angular.js:11004)

**Comment by thiennn** [comment]
It looks like the X-XSRF-Token is missing, Have you accepted the cookie consent?

**Comment by kuan62hu** [comment]
I checked the path ~/admin/ and code as below,
 [Route("admin")]
public IActionResult Index()
{ 
    var tokens = _antiforgery.GetAndStoreTokens(HttpContext);
    HttpContext.Response.Cookies.Append("XSRF-TOKEN",
        tokens.RequestToken, new CookieOptions { HttpOnly = false }
    );

    return View();
}
I still got the error again,
URL: http://localhost:49208/api/users/grid
Status: 400 Bad Request

**Comment by kuan62hu** [comment]
@thiennn  The required antiforgery header value "X-XSRF-Token" is not present. How come?

**Comment by thiennn** [comment]
The cookies has not been written, because the cookie consent has not been accepted. I think

**Comment by kuan62hu** [comment]
@thiennn Any suggestion?

**Comment by thiennn** [comment]
pull the latest code and try again

**Comment by kuan62hu** [comment]
@thiennn It's still happened with Safari except to Chrome on MacOS.

**Comment by thiennn** [comment]
tested with Safari on Ipad https://ci.simplcommerce.com/ it works as expected

**Comment by thiennn** [comment]
We cannot reproduce the issue. Btw, if you wish you can turn off the CSRF checking by removing the 

` o.Filters.Add(new AutoValidateAntiforgeryTokenAttribute()); ` at https://github.com/simplcommerce/SimplCommerce/blob/275edaf807d66cb9333b572b88f6165a0c47ffb5/src/SimplCommerce.WebHost/Extensions/ServiceCollectionExtensions.cs#L85

**Comment by thiennn** [comment]
@kuan62hu I'm sorry because I haven't noticed that some themes doesn't show the cookie consent panel. that is the reason why it was hard your you.
