### ISSUE TITLE
Help needed with Azure SQL settings

### ISSUE THREAD

**Issue by JanSichula** [simplcommerce/SimplCommerce#67]
In the meantime, I have decided that to play a bit and run it against Azure SQL so as to gain some experience until PostgreSQL version matures. Unfortunately, I am unable to populate database with sample data. It results in following error:

Fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKVBTG8B53VE": An unhandled exception was thrown by the application.
System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'RatingAverage', table 'simplecommerce2.dbo.Catalog_Product'; column does not allow nulls. INSERT fails.

**Comment by thiennn** [comment]
Sorry, I missed this one. While waiting for the fix, you can workaround by setting this collum to allow null

**Comment by JanSichula** [comment]
Thank you very much. I was able to follow advice at http://stackoverflow.com/questions/3889916/modify-table-how-to-change-allow-nulls-attribute-from-not-null-to-allow-null and modify appropriate column as a workaround.

P. S. The more I am getting acquainted with SimplCommerce, the more I like it.

**Comment by thiennn** [comment]
Tested with the latest source code. I don't see this issue. It has been fixed some days ago on #63

**Comment by JanSichula** [comment]
Hmm. Strange indeed. It was yesterday morning that I have cloned MASTER branch and launched all of my efforts. Will double check it again.

**Comment by thiennn** [comment]
retested, work fine
