### ISSUE TITLE
cannot access the links at /admin pages.

### ISSUE THREAD

**Issue by yalcinsinan** [simplcommerce/SimplCommerce#676]
Hi there,
I have successfully installed and run simplcommerce but I cannot access the links at /admin pages.

![questsimple](https://user-images.githubusercontent.com/115282/50104956-6b1f0880-023c-11e9-97ff-dd3cdecd9e9f.png)

**Comment by yalcinsinan** [comment]
![questsimple](https://user-images.githubusercontent.com/115282/50107473-e3d59300-0243-11e9-8dcc-27b445aae934.png)

**Comment by AlexandreBarros** [comment]
I'm in a similar problem here. One question, after your authentication process, can you access another area that needs authorization? Can you see the name of the logged user on top bar? 
Thank you, and excuse my english.
