### ISSUE TITLE
Error : Missing View Components

### ISSUE THREAD

**Issue by cevarief** [simplcommerce/SimplCommerce#68]
Build and Run successfully but when opening home page there's an error :

```bash
System.InvalidOperationException: A view component named 'SearchForm' could not be found.
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeAsync(String name, Object arguments)
   at AspNetCore._Views_Shared__Layout_cshtml.<ExecuteAsync>d__71.MoveNext() in /Views/Shared/_Layout.cshtml:line 44
```
It is also missing CartBadge and CategoryMenu.

**Comment by thiennn** [comment]
Please build the solution again. Sometimes we need to build twice

**Comment by cevarief** [comment]
Hi thanks. I'm building on mac. Rebuilding still does not make it.

**Comment by thiennn** [comment]
If you on mac, then please make sure that you build all the projects as the instruction in the Readme. For example "dotnet build \*\*/\*\*/project.json". Some module projects are not referenced by the WebHost, therefore it not be built when you build the WebHost. 

And you also need to run "gulp copy-module" to copy modules to the WebHost also.

Hope this help

**Comment by cevarief** [comment]
Solved now thanks.
