### ISSUE TITLE
How to make product options appear in the product page

### ISSUE THREAD

**Issue by wannado** [simplcommerce/SimplCommerce#686]

**Comment by wannado** [comment]
![image](https://user-images.githubusercontent.com/1073904/50583206-9ef06400-0eb3-11e9-968d-53bb6bed7413.png)

Hi I created some product variation like the above. If I understood things correctly, I was expecting the product page to show controls to select the 3 option values. But they do not show up in the product page. What am I doing wrong? Thanks in advance

**Comment by thiennn** [comment]
Sorry @wannado  for the late response. You have to add product variations for options you have added. In the first time create a product. You can generate all the possible variations based on options you have added
