### ISSUE TITLE
Will plan move to Angular 2 ?

### ISSUE THREAD

**Issue by WoolaChen** [simplcommerce/SimplCommerce#69]

**Comment by thiennn** [comment]
Angular 1.5 is perform very well. Still waiting for Angular 2 to be more mature.

**Comment by LiveLikeLastDay** [comment]
I also like to see Angular 2 in place. It's released for a while now.

**Comment by MaherJendoubi** [comment]
@thiennn Let's this dream comes true 👍

**Comment by LiveLikeLastDay** [comment]
I would suggest https://github.com/mgechev/angular-seed or https://github.com/NathanWalker/angular-seed-advanced for the backend.

I just started learning SimplCommerce.

**Comment by MaherJendoubi** [comment]
http://angularjs.blogspot.fr/2016/12/angular-160-released.html

**Comment by MaherJendoubi** [comment]
While there are a number of breaking changes between 1.5 and 1.6, many only affect very rare corner cases. There are a few significant changes that you should be aware of and we have a comprehensive migration guide to ensure that your migration goes smoothly.

**Comment by thiennn** [comment]
I am ok with upgrading to angular 2 as long as we components that we are using work well with it: summernote, smart table, ng-file-upload. 

If you have time please make some work on it, then we will review together.

@MaherJendoubi thank for the tip about angular 1.6

**Comment by MaherJendoubi** [comment]
@Kukks If you compare the number of contributors, stars, etc between https://github.com/angular/angular and https://github.com/aurelia/framework maybe that could change your mind...

**Comment by MaherJendoubi** [comment]
@Kukks in your link "Anyways... the truth is Aurelia has over 300 distinct contributors that have submitted code to the official Aurelia GitHub repositories." While ng2 repo only has 389 contributors.

**Comment by Kukks** [comment]
@MaherJendoubi Not trying to pick a fight here, so try and read a bit more and see WHEN it was posted.  I just said to also consider Aurelia, not to abandon the discussion on Ng2.

**Comment by punkouter** [comment]
Would like Ang2 since I am starting over again and since that's the current version would like to get familiar with that rather than learn the old version in 2017

**Comment by Xeevis** [comment]
+1 

Angular should be pretty mature by now? Also did quick search for mentioned components and there should be sufficient replacements. I'd hate to learn AngularJS now :(

https://github.com/valor-software/ng2-file-upload

**Comment by thiennn** [comment]
I am ok with Angular 4. But haven't had time to migrate

**Comment by thiennn** [comment]
#271 , #272 

We are now considering to migrate to Angular 4

**Comment by krristannn77** [comment]
great job thiennn!

**Comment by krristannn77** [comment]
we will wait for the angular 4 version..we are currently planning what open source to use for e-commerce nothing else is angular 4 but there's angular 4 spree commerce by aviabird which has an unfamiliar ruby on rails..asp.net core 2 + angular 4 would be the best ecommerce!
