### ISSUE TITLE
Unable to deploy on iis

### ISSUE THREAD

**Issue by amohsyn** [simplcommerce/SimplCommerce#694]
I am stuck in a weired problem of iis deployment which always shows http 500.30 ancm error i have followed all work arounds mentioned in similar issues but the issue still sustains. Installed hosting and runtime bundle but vs runs perfect however iis always shows error. Please help me out.

**Comment by thiennn** [comment]
@amohsyn Could you please get the latest code and try again. Check the file in logs folder if you still get errors. Btw, you normally have to update the Connection in the appsettings.json using User Id=;Password=

**Comment by amohsyn** [comment]
Thanks the problem is resolved. New code helped me debug the issue.

**Comment by horseyhorsey** [comment]
@thiennn 

For SimplCommerce.WebHost.csproj

Removing the explicit specification of InProcess as the hosting model, replacing
<AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel> with <RuntimeFrameworkName>Microsoft.AspNetCore.App</RuntimeFrameworkName>

aspnet/AspNetCore#6111 (comment)
