### ISSUE TITLE
Search textbox Icon in rtl languages

### ISSUE THREAD

**Issue by MarshalOfficial** [simplcommerce/SimplCommerce#699]
Hi,
In RTL Languages like Arabic and Persian search textbox icon position is corrupted,
I have attached screenshot in English and Arabic.

![rtl](https://user-images.githubusercontent.com/8558078/52537504-e7395680-2d7c-11e9-8b87-553c27a65a6d.png)

![ltr](https://user-images.githubusercontent.com/8558078/52537508-ed2f3780-2d7c-11e9-9fd0-4bc4680eacb1.png)

**Comment by justindongqiang** [comment]
Good catch.  I will have a look at it....

Thanks,
Justin

**Comment by hishamco** [comment]
May be I will have a look to it too

**Comment by hishamco** [comment]
I have a trouble in my build, by I notice the source of bug come from a CSS property, we can move inline instead or have a CSS expert to deal with this situation

**Comment by MohammadRezaRahmatzadeh** [comment]
> I have a trouble in my build, by I notice the source of bug come from a CSS property, we can move inline instead or have a CSS expert to deal with this situation

Ok, Thanks, I am challenging

**Comment by MohammadRezaRahmatzadeh** [comment]
> I have a trouble in my build, by I notice the source of bug come from a CSS property, we can move inline instead or have a CSS expert to deal with this situation

Hi bro, in this file : 
SimpleCommerce\src\SimplCommerce.WebHost\wwwroot\modules\core\site.css

.main-header .search-btn {
    background-color: #2196f3;
    border: 0;
    border-radius: 0;
    color: #fff;
    width: 38px;
    height: 38px;
    position: sticky;
    top: 0;
    right:22px;
}
I have changed position property to sticky and problem has been solved,
now css file is not checkout and i cant commit to source control and make pull requset!!!!

**Comment by MarshalOfficial** [comment]
I have made a pull request and problem solved,
Done.

**Comment by hishamco** [comment]
Right property should be changed depending on language direction. Please keep the issue open until your PR is megred
