### ISSUE TITLE
Delete all current catalog data and create sample catalog not working

### ISSUE THREAD

**Issue by mrnams** [simplcommerce/SimplCommerce#701]
When we click "Delete all current catalog data and create sample catalog"
It shows blank page only

**Comment by thiennn** [comment]
On which environment: server os, database, and on which industry: phone, fashion?

**Comment by mrnams** [comment]
Actually it works fine with local iis.
when we deploy to Plesk then it face the problem.
Database is MySQL.

**Comment by thiennn** [comment]
It might related to the setting of server, see here https://github.com/simplcommerce/SimplCommerce/issues/693

**Comment by aadviktech** [comment]
I am also facing same issue on plesk. I have also made changes in web.config, suggested in issue 693. But not resolved.
