### ISSUE TITLE
Error 400 (OAuth2 Error)!!| Register using Google account not working

### ISSUE THREAD

**Issue by mrnams** [simplcommerce/SimplCommerce#702]
Register using Google account not working,
It shows error shown in attached screenshot
Error 400 (OAuth2 Error)!!

Its show stopper issue

![2019-02-15 15_57_23-error 400 oauth2 error 1](https://user-images.githubusercontent.com/31761152/52850977-eb79c100-313a-11e9-9de6-fb1aad8d3706.png)

**Comment by thiennn** [comment]
Fixed, Btw you can create your own OAuth client for google https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?
