### ISSUE TITLE
Register using Facebook account not working,

### ISSUE THREAD

**Issue by mrnams** [simplcommerce/SimplCommerce#703]
Register using Facebook account not working,
It shows error shown in attached screenshot

Its show stopper issue
![2019-02-15 15_59_20- 8 error](https://user-images.githubusercontent.com/31761152/52851009-064c3580-313b-11e9-8451-96b769b7ad19.png)

**Comment by thiennn** [comment]
Fixed. Btw you can also create your own Facebook App https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-2.2
