### ISSUE TITLE
clarification on List<ValidationResult>

### ISSUE THREAD

**Issue by acebesmonte** [simplcommerce/SimplCommerce#704]
i would like to clarify if the IList\<ValidationResult\> can run without issue om machine is using .NET Core linux/mono? because it only exist in .NET 4.6

ref: https://docs.microsoft.com/en-us/dotnet/api/system.activities.validation.validationresults?view=netframework-4.7.2&viewFallbackFrom=netcore-2.0

/src/SimplCommerce.Infrastructure/Models/ValidatableObject.cs

```c#
        public virtual IList<ValidationResult> Validate()
        {
            IList<ValidationResult> validationResults = new List<ValidationResult>();
            Validator.TryValidateObject(this, new ValidationContext(this, null, null), validationResults, true);
            return validationResults;
        }
```

please forgive my noobness and thanks

**Comment by thiennn** [comment]
It run on well on Windows, Linux, Mac
