### ISSUE TITLE
Stock unavailablilty not checked while checkout

### ISSUE THREAD

**Issue by mrnams** [simplcommerce/SimplCommerce#706]
I have already filled issue for not having control on stock quantity.
I did manually change in stock quantity, e.g. for abc product i updated stock quantity to 2.
Now when user place order for 5 it let user proceed to checkout.

Expected behavior:
When user trying to add product quantities more than stock quantities, then checkout should be disabled

**Comment by thiennn** [comment]
@mrnams How did  you change the stock quantity?

**Comment by mrnams** [comment]
using sql query,for testing purposes i changed stock quantity.

**Comment by thiennn** [comment]
The correct way to update stock is in Inventory top menu in the Admin

**Comment by thiennn** [comment]
In the product editing page. You have to set Enable Stock Tracking to true also
