### ISSUE TITLE
Mobile verification while registering

### ISSUE THREAD

**Issue by mrnams** [simplcommerce/SimplCommerce#709]
Like amazon can we add mobile as mandatory to register,and make email optional.
Also we must enable two step security feature.
Also add OTP to verify delivery, i mean our site should send OTP to customer, customer must show/share OTP to verify customer.

**Comment by mrnams** [comment]
Guys I feel lits priority enhancement.

**Comment by thiennn** [comment]
ASP.NET Identity Core which used by SimplCommerce support this feature. But it will need a service provider to send message to mobile. We will not support this in the box but you can custom for your own need

**Comment by mrnams** [comment]
Thanks for quick look,
