### ISSUE TITLE
Portable Object localization

### ISSUE THREAD

**Issue by afernandes** [simplcommerce/SimplCommerce#711]
**PO file**
[https://docs.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-2.2](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-2.2)

OR

**JSON file**
[https://riptutorial.com/asp-net-core/example/9728/localization-using-json-language-resources](https://riptutorial.com/asp-net-core/example/9728/localization-using-json-language-resources)

**Comment by thiennn** [comment]
What are the benefit of adding that. We already manage the translation  in database

**Comment by afernandes** [comment]
PO files work well with collaborative online editing tools.

PO files support pluralization.

**Easy to copy for various environments, production, staging, development ...**

Maybe create the location the same way as the payment and shipping providers. 
Allowing you to install the location provider / plug-in via database or file.

I also like the things managed in the database, but in the case of location, from my point of view it would greatly facilitate my work.

**Comment by hishamco** [comment]
As @thiennn said we are already using database for managing the translations, but I think it need some improvement which I share some later one.

@afernandes nothing stop you to implement your own :)
