### ISSUE TITLE
Serious bug in Payment & Order creation

### ISSUE THREAD

**Issue by IamGanesh19** [simplcommerce/SimplCommerce#713]
Steps: 

- Add a product to cart and proceed to checkout.
- In checkout page select any payment provider other than CoD (Braintree / Stripe / Paypal) and don't complete the payment.
- Now in a new tab open the website and add any new product to cart.
- Go back to old tab and proceed with payment (without refreshing the page). Payment amount will get processed only for old cart amount.
- After successful payment, respective payment provider will get active cart and create order. Now the order is processed for old cart item and new cart item (added in new tab) which is wrong. User did payment only for old cart item, but system creates order with new cart item also. 

This is a serious bug in payment, where users can pay less and get more items ordered.

**Comment by thiennn** [comment]
Thank @IamGanesh19 I am working on it

**Comment by IamGanesh19** [comment]
Thanks @thiennn. Appreciate your time in resolving this issue quickly. 👍

**Comment by mrnams** [comment]
Does this solve my stock management issue?

**Comment by onurh** [comment]
If transaction fails on a payment gateway, it is not activating the passive cart again and user sees empty cart.

**Comment by thiennn** [comment]
@onurh I have create a new issue #721  according to your comment, thanks
