### ISSUE TITLE
#706 is still open

### ISSUE THREAD

**Issue by mrnams** [simplcommerce/SimplCommerce#718]

**Comment by mrnams** [comment]
Guys #706 is still reproducible, I updated stock quantity, then suppose stock quintiles are 2, now i switched to front end and successfully ordered 15 items,
Check out should check availability of stock.

Please update if you still say it's fixed, i shall share video

**Comment by thiennn** [comment]
@mrnams  what are steps you have done to update the stock quantity?

**Comment by mrnams** [comment]
Step 1
Inventory ->Stocks->(+/-) Adjusted Quantity 
Suppose  Current Quantity is 100, then add -95 in Stocks->(+/-) Adjusted Quantity, so that
 Current Quantity become 5.
Please note Stock Tracking is already enabled

Step 2
Go to front end and add same product to cart with quantity 10 and check out
it allow to checkout 10 quantities.
But we have only 5

**Comment by thiennn** [comment]
Thank you for the good information, I will take a look at this

**Comment by thiennn** [comment]
I just did the same steps as you have described above. Payment with COD, I got the error message "There are only 5 items available for ..." and the order is not created. 

As expected but might not be user friendly I will update the code to warn the user when the increase the number item in shopping cart

**Comment by thiennn** [comment]
@mrnams  fixed. Next time you just reopen the 706 instead of create a new one

**Comment by mrnams** [comment]
Yes I tried a lot, but could not get option to re-open closed issue.
Tons of thanks for quick response.

One more request, can you please take issue #720 
Its show stopper for me to deploy
