### ISSUE TITLE
BraintreeLandingViewComponent : payment process error...

### ISSUE THREAD

**Issue by horseyhorsey** [simplcommerce/SimplCommerce#726]
Is the `Amount` supposed to be an `int` for the `BraintreeCheckoutForm`? 

    InvokeAsync
        model.Amount = (int)zeroDecimalAmount;

Changing this to a `decimal` and removing the cast then I can see the next page. This is also in: 

- StripeLandingViewComponent
- StripeCheckoutForm

**Comment by thiennn** [comment]
Actually the Stripe checkout request the amount to be in 'long' I am not sure for Braintree

https://stripe.com/docs/currencies#zero-decimal

**Comment by horseyhorsey** [comment]
Thanks, I see.
