### ISSUE TITLE
Project doesnt build 

### ISSUE THREAD

**Issue by egibra** [simplcommerce/SimplCommerce#727]
Just downloaded project, opened and tried to build as in the tutorial, but got 185 errors. All errors look like this: 
"Metadata file 'C:\Users\Downloads\SimplCommerce-master\SimplCommerce-master\src\Modules\SimplCommerce.Module.Shipping\bin\Debug\netcoreapp2.2\SimplCommerce.Module.Shipping.dll' could not be found" . 
im using vs2017, .net core sdk version 2.2.1. 
what i might be doing wrong?

**Comment by thiennn** [comment]
Just close VS then reopen and build again. Or try building the solution in command line
