### ISSUE TITLE
Deleted account is not disabling

### ISSUE THREAD

**Issue by Mirivhbv** [simplcommerce/SimplCommerce#736]
If admin deletes users, they are able to sign-in still. Have to add condition for IsDeleted property at AccountController/Login action method

**Comment by horseyhorsey** [comment]
What would be best to do if account is deleted?
- Redirect to register?
- Tell them deleted?

**Comment by Mirivhbv** [comment]
If you redirect to register, they wouldn't able to register with same e-mail/username again. I think, it is a point.

**Comment by Mirivhbv** [comment]
Therefore, best option is latter one, IMO.
