### ISSUE TITLE
Support testing running with EF Core In-Memory Database Provider

### ISSUE THREAD

**Issue by tranvannhatdev** [simplcommerce/SimplCommerce#744]
Hi All,
I have reviewed this project. But i have some issue with DB when run project.
I can running project with testing or review environment with In-Memory Database

Regards,
Nhat

**Comment by thiennn** [comment]
Not tested, but I think yes. We can run SimplCommerce on SQLite, MySQL, PostgreSQL, MS SQL

**Comment by tranvannhatdev** [comment]
If project support In-Memory Database, you will easy to run it on cross platform. And will don't need to Docker, only .Net Core SDK is required.
Easy to start with starter

**Comment by thiennn** [comment]
You should use SQLite, In-Memory Database only suitable for unit-test.
