### ISSUE TITLE
Integration with ImageSharp

### ISSUE THREAD

**Issue by jindovu** [simplcommerce/SimplCommerce#745]
Hi Team,
    I have setup ImageSharp.Web to resize image on project Simplcommerce but it did not working, I have been try create another project and it working fine and I don't know why it not working on Simplcommerce please help me resolve this issue
Link setup: 
`https://github.com/SixLabors/ImageSharp.Web` 
and configuration on Simplcommerce 
Startup.cs file in SimplCommerce.WebHost
` services.AddImageSharpCore()
                .SetRequestParser<QueryCollectionRequestParser>()
                .SetMemoryAllocatorFromMiddlewareOptions()
                .SetCache(provider => new PhysicalFileSystemCache(
                    provider.GetRequiredService<IHostingEnvironment>(),
                    provider.GetRequiredService<MemoryAllocator>(),
                    provider.GetRequiredService<Microsoft.Extensions.Options.IOptions<ImageSharpMiddlewareOptions>>())
                {
                    Settings =
                    {
                        [PhysicalFileSystemCache.Folder] = PhysicalFileSystemCache.DefaultCacheFolder
                    }
                })
                .SetCacheHash<CacheHash>()
                .AddProvider<PhysicalFileSystemProvider>()
                .AddProcessor<ResizeWebProcessor>()
                .AddProcessor<FormatWebProcessor>()
                .AddProcessor<BackgroundColorWebProcessor>();`
and Configure function 
` app.UseDefaultFiles();
  app.UseImageSharp();
  app.UseStaticFiles();`

Thank you so much!

**Comment by thiennn** [comment]
You have to add  app.UseImageSharp() before app.UseCustomizedStaticFiles(env); (line 108) in the Startup.cs

**Comment by jindovu** [comment]
It's worked already
Thank you so much
