### ISSUE TITLE
Adjusting Main Page Slider Images

### ISSUE THREAD

**Issue by MarshalOfficial** [simplcommerce/SimplCommerce#748]
Hi,
where can i change main slider in home page?

![mainp](https://user-images.githubusercontent.com/8558078/55661043-c8a48880-581e-11e9-8fdf-9fb84147f7ee.png)

**Comment by thiennn** [comment]
Login to the admin. In the top menu, select Content --> Widgets. It is the Home Featured widget

**Comment by MarshalOfficial** [comment]
> Login to the admin. In the top menu, select Content --> Widgets. It is the Home Featured widget

Thanks,
