### ISSUE TITLE
Website Browser icon and mail logo

### ISSUE THREAD

**Issue by MarshalOfficial** [simplcommerce/SimplCommerce#749]
Hi,
where can i change main logo? and browser icon?

![ldd](https://user-images.githubusercontent.com/8558078/55661099-17522280-581f-11e9-9997-7045d903ed9d.png)

**Comment by thiennn** [comment]
The favicon.ico is in \SimplCommerce.WebHost\wwwroot. The logo is hard coded in the layout

**Comment by MarshalOfficial** [comment]
> The favicon.ico is in \SimplCommerce.WebHost\wwwroot. The logo is hard coded in the layout

Thank you.
