### ISSUE TITLE
Default Culture for language

### ISSUE THREAD

**Issue by MarshalOfficial** [simplcommerce/SimplCommerce#755]
Hi,
I have two Culture in my website first is English and second is Persian in culture table,
now i want when a user open website for first time for default Persian culture will selected and if he/she wants change it by partial control,
Because most of my users are Persian,
Is there any way to handle this issue?
Thanks,

**Comment by Maheshln3** [comment]
Yes.you can set the default  culture in db or in code under app.UseCustomizedRequestLocalization()

**Comment by MarshalOfficial** [comment]
@Maheshln3 
Thanks bro, I will check
