### ISSUE TITLE
Decrease Stock Value when order saved

### ISSUE THREAD

**Issue by MarshalOfficial** [simplcommerce/SimplCommerce#758]
Hi,
when i saved an order, stock for product items that were in that order were not decreased automatically, did it mentioned in code or no?

I have a sale system core back-end in below repository that designed stock value automation by purchase invoice stock will plus and by sale invoice it will decrease automatically, it can be helpful to perform it here,

https://github.com/MarshalOfficial/SaleSystem

* Stock table contains stock current value
* StockLog table is detail of increase and decreases of stock value of every products
* StockLogType indicate each log is from which process(Buy,Sale or handy Adjustment)

**Comment by thiennn** [comment]
There are 2 stock value. The Stock value in the Product table, and the stock value in Warehouse table. When an order created, the stock value in the Product table is decrease. When you create a shipping for Order, the stock in warehouse decrease. Please also be noted that the stock only decrease when stock tracking for product is enabled

**Comment by MarshalOfficial** [comment]
> There are 2 stock value. The Stock value in the Product table, and the stock value in Warehouse table. When an order created, the stock value in the Product table is decrease. When you create a shipping for Order, the stock in warehouse decrease. Please also be noted that the stock only decrease when stock tracking for product is enabled
@thiennn 
Thanks, Got it.
