### ISSUE TITLE
Image height and width

### ISSUE THREAD

**Issue by MarshalOfficial** [simplcommerce/SimplCommerce#760]
Hi,
My product images are in same width and height but i don't know why in website they are shown as below screenshot,

![images](https://user-images.githubusercontent.com/8558078/55822756-8a0c1800-5b15-11e9-99ae-81089a61420c.png)

**Comment by KettuDevelopment** [comment]
Are you sure that yout pictures have the same size? 
Do you tried it with an other language? maybe the reason are the arabic letters.

![2019-04-09 21_31_54-Nero-flavours](https://user-images.githubusercontent.com/47709914/55829461-ff281f00-5b0e-11e9-9056-24115400b016.png)

**Comment by MarshalOfficial** [comment]
> Are you sure that yout pictures have the same size?
> Do you tried it with an other language? maybe the reason are the arabic letters.
> 
> ![2019-04-09 21_31_54-Nero-flavours](https://user-images.githubusercontent.com/47709914/55829461-ff281f00-5b0e-11e9-9056-24115400b016.png)

Yes problem was pictures was not exactly same and solved,
Thanks,
