### ISSUE TITLE
Facebook / Google Login redirectUrl Issue

### ISSUE THREAD

**Issue by KettuDevelopment** [simplcommerce/SimplCommerce#761]
Hello,

after 2 days of testing im on a point where i downt know what to do. 

Working things:
First I created a Facebook and Google App. 
Configure the OAuth Redirect URIs.
Configure appsettings.json with appid and secret

But when I press the "Facebook" Button, the function "ExternalLogin" from AccountController is called. The redirectUrl of Challenge is "Core/Account/ExternalLoginCallback".

After "ExternalLogin" the Networkmonitor shows 
- 302 https://www.facebook.com/v2.12/dialog/oauth?client_id=[...]
- 302 https://localhost:49206/signin-facebook?code=AQ[...]
- 200 https://localhost:49206/login (Initiator is Facebook)

Why Facebook (and Google) returning "https://localhost:49206/login"
and not 
"https://localhost:49206/Core/Account/ExternalLoginConfirmation"

Is there any soloution?

Btw a big thanks to all people who working on this repository

**Comment by thiennn** [comment]
On Google OAuth setting. The Authorized redirect URIs should be:
https://localhost:49206/signin-google. Similarly  https://localhost:49206/signin-facebook for Facebook

**Comment by KettuDevelopment** [comment]
They are. 
The login on Facebook and Google is working. But after login on Google or Facebook I'm landing on the login page from the store.
After Google login the link is "shop.de/login#"
After Facebook login the link is "shop.de/login#_=_"

https://testshop.nero-flavours.de/login

**Comment by KettuDevelopment** [comment]
@thiennn any suggestions? 

![grafik](https://user-images.githubusercontent.com/47709914/55900257-0d397680-5bc7-11e9-9e7c-803081dc71bb.png)

**Comment by KettuDevelopment** [comment]
Problem solved.

The issue was the wrong App-Secret :/ 

Sorry
