### ISSUE TITLE
Websites use SimplCommerce

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#762]
SimplCommerce is my hobby project. I build it just because I want to practice my coding skill and for fun. I don't use it for business. 3 years have passed and now SimpleCommerce has more than 34 modules :D However, I am losing motivation to develop new features for it and I also don't have much free time recently.

To stay motivated, I would like to know how much SimplCommerce is useful for the community. So if you are able to utilize it to build real websites, please add your website url in a comment below. Thanks, I promise that SimplCommerce will always free as it is. Don't worry, there is no problem if you cannot share it because of some reasons.

**Comment by KettuDevelopment** [comment]
At this time I use it at www.testshop.nero-flavours.de 
But it don't work 100%
In 1-2 weeks the URL will change and we go online with a real shop. For German followers I will add "sofotrüberweisung.de" payment module and will post it.

**Comment by MarshalOfficial** [comment]
> SimplCommerce is my hobby project. I build it just because I want to practice my coding skill and for fun. I don't use it for business. 3 years have passed and now SimpleCommerce has more than 34 modules :D However, I am losing motivation to develop new features for it and I also don't have much free time recently.
> 
> To stay motivated, I would like to know how much SimplCommerce is useful for the community. So if you are able to utilize it to build real websites, please add your website url in a comment below. Thanks, I promise that SimplCommerce will always free as it is. Don't worry, there is no problem if you cannot share it because of some reasons.

@thiennn 
Hi bro,
I am preparing SimpleCommerce for a business project and website will be online soon as possible these days, but i have some small issues that i have created issues for them, but no body help me, i will appreciate if you help me in these hard few days that i want to publish a small commerce for my client,
Thanks,

**Comment by thiennn** [comment]
@MarshalOfficial I am sorry because I am very busy recently so that I cannot support all your issues. However for some specific needs you might have to do it by yourself, the code is open you modify it for your need

**Comment by MarshalOfficial** [comment]
@thiennn 
Sure bro, Thank you, I feel your condition and busy time,

**Comment by ytong3** [comment]
I come across SimplCommerce while doing research for a project. Just subscribed to this issue, as I am also interested in seeing how it is used in real world. Anyway, I appreciate your being open and sharing your knowledge and code. At least, I would like to give you my moral support and appreciation!

**Comment by IamGanesh19** [comment]
I am planning to use it for an online fashion portal. Will share the URL once it is up and running. In the process of creating the website, I have written a payment provider for India. Will create a PR for it very soon.

**Comment by jacek-gorgon** [comment]
Found this project just now while looking for a simple ecommerce solution to integrate with our commercial product. Will review code the code and if it's a good fit, our team might be able to contribute a bit to the project :)

**Comment by vavon** [comment]
I can’t provide a link to a site now but we are currently working on migrating one of our client site which is based on another platform to your SimplCommerce.
What make us decide to do the switch:
- the language, .Net Core
- the possibility (thanks to the license) and simplicity in altering the code
- the API approach for the admin
Front wise we won’t be using what SimplCommerce provide and use our Vue.js/Quasar front, to do so we are at the moment tweaking SimplCommerce to have a full API approach.
We are hopping on having it work by the end of the month, going under test the next and maybe going live in june.

**Comment by hederson** [comment]
@thiennn I just forked your project and loved what I saw. 
I'm trying to put online my wife's store and I found in your project a great way to do that with simplicity. I'm planning to do that in a few weeks.

**Thank you again, and dont give up.** 

PS: How can I help to develop this amazing project? I'm .net developer too.

**Comment by amohsyn** [comment]
Hello @KettuDevelopment  dear i have also a live website http://www.dressco.pk based on simplcommerce but i am facing very sluggish and painfully slow website loading almost it takes 4-5 min to complete every response. Even i reload the web it takes the same time no cashing help.

Please help me out solving this issue or could you please share your code please.

**Comment by KettuDevelopment** [comment]
Hey @amohsyn u have to check the service-timeout settings of your IIS App Pool. I solved this problem this way.

**Comment by fhebel** [comment]
Hi Thien,

thanks very much for the nice work.

I'm going to use simplcommerce for my wife's retail sales of exquisite Italian wines & olive oils. If that works out well I'll add another shop for exclusive silk suspenders.

Anyway, sometimes I have stupid newbie's questions. Where is the best place to ask them without bothering anybody?

Best regards,

Florian

**Comment by TheFirstWhiteDream** [comment]
Hi dear,
As a beginner of. net core in China, I was lucky to see this project. It's great! I hope that the author can continue to maintain and update, or give it to a community for maintenance and upgrading. At the same time, I wish you every success in your career and happiness in your family.

**Comment by andresclaros** [comment]
Hi Thien,
Great project, I use it to learn .net core and architecture.
Thank you so much.

**Comment by thiennn** [comment]
Thank you for all the comments. I will back shortly

**Comment by afernandes** [comment]
It is used on some internal sites of the company and I intend to use on other sites in the future.

I use the metronic theme on the website frontend
https://keenthemes.com/metronic/
https://keenthemes.com/metronic-v5.5.5/

On this particular site, I only use the wish list for now.
![print](https://user-images.githubusercontent.com/867631/61791740-389c4600-adf1-11e9-9e4e-aae4f634607f.png)
![print 2](https://user-images.githubusercontent.com/867631/61791741-3934dc80-adf1-11e9-8747-9683afdeb5d3.png)

**Comment by jacek-gorgon** [comment]
We have, in fact, adopted SimplCommerce in our solution. We're developing a heavily customized version for our internal needs and we'd like to port back possible bugfixes, etc., but due to the extent of those customizations, code bases will branch quite far and backporting might become impractical.

**Comment by TheTrillian69** [comment]
I'm working on the project. doing some customizations for my client. I'll share the link after it is deployed. 

Thank you so much for your support. I love the project.

**Comment by carlose18** [comment]
> Hello @KettuDevelopment dear i have also a live website http://www.dressco.pk based on simplcommerce but i am facing very sluggish and painfully slow website loading almost it takes 4-5 min to complete every response. Even i reload the web it takes the same time no cashing help.
> 
> Please help me out solving this issue or could you please share your code please.

--
How did you solve this problem?

**Comment by zhukovskyy** [comment]
> Hello @KettuDevelopment dear i have also a live website http://www.dressco.pk based on simplcommerce but i am facing very sluggish and painfully slow website loading almost it takes 4-5 min to complete every response. Even i reload the web it takes the same time no cashing help.
> 
> Please help me out solving this issue or could you please share your code please.

Sometimes it depends from IIS settings and from MS SQL database productivity...

**Comment by fhebel** [comment]
Shop for superb Italian wines (targeting EU customers), specialty Amarone Riserva & Recioto: [www.italopassione.com](https://www.italopassione.com)

**Comment by thiennn** [comment]
@fhebel  It's ok to remove or change the "Copyright © 2020 SimplCommerce" in the footer

**Comment by fhebel** [comment]
@thiennn Thanks a lot, mate!

**Comment by ibrahimclskn** [comment]
> @fhebel Altbilgideki "Telif Hakkı © 2020 SimplCommerce" i kaldırmak veya değiştirmek sorun değil

https://www.jollyjackz.com - test :)
