### ISSUE TITLE
Product category level 3 not shown in menu and not accessable

### ISSUE THREAD

**Issue by MarshalOfficial** [simplcommerce/SimplCommerce#763]
Hi, I have added some product categories as level 3 of top level, then in menu they are not shown and there is no way to access them,
see below screenshots:
![lellee](https://user-images.githubusercontent.com/8558078/55888002-d9a91d00-5bc3-11e9-96eb-d42ae9bb58bb.png)
![le](https://user-images.githubusercontent.com/8558078/55888017-e299ee80-5bc3-11e9-9a4f-91779e0b9f75.png)

**Comment by Maheshln3** [comment]
you need to loop again inside the category  childitems in CategoryMenu view component .

**Comment by MarshalOfficial** [comment]
@Maheshln3 
Thanks bro, done, Resolved with your help.
I appreciate,
