### ISSUE TITLE
PostgresException: 23505: duplicate key value violates unique constraint "PK_Core_User"

### ISSUE THREAD

**Issue by thanhtdvn** [simplcommerce/SimplCommerce#764]
After running the app with data seeding on PostgreSQL , when you register a new account on system, you will got an error related to "duplicate key value violates unique constraint PK_{Core_User}".

And this error is also occurs when you add a new entry of the entity that did seed data, ex: Address.

It seems a issue on Npgsql.EntityFrameworkCore.PostgreSQL like https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/367

Considering workaround on this.

**Comment by thiennn** [comment]
@thanhtdvn Is the problem still happen now?
