### ISSUE TITLE
Disable and Enable External Logins

### ISSUE THREAD

**Issue by MarshalOfficial** [simplcommerce/SimplCommerce#766]
Hi,
How can i disable and enable external logins? to not show and accessible with users temporary and enable every time i want,  
Thanks,

**Comment by thiennn** [comment]
You can remove them at https://github.com/simplcommerce/SimplCommerce/blob/master/src/SimplCommerce.WebHost/Extensions/ServiceCollectionExtensions.cs#L181

**Comment by MarshalOfficial** [comment]
> You can remove them at https://github.com/simplcommerce/SimplCommerce/blob/master/src/SimplCommerce.WebHost/Extensions/ServiceCollectionExtensions.cs#L181

@thiennn 
Thanks bro, Done.
