### ISSUE TITLE
error NU1001: The dependency cloudscribe.Web.Pagination >= 1.0.5 could not be resolved.

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#77]
![image](https://cloud.githubusercontent.com/assets/1798510/20314698/5cbbeb4e-ab5b-11e6-9591-0d00689f471e.png)

**Comment by thiennn** [comment]
Maybe you should run dotnet restore first?

**Comment by MaherJendoubi** [comment]
dotnet restore is the solution and we need to add it to the docs
