### ISSUE TITLE
Ignoring Stock Value on Cart and Product detail page

### ISSUE THREAD

**Issue by KettuDevelopment** [simplcommerce/SimplCommerce#770]
Hello SimplCommerce dudes,

I have noticed that you can select more products within the shopping cart and on the product detail page than are in stock.

I solved this problem inside the "ProductDetail.cshtml" by creating a hidden span object with the StockQuantity value. Within "product-detail.js" I simply compare these two values.

ProductDetail.cshtml:
`<span id="maxquantity" hidden="hidden">@Model.StockQuantity</span>`

product-detail.js: 
 ```
$('.quantity-button').on('click', function () {
        var quantityInput = $(this).closest("form").find('.quantity-field');
        var maxQuantity = $("#maxquantity");

        if ($(this).val() === '+') {
            if (parseInt(maxQuantity.text()) <= parseInt(quantityInput.val())) {
                quantityInput.val(parseInt(maxQuantity.text()));
            } else {
                quantityInput.val(parseInt(quantityInput.val(), 10) + 1);
            }
        }
        else if (quantityInput.val() > 1) {
            quantityInput.val(quantityInput.val() - 1);
        }
    });
```

However, I cannot solve this problem within the shopping cart ("cart\Index.cshtml" and "shopping-cart.js") because the StockQuantity is not passed with the CartItems.

Has anyone already recognized and solved this problem? Unfortunately, I don't have the exact overview to hand over the StockQuantity property via the CartItemVm.

**Comment by thiennn** [comment]
I remember that I have fixed at https://github.com/simplcommerce/SimplCommerce/commit/8bcc1cf9e4bac3ef344a912f25d90f21a282ae17
