### ISSUE TITLE
Multi-Language Problem

### ISSUE THREAD

**Issue by fetullahyldz** [simplcommerce/SimplCommerce#775]
Hi Is there a way to enter content into another language when adding categories and products.

**Comment by hishamco** [comment]
I don't think that we support content localization. @thiennn correct me if I'm wrong

**Comment by fetullahyldz** [comment]
now I want to write the description part of the product title turkish english and russian but when adding content it does not have a field

**Comment by thiennn** [comment]
@fetullahyldz I sorry but this feature hasn't been supported yet

**Comment by hishamco** [comment]
May be it's a good feature for upcoming releases

**Comment by thiennn** [comment]
Will  work on it this weekend

**Comment by hishamco** [comment]
We should schedule everything and focusing to stabilizing the platform rather than adding new feature

I think we should add this after the 1.0.0, let's stabilize and improve current localization module

**Comment by thiennn** [comment]
Worked, basically

**Comment by fetullahyldz** [comment]
Thank you very much has been really great health and your project will be much better

**Comment by fetullahyldz** [comment]
Hello, opera vs google chrome does not choose language in mobile browser and there seems to be a problem
