### ISSUE TITLE
@sxmny123 please describe the steps to reproduce the issue in English

### ISSUE THREAD

**Issue by sxmny123** [simplcommerce/SimplCommerce#776]
@sxmny123 please describe the steps to reproduce the issue in English

_Originally posted by @hishamco in https://github.com/simplcommerce/SimplCommerce/issues/774#issuecomment-513508179_

Questions from the Chinese netizens great god: hello, can you tell me the database is created, run the program he will not automatically give me create table tips {System. The Data. SqlClient. SqlException x80131904 (0) : object name 'Core_AppSetting' is invalid.The at

**Comment by hishamco** [comment]
Be sure to check the ConnectionString in `appSettings.json` before you run the application. Database should be created and migration should be applied

**Comment by thiennn** [comment]
Please read the README.md there is the instructions how to getting started there
