### ISSUE TITLE
Add new module error!

### ISSUE THREAD

**Issue by TheFirstWhiteDream** [simplcommerce/SimplCommerce#787]
Migration dialog box appears in vs2017 after adding new modules to replace csproj files according to documents？
![image](https://user-images.githubusercontent.com/30792241/62294205-051a8500-b49d-11e9-9cd1-0cbe4f940b03.png)

**Comment by thiennn** [comment]
Sorry I cannot read Chinese. However, you should have the latest VS 2019 and the lasted .net core sdk (2.2.401) installed

**Comment by TheFirstWhiteDream** [comment]
> Sorry I cannot read Chinese. However, you should have the latest VS 2019 and the lasted .net core sdk (2.2.401) install

Yes! I has installed. Can you give me a detail step  to  add a new moudule?
![image](https://user-images.githubusercontent.com/30792241/62337041-8e65a200-b505-11e9-8d9d-7851024435aa.png)

**Comment by TheFirstWhiteDream** [comment]
> http://docs.simplcommerce.com/en/latest/how-to-add-new-modules/

Thanks! I has successfully for add a new module!
Wish everything goes well with you！
