### ISSUE TITLE
An error in payments module

### ISSUE THREAD

**Issue by TheFirstWhiteDream** [simplcommerce/SimplCommerce#789]
![image](https://user-images.githubusercontent.com/30792241/62409623-cc012280-b60c-11e9-816f-2a101c833438.png)

**Comment by thiennn** [comment]
@TheFirstWhiteDream  Could you please create a pull request for this

**Comment by TheFirstWhiteDream** [comment]
> @TheFirstWhiteDream Could you please create a pull request for this

I'll try. I'm not very familiar with pr.

**Comment by thiennn** [comment]
fixed
