### ISSUE TITLE
Publishing Docker Images with Automated Builds

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#79]
I have create and automated build in docker hub https://hub.docker.com/r/simplcommerce/nightly-build/
Now we need to create a dockerfile to build the image. Below are some initial thoughts 
We might need to copy entire the source code into the image and do the build there because the build agent might not have dotnet sdk installed
Then similar to the step to run by command line in the readme
- Run dotnet restore
- Run dotnet build \*\*/\*\*/project.json to build all the project
- Install gulp (not sure if gulp has been installed in the base image)
- Run "gulp copy-modules" to copy modules to the WebHost
- Run EF migration to create database schema
- Connect to database and run StaticData_Postgres.sql to create static data
- Finally dotnet run to launch the app

Another problem we need to address is the postgresql data provider for EF. By default we use SQL server. But for docker it is easier to go with postgresql. The best solution is replacing the sql server data provider by postgresql data provider by command line in the docker file.

**Comment by sau-lanvy** [comment]
@thiennn, @MaherJendoubi We'll be needed to run StaticData_Postgres.sql file before using `dotnet run` command. It's hard to complete if only use dockerfile. 

How do you think if we should be used docker-compose?

**Comment by thiennn** [comment]
yeah, docker compose is a good way to go. Another option is
1. Create one image, let say from ubuntu and installed PostgreSQL, dotnet core sdk, and nodejs. Then publish this image to docker hub. 
2. Create a dockerfile from the image created above. In this case we can use psql (which installed together with PostgreSQL to run the .sql script.

**Comment by thiennn** [comment]
Yeah, it works: docker run -d -p 5000:5000 simplcommerce/nightly-build
