### ISSUE TITLE
Create sample data programatically

### ISSUE THREAD

**Issue by hishamco** [simplcommerce/SimplCommerce#803]
Switching sample date during runtime is good and bad, what I suggest to create a new APIs that let you should the sample during the development time

```csharp
app.UseSampleData(Sample.Phones);
```

**Comment by thiennn** [comment]
Sample data is just for demo purposes, I think switching at runtime is for user friendly than development time

**Comment by hishamco** [comment]
It would be nice if we provider the two approaches, one more think which I don't like is to switch from the home page, perhaps from admin is a good option, unless we think to create a setup for SimplCommerce
