### ISSUE TITLE
"isBundledWithHost": false,

### ISSUE THREAD

**Issue by ghd258** [simplcommerce/SimplCommerce#808]
![微信图片_20190904205832](https://user-images.githubusercontent.com/4811375/64256892-e5bcbf00-cf56-11e9-97cd-884615ea87d6.png)
![微信图片_20190904210001](https://user-images.githubusercontent.com/4811375/64256937-fcfbac80-cf56-11e9-8921-c0b2446ae31e.png)

**Comment by thiennn** [comment]
If you want to set isBundledWithHost: false. Then the module need publish to have all the dependencies included in the published output. Then all those file should be copied to the Modules folder in the WebHost

**Comment by ghd258** [comment]
![QQ图片20190905094349](https://user-images.githubusercontent.com/4811375/64305353-c60eb080-cfc1-11e9-9855-8a6e06510175.png)

**Comment by ghd258** [comment]
![QQ图片20190905094527](https://user-images.githubusercontent.com/4811375/64305392-e9d1f680-cfc1-11e9-818a-4629f823a6fd.png)

**Comment by ghd258** [comment]
An error occurred while starting the application.
RuntimeBinderException: 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'id'
CallSite.Target(Closure , CallSite , object )

RuntimeBinderException: 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'id'
CallSite.Target(Closure , CallSite , object )
System.Dynamic.UpdateDelegates.UpdateAndExecute1<T0, TRet>(CallSite site, T0 arg0)
CallSite.Target(Closure , CallSite , object )
SimplCommerce.Infrastructure.Modules.ModuleConfigurationManager.GetModules()+MoveNext() in ModuleConfigurationManager.cs
-
            using (var reader = new StreamReader(modulesPath))
            {
                string content = reader.ReadToEnd();
                dynamic modulesData = JsonConvert.DeserializeObject(content);
                foreach (dynamic module in modulesData)
                {
                    yield return new ModuleInfo
                    {
                        Id = module.id,
                        Version = Version.Parse(module.version.ToString())
                    };
                }
            }
SimplCommerce.WebHost.Extensions.ServiceCollectionExtensions.AddModules(IServiceCollection services, string contentRootPath) in ServiceCollectionExtensions.cs
-
        private static readonly IModuleConfigurationManager _modulesConfig = new ModuleConfigurationManager();
        public static IServiceCollection AddModules(this IServiceCollection services, string contentRootPath)
        {
            const string moduleManifestName = "module.json";
            var modulesFolder = Path.Combine(contentRootPath, "Modules");
            foreach (var module in _modulesConfig.GetModules())
            {
                var moduleFolder = new DirectoryInfo(Path.Combine(modulesFolder, module.Id));
                var moduleManifestPath = Path.Combine(moduleFolder.FullName, moduleManifestName);
                if (!File.Exists(moduleManifestPath))
                {
                    throw new MissingModuleManifestException($"The manifest for the module '{moduleFolder.Name}' is not found.", moduleFolder.Name);
SimplCommerce.WebHost.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
-
        }
        public void ConfigureServices(IServiceCollection services)
        {
            GlobalConfiguration.WebRootPath = _hostingEnvironment.WebRootPath;
            GlobalConfiguration.ContentRootPath = _hostingEnvironment.ContentRootPath;
            services.AddModules(_hostingEnvironment.ContentRootPath);
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
