### ISSUE TITLE
libs.min.css is missing

### ISSUE THREAD

**Issue by CasAl0** [simplcommerce/SimplCommerce#815]
Hy guys!
I downloaded the source code (.zip) and when I start the site it doesn't load the libs.min.css library. It seems there is not. What am I doing wrong?

Regards.

**Comment by thiennn** [comment]
Hi @CasAl0 This file is auto generated. I have made running bundle on build with the lasted commit. Please get the latest source code and build, this file will be generated

**Comment by CasAl0** [comment]
Hi thiennn.
Thank you for your answer. Now I see the file. But another, new problem has been created that I show you in the attached photo. Am I still doing something wrong? Thanks
![SimpleCommerce](https://user-images.githubusercontent.com/11368968/65610435-a0b60680-dfb1-11e9-94e4-e8e0e3f2dd04.PNG)

**Comment by thiennn** [comment]
@CasAl0 Sorry for the late response. Just close and open Visual Studio again and make sure you have dotnet core skd 3.0 installed

**Comment by CasAl0** [comment]
Thanks. Unfortunately I tried everything. To close VS, to recompile several times, to download the sources again. I'm sure I have the 3.0 SDK but the problem is not solved. I will try again. If you can think of any suggestion I gladly accept it. Thank you very much and good job.

**Comment by CasAl0** [comment]
Hi thiennn, 
I managed to solve all the problems finally! To solve the problem of references I ran VS in administrator mode and now find all the dlls and references. Perfect !

**Comment by thiennn** [comment]
Normally, we don't need to run VS in administrator, maybe your PC is special
