### ISSUE TITLE
Change content of the Razor View in a module is not Effect

### ISSUE THREAD

**Issue by lucy1417** [simplcommerce/SimplCommerce#820]
Hi @thiennn 

First, I really thank you for the great project.

I tried to download and run this project on my local and I am having an issue with this project:
- While the website is running in debug mode, I open a Razor view (.cshtml) in a module and change some text in the Razor view (.cshtml), then I refresh the browser, but the text that I was changed was not affected. I need to rebuild the project to see the text I changed

How can I resolve this issue?
I use .net core 2.2

**Comment by thiennn** [comment]
Hi @lucy1417 Yes, you have to build the project for change in Razor file effect :)

**Comment by dario-l** [comment]
I have the same issue with my project. :(

https://github.com/aspnet/AspNetCore/issues/14572

**Comment by dario-l** [comment]
I found solution. Checkout my attached earlier issue. 😃
