### ISSUE TITLE
WidGet Translation

### ISSUE THREAD

**Issue by mrccarvalho** [simplcommerce/SimplCommerce#822]
Hi,

Its possible to apply the translation Logic to translate a widget ? Like Carousel or Html WidGet ?

Does anyone know a way to achieve this?

Thanks.

**Comment by hishamco** [comment]
> Its possible to apply the translation Logic to translate a widget

Could you please elaborate?

**Comment by hishamco** [comment]
Closing this for now, while there's no respond, feel free to reopen it again
