### ISSUE TITLE
limit max character on web deploy

### ISSUE THREAD

**Issue by killerangels** [simplcommerce/SimplCommerce#823]
![2019-10-02 (1)](https://user-images.githubusercontent.com/17747049/66065730-74a10500-e51e-11e9-8c76-0d97420c98fb.png)

**Comment by thiennn** [comment]
Hi @killerangels , Please try to shorten the Path, for example C:\Projects\SimplCommerce\ or D:\Projects\SimplCommerce

**Comment by killerangels** [comment]
solved
