### ISSUE TITLE
Error in SimplCommerce.Module.SampleData script - The INSERT statement conflicted with the FOREIGN KEY constraint 

### ISSUE THREAD

**Issue by LiveLikeLastDay** [simplcommerce/SimplCommerce#83]
For example:

Because Catalog_ProductOption table is empty and follow script will be failed:
`
INSERT [dbo].[Catalog_ProductOptionCombination] ([Id], [OptionId], [ProductId], [Value]) VALUES (1, 1, 2, N'Gray')
`

And 
`
INSERT [dbo].[Core_WidgetInstance] ([Id], [CreatedOn], [Data], [DisplayOrder], [HtmlData], [Name], [PublishEnd], [PublishStart], [UpdatedOn], [WidgetId], [WidgetZoneId]) VALUES (1, CAST(N'2016-07-11 05:29:31.1868415' AS DateTime2), N'[{{"Image":"7d868097-58a5-43f8-a882-6d7872345fe7.jpg","ImageUrl":null,"Caption":null,"TargetUrl":"#"}},{{"Image":"d539b558-15ea-4317-9a5b-62e4db9a45f5.jpg","ImageUrl":null,"Caption":null,"TargetUrl":"#"}},{{"Image":"e543ed8e-5feb-4a39-8860-51d94a00ee31.jpg","ImageUrl":null,"Caption":null,"TargetUrl":"#"}},{{"Image":"c015d99d-6c3b-4337-9ba7-26822d75a8e2.jpg","ImageUrl":null,"Caption":null,"TargetUrl":"#"}}]', 0, NULL, N'Home Carousel', NULL, CAST(N'2016-07-11 05:42:44.7523284' AS DateTime2), CAST(N'2016-07-11 05:29:31.1868415' AS DateTime2), 1, 1)

The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Core_WidgetInstance_Core_Widget_WidgetId". The conflict occurred in database , table "dbo.Core_Widget", column 'Id'.
`

**Comment by thiennn** [comment]
@LiveLikeLastDay Did you run the sql script src/Database/StaticData.sql to create init data?

**Comment by LiveLikeLastDay** [comment]
You are right.

Sorry, I missed this step - "Run src/Database/StaticData.sql to create seeding data".

Close this issue.
