### ISSUE TITLE
sample container ci-build loads with a weird HTML layout

### ISSUE THREAD

**Issue by pdtit** [simplcommerce/SimplCommerce#833]
Hi, when running the sample "docker run -p 5000:80 simplcommerce/ci-build", the layout of the web page looks "weird", in some basic HTML format, not the nice looking webshop like running on IIS, or in Visual Studio mode.

Any ideas what could be wrong? tested with Chrome, Edge and Firefox

**Comment by thiennn** [comment]
The docker image is out of date. I am working on it, there is an issue with EF Core on SQLite
