### ISSUE TITLE
How can I show PaypalPlus button instead of the PaypalExpress button?

### ISSUE THREAD

**Issue by fhebel** [simplcommerce/SimplCommerce#841]
As far as I found out the button image is generated by an original Paypal script. Is there a way to tell the script to render the Paypal Plus image?

Thank you very much in advance!

**Comment by thiennn** [comment]
Paypal Plus is a different product of Paypal. They only offer this in German and Latin American markets. This is a different kind integration and required developing a new module for it. Unfortunately, at the moment, I am not sure I have enough time to implement.

**Comment by fhebel** [comment]
It seems you have already some knowledge about this. Would you be able to help me out with the specification? I’ll gladly contribute the implementation of the module.

**Comment by thiennn** [comment]
I cannot activate this feature on my sandbox account

**Comment by fhebel** [comment]
They don't have any documentation online, but it seems they're using an iFrame for this feature. I just left Paypal a message to get in touch with me. Hopefully they're going to provide documentation in English.

**Comment by fhebel** [comment]
I'm closing this issue, because we have now the StripeV2 module for credit card payments (incl. SCA, PSD2) (#906 #928)
