### ISSUE TITLE
SimplCommerce.MSBuildTasks update nuget Microsoft.Build.Utilities.Core 16.3.0

### ISSUE THREAD

**Issue by ghd258** [simplcommerce/SimplCommerce#842]
SimplCommerce.MSBuildTasks update nuget Microsoft.Build.Utilities.Core 16.3.0

**Comment by thiennn** [comment]
Could you help us?

**Comment by ghd258** [comment]
Due to special reasons, our access to foreign resources is blocked by the firewall, so we can't clone the code to modify it locally. The speed is basically several KB

**Comment by thiennn** [comment]
We don't have to use this build task any more
