### ISSUE TITLE
Adding products to warehouse throws exception:  'System.NullReferenceException'

### ISSUE THREAD

**Issue by jpb4815** [simplcommerce/SimplCommerce#843]
In the current version of the application running just the demonstration with Sample Data, I am unable to test the inventory tracking or management feature set. Anytime I try to add either one product, or all products to the warehouse selected(Default warehouse or custom made), I get a toast notification of an error stating that there is a problem in the LINQ to SQL queries written to do:      
 Add Selected product,  and Add All Products it doesn't matter which I try. It happens with the sample data as well as any product I make.

I am Logged in as:  Admin, but have also tried as a vendor for the selected warehouse.
I Traced it all the way down to the StockService.cs  AddAllProducts, / and WarehouseProductApiController.cs AddProducts. 
   No matter what I do the application is blowing up in the:  .GoupJoin portion of the Queries. I have attached the error messages as text files.
   When stepping through the process it seems to get the correct list of products to add to the Warehouse stock table, but when trying to save off the changes it blows it up every time.
This is the offending section: 
```
var stocks = await _productRepository.Query().Where(x => !x.HasOptions && x.VendorId == warehouse.VendorId)
                .GroupJoin(_stockRepository.Query().Where(x => x.WarehouseId == warehouse.Id),
                    product => product.Id, stock => stock.ProductId,
                    (product, stockCollection) => new {IsNew = !stockCollection.Any(), ProductId = product.Id})
                .Where(x => x.IsNew)
                .Select(x => new Stock
                {
                    ProductId = x.ProductId,
                    WarehouseId = warehouse.Id,
                    Quantity = 0
                }).ToArrayAsync();
            _stockRepository.AddRange(stocks);
            await _stockRepository.SaveChangesAsync();
```

I am at a loss trying to do something to get this working, I hope that there is something that somebody can point me in the right direction.
Thanks in advance for any help you can give.
[Error_Message_Add_Selected_Products.txt](https://github.com/simplcommerce/SimplCommerce/files/3848965/Error_Message_Add_Selected_Products.txt)
[Error_Message_Add_All_Products.txt](https://github.com/simplcommerce/SimplCommerce/files/3848968/Error_Message_Add_All_Products.txt)

**Comment by thiennn** [comment]
Thanks, I will look into this bug

**Comment by thiennn** [comment]
the issue has been fixed

**Comment by jpb4815** [comment]
Thanks,
What was the problem if you don't mind me asking?
John

**Comment by thiennn** [comment]
The change in EF Core 3.0 is not compatible with the previous version
