### ISSUE TITLE
Error after clicking payment button

### ISSUE THREAD

**Issue by oscararnoldo** [simplcommerce/SimplCommerce#845]
Hi
I receive an error when I try to process an order. after clicking Payment button I receive the following error:   SocketException: No connection could be made because the target machine activaly refuse it

application stops working at the following lines:
55  return await gateway.ClientToken.GenerateAsync():
53 var model = new BraintreeCheckoutForm

by the way... GREAT PRODUCT

**Comment by thiennn** [comment]
Please go to the /admin. On the menu in at the top, choose System --> Payment Provider. You can turn of Braintree. Or to make sure the setting for Braintree is correct

**Comment by oscararnoldo** [comment]
Hi Thiennn, thanks for your quick answer. I did what you said. I turned braintree off, and I was to continue, I selected Stripe as payment method, I typed demo data into Stripe window, and when
payment process started application stop working at  file StripeController.cs line 84
line code:  <var charge = stripeChargeService.Create(new ChargeCreateOptions>

thanks in advance

**Comment by thiennn** [comment]
Please make sure our Stripe configuration are correct

**Comment by oscararnoldo** [comment]
Hi Thiennn
I have verified values for private and public key if they have not changed from previous version. I mean they are correct

**Comment by oscararnoldo** [comment]
Hi Thiennn. problem fixed. I was having issues with network restrictions... I was able to make it work
