### ISSUE TITLE
Order history

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#85]
Every changes on orders should be tracked

**Comment by jducobu** [comment]
Maybe adding triggers on order table

**Comment by thiennn** [comment]
I don't think using triggers is a good way because it depend directly on specific databases and it's hard to maintain. 

I think every change on the order should publish a notification using MediatR, and the order history is saved by implement an event handler. You can checkout using MediatR in https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Core/Extensions/SimplSignInManager.cs

**Comment by thiennn** [comment]
Create new module called "SimplCommerce.Module.OrderHistory". In this module implement an event handler for OrderStatusChanged. 
Create new table to store OrderHistory and the angular directive to show history of an order

**Comment by thiennn** [comment]
for simplicity, just put OrderHistory in the Orders module
