### ISSUE TITLE
deps.json issue

### ISSUE THREAD

**Issue by pochtaliot** [simplcommerce/SimplCommerce#851]
Hi! 
According to Getting started docs https://docs.simplcommerce.com/en/latest/getting-started/

`PM> Update-Database`
`Build started...`
`Build succeeded.`
`The specified deps.json [C:\Users\...\SimplCommerce\src\SimplCommerce.WebHost\SimplCommerce.WebHost.deps.json] does not exist`

Where can I get this file?

**Comment by thiennn** [comment]
This is a auto generated file. Please try to do rebuild the application
