### ISSUE TITLE
When Use Ef migrations,can set auto migrations!

### ISSUE THREAD

**Issue by DebugOfTheRoad** [simplcommerce/SimplCommerce#853]
every time when i create a new module,  and have some entitys,  

according dotnet ef commond, (dotnet ef migrations add XXXX) for new modules,

at last , when the framework statrup, it will check new migrations ,and then update database!

**Comment by hishamco** [comment]
This is cool, if it's doable

**Comment by thiennn** [comment]
This should be handled as part of module installation. I had this in mind, but haven't got time to implement
