### ISSUE TITLE
new products can not be added to default warehouse or even a new one

### ISSUE THREAD

**Issue by oscararnoldo** [simplcommerce/SimplCommerce#857]
when you try to add products to a warehouse, a red window appears but no error message is shown. so you do not know the reason why product can not be added.

**Comment by thiennn** [comment]
Please check the error message in the Chrome Developer Tools or in the Console/Debug log. I work fine on my side

**Comment by oscararnoldo** [comment]
Hi Thien

I have done what you said. I was able to see errors in Chrome console.  there are an error on api when
you select a default warehouse in "Manage warehouse products" option, an error arise and many others when
you try to add a product to default warehouse. I will debug the application and let you know.

________________________________
De: Thien Nguyen Le Quynh <notifications@github.com>
Enviado: sábado, 4 de enero de 2020 08:32
Para: simplcommerce/SimplCommerce <SimplCommerce@noreply.github.com>
Cc: oscararnoldo <oscar.arnoldo@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [simplcommerce/SimplCommerce] new products can not be added to default warehouse or even a new one (#857)


Please check the error message in the Chrome Developer Tools or in the Console/Debug log. I work fine on my side

**Comment by jpb4815** [comment]
This is the same error as #843, if you take the update and rebuild it should fix that

**Comment by oscararnoldo** [comment]
Thanks John

________________________________
De: John Brown <notifications@github.com>
Enviado: domingo, 12 de enero de 2020 02:06
Para: simplcommerce/SimplCommerce <SimplCommerce@noreply.github.com>
Cc: oscararnoldo <oscar.arnoldo@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [simplcommerce/SimplCommerce] new products can not be added to default warehouse or even a new one (#857)


This is the same error as #843<https://github.com/simplcommerce/SimplCommerce/issues/843>, if you take the update and rebuild it should fix that

**Comment by oscararnoldo** [comment]
hey John is there a way to pay again  order with PaymentPending status

**Comment by thiennn** [comment]
> hey John is there a way to pay again order with PaymentPending status

track in #721
