### ISSUE TITLE
Unable to add Migrations

### ISSUE THREAD

**Issue by jpb4815** [simplcommerce/SimplCommerce#859]
I am trying to add some changes for a Delivery Service and When I add the classes(Domain Models) and Inherit either EntityBase or EntityBaseWithTypedId<long> for the ones with F Keys Entity framework is throwing a multitude of errors. I make the changes, build then I run Add-Migrations in the Package Manager console. If the migration is successful(about 1 in 3 times) I get prompted to Update the database as I should, But the I get the error that the objects are already in the database.
If the Migration is unsuccessful, then I get the error that the migration failed because it was unable to ready the parameter of type(key), in verbose logging that error directs me to a country Id that is a string in the configuration, but EF thinks that it is not a string.
I am very stuck, I need to keep working on what I am doing, but this not being able to migrate is holding me up.

**Comment by thiennn** [comment]
You might want to try delete the database and run Update-Database again

**Comment by jpb4815** [comment]
I have tried that repeatedly

**Comment by thiennn** [comment]
Can you share the domain model and the mapping?
