### ISSUE TITLE
Docker question: How are images in user-content supposed to work in containers?

### ISSUE THREAD

**Issue by fhebel** [simplcommerce/SimplCommerce#860]
Ciao ragazzi,

I'm trying to bring my online-shop to production using docker. Every time you upload images for widgets or products, a copy of it is stored in src/SimplCommerce.WebHost/wwwroot/user-content.

How is this supposed to work once you dispose the old container & deploy a new one?

Thanks a lot in advance.

Tanti saluti

Florian

**Comment by thiennn** [comment]
The are some approaches for this:
1. Mount folder, mount a folder in the host to a folder in the docker container
2. Using cloud services, Azure Blob and AWS S3 modules already there. http://docs.simplcommerce.com/en/latest/amazon-s3/

**Comment by fhebel** [comment]
@thiennn Thanks a lot! Sorry that I bothered you again with a stupid question.

**Comment by thiennn** [comment]
@fhebel It's ok. No one know anything
