### ISSUE TITLE
Error when trying to download an invoice from an order

### ISSUE THREAD

**Issue by oscararnoldo** [simplcommerce/SimplCommerce#861]
Enter as administrator user
select an order,
press dowload invoice button , 
an ERROR HTTP 500 appears

**Comment by thiennn** [comment]
Did you follow the docs http://docs.simplcommerce.com/en/latest/notes-for-export-pdf/

**Comment by oscararnoldo** [comment]
Hi Thien
I have read the docs and I have copied file libwkhtmltox.dll to folder C:\inetpub\wwwroot\wwwroot and I keep receiving
the error.   simplcommerce application is installed as Default web site. in IIS 7.0

________________________________
De: Thien Nguyen Le Quynh <notifications@github.com>
Enviado: lunes, 13 de enero de 2020 19:50
Para: simplcommerce/SimplCommerce <SimplCommerce@noreply.github.com>
Cc: oscararnoldo <oscar.arnoldo@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [simplcommerce/SimplCommerce] Error when trying to download an invoice from an order (#861)


Did you follow the docs http://docs.simplcommerce.com/en/latest/notes-for-export-pdf/

**Comment by thiennn** [comment]
Put in the C:\inetpub\wwwroot ? In the root folder of the website and the version must match the version of your OS (86 or 64)

**Comment by oscararnoldo** [comment]
what would be the root folder is SimplCommerce application is installed on default website on IIS?

**Comment by thiennn** [comment]
I haven't install on IIS for a long time. But the root folder of the website is the folder that contains the appsettings.json

**Comment by Dark-Yox** [comment]
I have the same problem but with Azure, it keep loading for a very long time before showing the "500 - The request timed out. The web server failed to respond within the specified time." 
It's working fine in my local IIS server but there's a problem with Azure I tried both the 32 and 64 bit version. (Putting them with the appsettings.json in "C:\home\site\wwwroot" using Kudu)
