### ISSUE TITLE
run the application on visual studio 2019

### ISSUE THREAD

**Issue by Mr-alaa** [simplcommerce/SimplCommerce#876]
Hi everybody when I try to run the application after a click on SimplCommerce.sln I got error that can't load the application and the SDK is not found despite I have dotnet --version 3.1.201 and modified the connection as written in the instructions How can I run it correctly

**Comment by thiennn** [comment]
Hi @Mr-alaa which version of VS 2029 you are using. In the top Menu in VS, go to Help --> About Visual Studio. "Version 16.4.5" is what I am using.

**Comment by thiennn** [comment]
Please get the latest code and try again. It should be ok now

**Comment by Mr-alaa** [comment]
I have already got the last version but the same thing 
For this comment which version of VS 2029 you are using. In the top Menu in VS, go to Help --> About Visual Studio. "Version 16.4.5" is what I am using.
will it be different ????

**Comment by thiennn** [comment]
VS version >= 16.3.x is required for . NET Core 3.1

**Comment by Mr-alaa** [comment]
I have vs Version 16.5.2 can you help me

**Comment by thiennn** [comment]
Please take the screenshot and share to me

**Comment by Mr-alaa** [comment]
![image](https://user-images.githubusercontent.com/20131615/78251624-e966f300-74f1-11ea-8deb-0433717a5557.png)

**Comment by Mr-alaa** [comment]
![Annotation 2020-04-02 145554](https://user-images.githubusercontent.com/20131615/78251841-35b23300-74f2-11ea-9b05-4c2e88ba6e06.jpg)

**Comment by Mr-alaa** [comment]
![Annotation 2020-04-02 1455542](https://user-images.githubusercontent.com/20131615/78251853-3a76e700-74f2-11ea-9fe9-8ddc9acef2be.jpg)

**Comment by Mr-alaa** [comment]
![Annotation 2020-04-02 1455542](https://user-images.githubusercontent.com/20131615/78251924-55e1f200-74f2-11ea-8a32-7acdb2dfafe5.jpg)

**Comment by Mr-alaa** [comment]
Can I share Skype and be thankful to you?

**Comment by thiennn** [comment]
Please open the output panel. There should be some error log here

**Comment by Mr-alaa** [comment]
![image](https://user-images.githubusercontent.com/20131615/78252822-bb82ae00-74f3-11ea-9fb5-21998c0e3c4c.png)

**Comment by Mr-alaa** [comment]
despite i download it and i check the version using cmd

**Comment by Mr-alaa** [comment]
done thanks i have fixed it thanks for your help

**Comment by Mr-alaa** [comment]
does i need to run migration or only update database
