### ISSUE TITLE
Custom css (product-detail.css) for a particular theme

### ISSUE THREAD

**Issue by fhebel** [simplcommerce/SimplCommerce#878]
Ciao ragazzi,

I'd like to make some changes in product-detail.css (mostly regarding colours), which come only into effect if a particular theme is used.
The original file is located here:
src/Modules/SimplCommerce.Module.Catalog/wwwroot/product-detail.css

I tried to put the file in
src/SimplCommerce.WebHost/wwwroot/themes/my-theme/css/
src/SimplCommerce.WebHost/wwwroot/themes/my-theme/module/catalog/
src/SimplCommerce.WebHost/Themes/my-theme/wwwroot/

Without any success.

Would someone please give me a hint?

Thanks a lot in advance

Best regards,

Florian

**Comment by thiennn** [comment]
I suggest that you create a new theme for your changes. Please follow the document here https://docs.simplcommerce.com/en/latest/theme-development/

**Comment by fhebel** [comment]
Ciao ragazzi,

I'm going to answer this question myself (maybe I'll ask @thiennn for permission to improve the documentation in this regard):

Short answer:
It's not possible to only change a css, which is part of a specific module and not part of e.g. site.min.css.

Long answer:
In my case the product-detail.css was referenced by ProductDetail.cshtml, so the way to go was to have a custom ProductDetail.cshtml (which was already there because I derived my theme from CozaStore) and to change the url pointing to a copy of product-detail.css in a folder beneath wwwroot/themes/my-theme/ ...

In other cases, where the css to alter is located in the site.min.css, you might want to simply write your own css for overriding and put it in the bundleconfig.json behind the original css.

Best regards,

Florian
