### ISSUE TITLE
Rename the docker image for site with a non-generic name

### ISSUE THREAD

**Issue by MaherJendoubi** [simplcommerce/SimplCommerce#88]
![image](https://cloud.githubusercontent.com/assets/1798510/21453906/496a121a-c914-11e6-8a7d-4645e1fdb118.png)

**Comment by thiennn** [comment]
I think, we can easily name the container by adding the parameter --name <name> to the docker run. 

`docker run --name <yourdesirename> -d -p 5000:5000 --link simpldb:simpldb simplcommerce/nightly-build`

**Comment by MaherJendoubi** [comment]
I suggest docker run --name simplcommerce -d -p 5000:5000 --link simpldb:simpldb simplcommerce/nightly-build

**Comment by MaherJendoubi** [comment]
or docker run --name simplsite -d -p 5000:5000 --link simpldb:simpldb simplcommerce/nightly-build

**Comment by thiennn** [comment]
okie, simplsite sound good. Thank you

**Comment by MaherJendoubi** [comment]
Thanks
