### ISSUE TITLE
Question: Purchase confirmation mail to the user

### ISSUE THREAD

**Issue by fhebel** [simplcommerce/SimplCommerce#885]
Ciao ragazzi,

do I understand correctly, that for the purchase confirmation mail to the user I should extend the respective ExecutePayment method of my PaymentProvider at the point where the OrderStatus is finally set to "PaymentReceived"?

`                order.OrderStatus = OrderStatus.PaymentReceived;
                await _paymentRepository.SaveChangesAsync();
                await _orderEmailService.SendEmailToUser(currentUser, order);
`

Any comment is very much appreciated.

Grazie mille in anticipo

Tanti saluti

Florian

PS: I would actually prefer some mechanism where the email send task is persisted after the payment is received, then I would trigger it right away. This would give the possibility to retry or resend an email if it failed.

**Comment by hishamco** [comment]
If I understand your question correctly, based on the `OrderStatus` you can send different emails to the user for example:

- The transaction is failed due incorrect payment
- The transaction is succeed
- ... etc

**Comment by fhebel** [comment]
Thanks a lot @hishamco! Your answer shows me that I'm on the right track ...
