### ISSUE TITLE
Bug: Propagation of "IsProductPriceIncludeTax" in CartService.MigrateCart is missing

### ISSUE THREAD

**Issue by fhebel** [simplcommerce/SimplCommerce#886]
[bug_cartservice_is_product_price_include_tax_missing.patch.txt](https://github.com/simplcommerce/SimplCommerce/files/4539603/bug_cartservice_is_product_price_include_tax_missing.patch.txt)

**Comment by thiennn** [comment]
Hi @fhebel 

Could you please create a pull request. It will be much helpful
