### ISSUE TITLE
Missing `ModuleInitializer` for EmailSenderSendgrid?

### ISSUE THREAD

**Issue by mdekrey** [simplcommerce/SimplCommerce#900]
I am trying to switch my app over to using the Sendgrid module from SMTP. However, switching out the module reference results in `SimplCommerce.Module.EmailSenderSendgrid.EmailSender` never being registered with DI.

I believe it's missing a `ModuleInitializer` similar to [`SimplCommerce.Module.EmailSenderSmtp.ModuleInitializer`](https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.EmailSenderSmtp/ModuleInitializer.cs). I can create a PR with that missing file if necessary, but if there's a more correct way, I would prefer that!

**Comment by thiennn** [comment]
Yes, you are correct. Waiting for your PR
