### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by alhaditraining** [simplcommerce/SimplCommerce#905]
Hi I get this error
MSB3231	Unable to remove directory "obj\Debug\netcoreapp3.1\Razor\". Could not find a part of the path 'Default.cshtml.g.cs'.
try to remove the obj file but same error

**Comment by thiennn** [comment]
We haven't seen this error. Could you please describe steps to reproduce.

**Comment by hishamco** [comment]
Try to clean the solution

**Comment by alhaditraining** [comment]
thanks ,
we can close it
