### ISSUE TITLE
Why so many resource folders in bin??

### ISSUE THREAD

**Issue by amohsyn** [simplcommerce/SimplCommerce#919]
When compiling or publishing i find so many resource folders containing humazier dll. I want to know where these folders come from?? And what use of it..

Regards.

**Comment by hishamco** [comment]
Please screen shot

**Comment by amohsyn** [comment]
> Please screen shot
@
![Screenshot_2020-07-20-15-17-36-806_com android chrome](https://user-images.githubusercontent.com/9105786/87927513-c3635f80-ca9c-11ea-8342-f7eb614bd8c9.png)

#

**Comment by hishamco** [comment]
This is just a localization versions

**Comment by sefacan** [comment]
Hi,
You can look at that
https://stackoverflow.com/a/61798395

**Comment by amohsyn** [comment]
@sefacan Thanks buddy.

**Comment by amohsyn** [comment]
Issue resolved by adding following line in csproj file:

<SatelliteResourceLanguages>ru;en-US</SatelliteResourceLanguages>

Include only the desired cultures separated by ';'.
