### ISSUE TITLE
Menu management 

### ISSUE THREAD

**Issue by thiennn** [simplcommerce/SimplCommerce#92]
Allow admin can add or remove item from the main navigation

**Comment by dohuy91** [comment]
Hi a, may I take this one ? I will implement this feature based on the way wordpress manages
https://www.youtube.com/watch?v=ZzNwCHG_VWk

Thanks
Huy

**Comment by thiennn** [comment]
Look great, I like it

**Comment by MaherJendoubi** [comment]
I like it too

**Comment by thiennn** [comment]
Hi @dohuy91 ,

I was wondering whether it is a good idea to tight couple menu item to Category, Brand, Product, etc.
Maybe we should keep them separate, and we should have to table 1. Menu; 2. MenuItem. MenuItem should have hierarchy (ParentId).

Yeah, I am open for discussion

**Comment by thiennn** [comment]
Oh yes, There is a table call Core_Entity. You can link to that one

**Comment by dohuy91** [comment]
Great, understood. I will create 2 table Menu, MenuItem and link them to Core_Entity

**Comment by balasratran** [comment]
I like it too

**Comment by balasratran** [comment]
Do not know when this function will complete, I'm waiting?

**Comment by MaherJendoubi** [comment]
cc @dohuy91

**Comment by thiennn** [comment]
```cs
public class Menu : EntityBase
 {
        publicbool IsPublished { get; set; }

        public string Name {get;set;}

        public bool IsSystem { get; set; }

        public IList<MenuItem> MenuItems { get; protected set; } = new List<MenuItem>();
}

public class MenuItem : EntityBase
{
    public long? ParentId { get; set; }
	
    public MenuItem Parent { get; set; }
	
    public long MenuId { get; set; }
	
    public Menu Menu { get; set; }
	
    public long? EntityId { get; set; }
	
    public Entity Entity { get; set; }
	
   public string CustomUrl { get; set; }
}
```
