### ISSUE TITLE
Why can't i manage related products while creating or editing??

### ISSUE THREAD

**Issue by amohsyn** [simplcommerce/SimplCommerce#920]
![Image 2](https://user-images.githubusercontent.com/9105786/87963434-228f9700-cad2-11ea-8ed9-146ec87ae33b.png)

**Comment by amohsyn** [comment]
@thiennn Please help me fix this!

**Comment by fhebel** [comment]
Hi @amohsyn,

you have to fix the reference, the admin path segment is missing. I’ll try to send you the fix tonight.

Best regards,

Florian

**Comment by amohsyn** [comment]
@fhebel  Dear so nice of you , i 'll be waiting...

**Comment by fhebel** [comment]
@amohsyn Here you are. The fix is really simple. You can apply it yourself in the meantime or wait for @thiennn to merge the pull request.

**Comment by amohsyn** [comment]
@fhebel  Thanks a lot dear. Fixed it.
