### ISSUE TITLE
where is "product-selection-directive" is defined in solution? How can i customise it??

### ISSUE THREAD

**Issue by amohsyn** [simplcommerce/SimplCommerce#922]
Please help me out understand the angular directive in catalog module. How can i add a new one like "product-selection-directive"

Thanks.

@thiennn 
@fhebel 
@sefacan
@hishamco

**Comment by fhebel** [comment]
Hi @amohsyn,

I recently added the possibility to reference "Related Pages" to products, which means that you can simply reference (and reuse) CMS pages on the product details page.

It works like this:
- add a new Javascript-file (e.g. src/Modules/SimplCommerce.Module.Catalog/wwwroot/admin/product/page-selection-directive.js), which references the html-part (this was the templateUrl I fixed)
- add your new js file to src/Modules/SimplCommerce.Module.Catalog/bundleconfig.json
- add the respective html (e.g. src/Modules/SimplCommerce.Module.Catalog/wwwroot/admin/product/page-selection-directive.html)
- extend the src/Modules/SimplCommerce.Module.Catalog/Areas/Catalog/Controllers/ProductApiController.cs to serve the gridData needed for your purpose

I hope that helps.

Best regards,

Florian
