### ISSUE TITLE
How can i change the route path of entity say blog??

### ISSUE THREAD

**Issue by amohsyn** [simplcommerce/SimplCommerce#929]
I want route path like this::
Http://localhost/blog/blog-1

Please help.

**Comment by fhebel** [comment]
Hi @amohsyn,

In Startup.cs you will find the following code:
```C# 
app.UseEndpoints(endpoints =>
{
    endpoints.MapDynamicControllerRoute<SlugRouteValueTransformer>("/{**slug}");
    endpoints.MapControllerRoute(
        name: "areas",
        pattern: "{area:exists}/{controller=Home}/{action=Index}/{id?}");
    endpoints.MapControllerRoute(
        name: "default",
        pattern: "{controller=Home}/{action=Index}/{id?}");
});
```
So your question is regarding the route named "areas":

Let's do a small example:
https://localhost:49206/Catalog/Category/CategoryDetail?Id=1

According to our code above our **first path segment** is an area e.g. Catalog
The **second path segment** is the controller name without the "Controller" suffix e.g. Category
The **third path segment** is the method in the respective controller e.g. CategoryDetail
The query string contains all necessary parameters for the method e.g. Id=1

Ok, so let's put all the parts together:

For our example we have to find the respective controller, which is in our case the CategoryController.cs

There you will find an AreaAttribute on the class

```C#
[Area("Catalog")]
```

So this would be our first path segment.

I hope that helps.

Best regards,

Florian

PS: https://www.yogihosting.com/aspnet-core-areas
PPS: For the api controllers you could use also the RouteAttribute
```C#
[Route("api/categories")]
```
