### ISSUE TITLE
CSS issue - The Search textbox intersect with Category dropdown

### ISSUE THREAD

**Issue by WahidBitar** [simplcommerce/SimplCommerce#936]
The Search textbox intersect with Category dropdown height and the height of the Categories filter dropdown isn't the same as search textbox.

![image](https://user-images.githubusercontent.com/1735126/92106117-910f8680-edec-11ea-9de3-cdacef49ec99.png)

**Comment by SwarnenduDasKW** [comment]
Made the following change to fix the issue. Adjusted the width of the search input and made the height same for input box and dropdown. 


.main-header .search-input {
    width: calc(100% - **225px**);
}

.main-header .search-input input {
    **height: 38px;**
    width: 100%;
    max-width: 100%;
    border-radius: 0;
}

.main-header .search-category select {
    **height: 38px;**
    border-radius: 0;
    width: 180px;
    **margin-left:10px;**
}

![image](https://user-images.githubusercontent.com/41870788/92118719-dae47680-edc4-11ea-94b4-f314a4532bd5.png)

**Comment by TATARPRO** [comment]
This issue should be closed if it has been resolved

**Comment by hishamco** [comment]
@SwarnenduDasKW could please push a PR for this fix

@WahidBitar could you please confirm if this fixed your issue?

**Comment by WahidBitar** [comment]
Waiting @SwarnenduDasKW Pull Request

**Comment by SwarnenduDasKW** [comment]
@WahidBitar Hey Man, Sorry for the late response. The issue is fixed and pull request is created. Thanks!!
![image](https://user-images.githubusercontent.com/41870788/112258317-b060ea80-8c3c-11eb-8cdd-f2d5df287e6b.png)
