### ISSUE TITLE
Getting SQL Exception while running the project from Visual Studio locally.

### ISSUE THREAD

**Issue by abhimjoshi** [simplcommerce/SimplCommerce#94]
Getting an error while connecting to SQL server local database when running project for the first time using Visual Studio.

It seems that application is trying to connect database using Windows authentication Username, but it should use SQL Username/ Password I have mentioned in the connection string in AppSettings.json

**Error:** 
SqlException: Login failed for user {windowsDomainName}\abhishek.j'

**See the settings I have configured below:**

> 
> {
>   "ConnectionStrings": {
>     "DefaultConnection": "Server=**(local);Database=SimplCommerce;uid=sa;pwd=mypwd123**;Trusted_Connection=True;MultipleActiveResultSets=true;Integrated Security=true"
>   },
>   "Logging": {
>     "IncludeScopes": false,
>     "LogLevel": {
>       "Default": "Debug",
>       "System": "Information",
>       "Microsoft": "Information"
>     }
>   },
>   "Storage": {
>     "StorageType": "**LocalStorage**", //Set "AzureStorage" or "LocalStorage"
>     "AzureStorage": {
>       "StoragePath": "http://127.0.0.1:10000/devstoreaccount1/images/",
>       "StorageConnectionString": "DefaultEndpointsProtocol=https;AccountName=account-name;AccountKey=account-key"
>     }
>   } 
> }

See image below for the more details about error:

![sqlsqlerror](https://cloud.githubusercontent.com/assets/7397820/21515467/08101e6e-ccf6-11e6-9888-a9b2f2411510.png)

**Comment by thiennn** [comment]
@abhimjoshi 
Can you try removing the Trusted_Connection=True; and the Integrated Security=true; in the connection string

**Comment by abhimjoshi** [comment]
@thiennn Thanks for the answer. I removed both the settings from connection string and error has gone now.

However, now I am getting different error (see below), which is related to some database objects (tables) are not found. Since we're using Entity framework, the object should be automatically generated, but somehow it is not generating OR may be some other issue is there. Would you be able to identify the root cause of error? see below the error:

**Error:**
> 
> SqlException: Invalid object name 'Localization_Resource'.
> 
> System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
> DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(SimplCommerce.Infrastructure.Data.IRepository`1[SimplCommerce.Module.Localization.Models.Resource])' on type 'EfStringLocalizerFactory'. ---> Invalid object name 'Localization_Resource'. (See inner exception for details.)

**Comment by thiennn** [comment]
You need to run the 'Update-Database' to generate tables. Please see the [readme](https://github.com/simplcommerce/SimplCommerce#using-visual-studio-2015-update-3) for more detail

**Comment by abhimjoshi** [comment]
@thiennn Thanks for the information. Things are working well now.
