### ISSUE TITLE
Lỗi khi chạy "dotnet ef database update trên Centos 7"

### ISSUE THREAD

**Issue by farmerjs** [simplcommerce/SimplCommerce#95]
Chào a,

Tôi đang muốn chạy project trên Centos 7 với database là PostgreSQL khi chạy đến đoạn phát sinh schema database thì báo lỗi, mặc dù trước đó build như hướng dẫn "dotnet build **/**/project.json" vẫn thành công.
![netcore](https://cloud.githubusercontent.com/assets/6466938/21526007/b3613566-cd53-11e6-98da-dd82d06e5f6b.jpg)

Nhờ sự hỗ trợ của anh,

Cám ơn anh.

**Comment by thiennn** [comment]
Chào @farmerjs ,

Entity framework có migration có 1 issue. Bạn có thể workaround bằng cách vào thư mục SimplCommerce.WebHost/Migrations, open file SimplDbContextModelSnapshot.cs, và *_initialShema.Designer.cs remove hết những câu lệnh using SimplCommerce.Module.*.Models; đi.
Sau đó chạy lệnh dotnet ef database update lại là ok.

**Comment by farmerjs** [comment]
Cám ơn anh @thiennn đã chạy thành công
Em mới nhảy qua Linux mãi mới import đống data vào được :D

Trên môi trường production mình sẽ thay đổi URL  .UseUrls("http://*:5000") ->      .UseUrls("http://domain:80") phải ko anh @thiennn  nhỉ?

**Comment by thiennn** [comment]
Cool, 
Đổi qua .UseUrls("http://domain:80") cũng được, nhưng trên production thì mình nên có 1 con reverse proxy ở phía trước như nginx chẳn hạn
