### ISSUE TITLE
Login fail

### ISSUE THREAD

**Issue by nqtuyen** [simplcommerce/SimplCommerce#958]
After publish and install on server (MS 2012R2), I try to login but it return login screen, can not go to admin site. When debug, login is OK.

Thanks!

**Comment by sergiohinojosa** [comment]
Hi @nqtuyen what kind of browser are you using? Is it chrome? I'm also experiencing issues login in with chrome (admin account or others) I think it has to do with the redirect at login. It works with Safari and Firefox though.

Here is what happens on chrome. Login returns 302 and then loads  home with a 200. No error (at least not easy visible on the front) 
![image](https://user-images.githubusercontent.com/20834538/101897411-ccb7aa80-3baa-11eb-9e6b-cce69dec805f.png)

**Comment by nqtuyen** [comment]
Thank for your support. I determined why I did login error. Because of software use https but my server did not supported. So when I installed Let' Encrypt SSL certificate, it worked well. Hope others user will find it helpful if install it in production. Many thank!

**Comment by nqtuyen** [comment]
should use https.
