### ISSUE TITLE
[Question] Is there an easy way to import products from a JSON file

### ISSUE THREAD

**Issue by Dark-Yox** [simplcommerce/SimplCommerce#974]
I have a huge JSON file and I need to import data from it to the database but I'm not familiar a lot with SQL especially when there's multiple tables affected. 

The products in my JSON file looks like this :

` { 
    "Id": 1,
    "Brand": "Brand name",
    "Name": "Product name",
    "Slug": "product_name",
    "Description": "<div id="tab_product_page"> Some HTML </div>",
    "ImageUrl": "https://i.redd.it/bp1mmcoc8xe31.jpg",
    "Category": "Category name",
    "SubCategory": "Subcategory name",
    "Price": 420.555,
    "OldPrice": 666.69
  }`

**Comment by TATARPRO** [comment]
You can, but in order to do that, you'll have to create a special module for that then perform all normalizations there so that they can match the current product model

**Comment by Dark-Yox** [comment]
If we ignore the media (ImageUrl), won't it be easier to write an SQL query to add the product ?

**Comment by TATARPRO** [comment]
If you ignore media, how do you then intend to give your product an image?

**Comment by Dark-Yox** [comment]
I still need to understand how the media is stored and linked to the product, that's why I suggested to ignore it for now.

**Comment by TATARPRO** [comment]
Take a look at [product.cs](https://github.com/simplcommerce/SimplCommerce/blob/master/src/Modules/SimplCommerce.Module.Catalog/Models/Product.cs), it has a property called medias which holds a reference to all the medias uploaded with that product. The include images, instruction manuals and all sort of media content. At line [365](https://github.com/simplcommerce/SimplCommerce/blob/4b84142fc9e1eb9fb5ddca35c7bb49c9f0122649/src/Modules/SimplCommerce.Module.Catalog/Areas/Catalog/Controllers/ProductApiController.cs#L365), it calls `SaveProductMedias(model, product);` At product medias, you'll see that there, its iterating through the images and documents sent with the model then creating a Media object to add to the product which is to be saved to the db. All the items added to product are created and saved to the db when the transaction is committed. This will ensure that everything is created. If one fails, everything fails.

**Comment by Dark-Yox** [comment]
I forgot to close this issues. Thank you for your help sir, I did as you said, and managed to make it work.
There's also SQL files inside the SampleData module if someone need it.
