### ISSUE TITLE
Demo admin page not loading

### ISSUE THREAD

**Issue by danijeljw-RPC** [simplcommerce/SimplCommerce#989]
Clicked on the link on main page for admin demo page, and it brought a page suggesting to open a ticket.

Link clicked: http://demo.simplcommerce.com/admin

Outcome:

![Screen Shot 2021-06-07 at 7 26 17 pm](https://user-images.githubusercontent.com/69200012/120992761-403b1d00-c7c6-11eb-81fd-2b304206f1a8.png)

**Comment by thiennn** [comment]
It should work now
