### ISSUE TITLE
error when running smplcommerce

### ISSUE THREAD

**Issue by cumironin** [simplcommerce/SimplCommerce#99]
All the step that require to do on list is pass, but when i hit "dotnet watch run"  or "dotnet run"  my page return to : 

Error.

An error occurred while processing your request.

Please create an issue in https://github.com/simplcommerce/SimplCommerce/issues. Thanks

is there any recent bugs or something, cause on cli i don't see any raise problem at all.

**Comment by thiennn** [comment]
@cumironin Please tell more about the environment are you running on, the error message etc.

**Comment by cumironin** [comment]
i'am work with mac env (sierra), .net core 1.1, using postgre db, it's all ok no problemo, but when i run the page turn it that way ?

check code below for "dotnet watch run" : 

```
☁  SimplCommerce.WebHost  dotnet watch run
[DotNetWatcher] info: Running dotnet with the following arguments: run
[DotNetWatcher] info: dotnet process id: 54182
Project SimplCommerce.Infrastructure (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project SimplCommerce.Module.Core (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project SimplCommerce.Module.Localization (.NETStandard,Version=v1.6) was previously compiled. Skipping compilation.
Project SimplCommerce.WebHost (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
Hosting environment: Production
Content root path: /Users/cumironin/Projects/SimplCommerce-master/src/SimplCommerce.WebHost
Now listening on: http://127.0.0.1:5000
Application started. Press Ctrl+C to shut down.
```

**Comment by thiennn** [comment]
@cumironin ,

The web site ran successfully, open the browser and to go http://localhost:5000, or http://127.0.0.1:5000
